10.0 pos multi session offline order
itpp-labs/pos-addons pull request #1000
Opened 2019-05-18 17:24 UTC by KolushovAlexandr

2019-05-20 12:21 UTC, GabbasovDinar commented
![photo5411400528442797070](https://user-images.githubusercontent.com/15119940/58021190-b4dd8900-7b23-11e9-9515-298b60a89515.jpg)

2019-05-20 12:32 UTC, yelizariev requested changes
![image](https://user-images.githubusercontent.com/186131/58022285-975dee80-7b26-11e9-8135-5f900958c6ad.png)

2019-05-20 12:32 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            console.log(orders)
To delete

2019-05-21 13:50 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-23 11:37 UTC, yelizariev approved these changes

2019-05-23 11:37 UTC, merged