:ambulance: error with orders have same numberspaid offline and onlin…
itpp-labs/pos-addons pull request #1005
Opened 2019-05-25 15:07 UTC by KolushovAlexandr

…e on different POSes

2019-05-27 13:52 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-28 09:04 UTC, yelizariev requested changes

2019-05-28 09:04 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **Fix:** Error with orders have the same numbers were paid offline and online on different POSes
How it works now? What will happened in the described scenario?

2019-05-29 08:36 UTC, yelizariev approved these changes

2019-05-30 13:53 UTC, merged