10.0 pos ms issues 3
itpp-labs/pos-addons pull request #1035
Opened 2019-06-24 13:05 UTC by KolushovAlexandr

2019-06-25 07:39 UTC, yelizariev requested changes

2019-06-25 07:39 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            }
seems ok

2019-06-25 07:39 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                                                                      ('state', '=', 'draft'),
:+1:

2019-06-25 07:39 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                'multi_session_ID': self.multi_session_ID,
:+1:

2019-06-25 07:39 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                    .create({'multi_session_ID': self.multi_session_ID, 'pos_ID': pos_ID, 'user_ID': user_ID})
Looks complicated. Can we simplify it? May be
```

pos = self.env['pos_multi_session_sync.pos'].search([("pos_ID", "=", pos_ID)])

if len(pos) > 1:
    # workaround for deployment with a bug
   # TODO: remove this in odoo 13 
    pos.unlink()
    pos = None

if not pos:
     pos = ...create(...)

```

2019-06-25 07:39 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                same_id_poses.multi_session_ID = self.multi_session_ID
Is it possible, that ``same_id_poses.multi_session_ID != self.multi_session_ID``?

2019-06-25 07:39 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                             .search([('multi_session_ID', '=', self.multi_session_ID), ('state', '=', 'draft'),
:+1:

2019-06-25 07:48 UTC, KolushovAlexandr commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                same_id_poses.multi_session_ID = self.multi_session_ID
yes if `pos.config was assigned to a different multi session`

2019-06-25 07:49 UTC, KolushovAlexandr commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                same_id_poses.multi_session_ID = self.multi_session_ID
before those changes it created a new record with the same `pos_ID` and different `multi_session_ID`

2019-06-25 10:24 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                same_id_poses.multi_session_ID = self.multi_session_ID
I mean that same_id_poses is the same record as self.

2019-06-25 10:33 UTC, yelizariev commented on pos_multi_session_sync/models/pos_multi_session_sync_models.py
> +                same_id_poses.multi_session_ID = self.multi_session_ID
ok, I got it. self is not a record of ``pos_multi_session_sync.pos``

2019-06-27 06:23 UTC, yelizariev approved these changes

2019-06-27 08:12 UTC, ilmir-k approved these changes

2019-06-27 08:14 UTC, merged