:heart_eyes: show the autostart_longpolling setting after install Mul…
itpp-labs/pos-addons pull request #1044
Opened 2019-07-02 15:09 UTC by KolushovAlexandr

…ti Session module

2019-07-03 10:37 UTC, ilmir-k commented
the strange travis error that is not related to the update

2019-07-03 10:41 UTC, ilmir-k approved these changes

2019-07-03 10:41 UTC, ilmir-k requested changes
KolushovAlexandr add changelog record please, it's enough for ``pos_longpolling`` only

2019-07-03 13:04 UTC, ilmir-k approved these changes

2019-07-04 09:12 UTC, yelizariev approved these changes

2019-07-04 09:13 UTC, merged