:ambulance: possible multiple multisessions with same multisession ID
itpp-labs/pos-addons pull request #1046
Opened 2019-07-08 16:54 UTC by KolushovAlexandr

2019-07-08 17:40 UTC, yelizariev reviewed
You will need to update version

2019-07-09 07:17 UTC, Ramil-Mukhametzyanov approved these changes

2019-07-09 08:46 UTC, yelizariev requested changes

2019-07-09 08:46 UTC, yelizariev commented on pos_multi_session_sync/controllers/pos_multi_session.py
> +            multi_session = ms_model.write({'dbname': dbname})
wrong code and Impossible case ( multi_session.dbname is always dbname, ms_model is not a recordset

2019-07-09 09:02 UTC, yelizariev commented on pos_multi_session_sync/controllers/pos_multi_session.py
> +            multi_session.unlink()
Any idea how it's possible? Anyway, you need to add a comment about this strange case

2019-07-09 13:24 UTC, yelizariev commented on pos_multi_session_sync/controllers/pos_multi_session.py
> +            multi_session = multi_session.write({'dbname': dbname})
Why?

2019-09-02 06:07 UTC, yelizariev approved these changes

2019-09-02 06:08 UTC, merged