:arrow_up::one::one: pos_journal_pin
itpp-labs/pos-addons pull request #1051
Opened 2019-07-17 11:20 UTC by fedoranvar

2019-07-17 11:24 UTC, KolushovAlexandr commented on pos_journal_pin/README.rst
> +Demo: http://runbot.it-projects.info/demo/pos-addons/11.0
not all references are changed

2019-07-17 11:25 UTC, KolushovAlexandr commented on pos_journal_pin/static/src/js/main.js
> +            var is_manager = _.include(this.pos.get_cashier().groups_id, manager_group_id);
you can add yourself to contributors here

2019-07-17 11:26 UTC, KolushovAlexandr requested changes
some minor changes are needed

2019-07-17 11:57 UTC, KolushovAlexandr commented on pos_journal_pin/doc/index.rst
>  Journal
Please also fix this article because there is no 'Payment Methods' menu In **point of sale** menu anymore

2019-07-17 11:58 UTC, KolushovAlexandr requested changes
Configuration

2019-07-17 12:15 UTC, KolushovAlexandr approved these changes

2019-07-18 07:52 UTC, Ramil-Mukhametzyanov requested changes
Demo user cannot enter a POS.
The error message is below.

Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Administration/Settings
(Document model: ir.module.module) - (Operation: read, User: 5)

2019-07-23 10:59 UTC, Ramil-Mukhametzyanov requested changes
Cannot enter a value in the Tendered column on the payment screen if there is at least one payment method that requires manager permission. The issue happens not only for POS User, but also for POS Manager.

2019-07-23 11:59 UTC, Ramil-Mukhametzyanov approved these changes
it works well :+1:

2019-07-23 12:00 UTC, Ramil-Mukhametzyanov requested changes
price required

2019-07-23 18:03 UTC, KolushovAlexandr requested changes

2019-07-23 18:03 UTC, KolushovAlexandr commented on pos_journal_pin/static/src/js/main.js
> +          	if (paymentlines.length > 0 || this.pos.cashregisters[0].journal.ask_manager === false) {
if (paymentlines.length || !this.pos.cashregisters[0].journal.ask_manager) {

2019-07-23 18:03 UTC, KolushovAlexandr commented on pos_journal_pin/static/src/js/main.js
> +          	if (paymentlines.length > 0 || this.pos.cashregisters[0].journal.ask_manager === false) {
also check the case if there is no any pymentmethods for POS. It should give an error some kind of 
**con not take property `journal` of undefined**

2019-07-23 18:03 UTC, KolushovAlexandr commented on pos_journal_pin/static/src/js/main.js
> +          	if (paymentlines.length > 0 || this.pos.cashregisters[0].journal.ask_manager === false) {
fix indents Everywhere

2019-07-23 18:03 UTC, KolushovAlexandr commented on pos_journal_pin/static/src/js/main.js
> +
keep history clean. here and below

2019-07-23 18:03 UTC, KolushovAlexandr commented on pos_journal_pin/models/models.py
>  # Copyright 2018 Kolushov Alexandr <https://it-projects.info/team/KolushovAlexandr>
please fix the year for me, it should be 2019

2019-07-24 13:04 UTC, KolushovAlexandr approved these changes

2019-07-29 07:21 UTC, em230418 approved these changes

2019-07-29 07:23 UTC, em230418 commented
> price required

@Ramil-Mukhametzyanov, looks like it is resolved: https://github.com/it-projects-llc/pos-addons/pull/1051/files#diff-63bd019ceace583987ef38b91db72a4f

2019-08-05 07:46 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-05 07:46 UTC, merged