:ambulance: error after an order was created offline
itpp-labs/pos-addons pull request #1052
Opened 2019-07-17 14:55 UTC by KolushovAlexandr

2019-07-18 06:33 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/doc/changelog.rst
> +- **Fix:** Synchrom=nization error after an order was created offline
please correct it here: "Synchrom=nization"

2019-07-18 06:33 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_sync/doc/changelog.rst
> +- **Fix:** Updated 'update_revision_ID' message
:+1:

2019-07-18 06:37 UTC, Ramil-Mukhametzyanov requested changes
After exiting POS session and entering again, orders disappear

2019-08-27 09:11 UTC, kaadevelop reviewed
**2 installable** modules are updated:
```
├─ pos_multi_session/
|  ├─ __manifest__.py
|  ├─ doc/
|  |  └─ changelog.rst
|  └─ static/
|     └─ src/
|        └─ js/
|           └─ pos_multi_session.js
└─ pos_multi_session_sync/
   ├─ __manifest__.py
   ├─ doc/
   |  └─ changelog.rst
   └─ models/
      └─ pos_multi_session_sync_models.py
```

**0 not installable** modules are updated:
Not installable modules remain unchanged.

> sent by [review-bot](https://odoo-devops.readthedocs.io/en/latest/git/github_review_bot.html)

2019-08-27 09:11 UTC, kaadevelop commented on pos_multi_session/doc/changelog.rst
> +
Has to be tested

2019-08-27 09:11 UTC, kaadevelop commented on pos_multi_session_sync/doc/changelog.rst
> +
Has to be tested

2019-08-27 10:18 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-27 12:00 UTC, em230418 requested changes
1.

Тесты в одуап проваливаются, если еще pos_restaurant поставить.
Создавал базу следующей командой:
```
docker-compose run dodoo -- init --new-database pos1052 --demo -m stock,point_of_sale,procurement,mail,bus,barcodes,web_kanban,account,pos_disable_payment,report,base_setup,stock_account,base,decimal_precision,analytic,pos_longpolling,web,web_tour,product,web_planner,pos_multi_session,pos_multi_session_sync,pos_restaurant
```

Тесты запускал с этой:
```
docker-compose run odoo -d pos1052 --test-enable --stop-after-init -i pos_multi_session,pos_multi_session_sync,pos_restaurant
```

2. Тесты в самом тревисе провалились https://github.com/it-projects-llc/pos-addons/pull/1052/checks?check_run_id=204255514
Полагаю надо подтянуть изменения, которые за это время появились

2019-08-29 08:15 UTC, kaadevelop reviewed
None

**3 installable** modules are updated:
```
├─ pos_multi_session/
|  ├─ README.rst
|  ├─ __manifest__.py
|  ├─ doc/
|  |  └─ changelog.rst
|  ├─ static/
|  |  └─ src/
|  |     └─ js/
|  |        └─ pos_multi_session.js
|  └─ tests/
|     └─ test_pos.py
├─ pos_multi_session_restaurant/
|  ├─ static/
|  |  └─ src/
|  |     └─ js/
|  |        └─ pos_multi_session_restaurant.js
|  └─ tests/
|     └─ test_pos_ms_r.py
└─ pos_multi_session_sync/
   ├─ __manifest__.py
   ├─ doc/
   |  └─ changelog.rst
   └─ models/
      └─ pos_multi_session_sync_models.py
```

Not installable modules remain unchanged.
```
```

> sent by [:v: Review Bot](https://odoo-devops.readthedocs.io/en/latest/git/github-review-bot.html)

2019-08-29 08:15 UTC, kaadevelop commented on pos_multi_session/doc/changelog.rst
> +
Has to be tested

2019-08-29 08:15 UTC, kaadevelop commented on pos_multi_session_sync/doc/changelog.rst
> +
Has to be tested

2019-09-09 10:26 UTC, em230418 approved these changes

2019-09-09 11:25 UTC, merged