deleted unused variables in *.js
itpp-labs/pos-addons pull request #1054
Opened 2019-07-19 09:14 UTC by fedoranvar

2019-07-22 08:17 UTC, KolushovAlexandr requested changes
@fedoranvar I see much more lines that could be deleted. Also, do not forget about commit message rules
https://gitlab.com/itpp/handbook/blob/master/documenting-updates.md

2019-07-23 18:10 UTC, KolushovAlexandr requested changes
* Fix indents everywhere
* Wrong commit tag
* Update versions and changelog
* Split commit to two ones with appropriate tags and commit messages
* tags :one::zero: are not needed here

2019-07-24 10:13 UTC, KolushovAlexandr requested changes

2019-07-24 10:13 UTC, KolushovAlexandr commented on pos_invoice_postponed/doc/changelog.rst
> +- **Fix** Deleted unused variables
that's not a FIX it's refactoring. Here it might be missed

2019-07-24 10:13 UTC, KolushovAlexandr commented on pos_journal_pin/doc/changelog.rst
> +- **Fix** Deleted unused variables
that's not a FIX it's refactoring. Here it might be missed

2019-07-24 10:13 UTC, KolushovAlexandr commented on pos_journal_pin/doc/changelog.rst
> +- **Fix** Numpad-click-event in case of empty payment lines
better explain the reason and consequences by the user point of view

2019-07-24 10:13 UTC, KolushovAlexandr commented on pos_journal_pin/static/src/js/main.js
> +          	if (paymentlines.length || !this.pos.cashregisters[0].journal.ask_manager) {
indents are still wrong

2019-07-25 09:02 UTC, KolushovAlexandr requested changes

2019-07-25 09:02 UTC, KolushovAlexandr commented on pos_journal_pin/doc/changelog.rst
> +- **Fix** When payment lines are empty and numpad-button clicked - it request PIN to add payment line, if first payment method in list is PIN (USD)
Adding a paymentline without asking managers PIN on the Payment Screen could be provoked by clicking on a numpad button

2019-07-25 09:02 UTC, KolushovAlexandr commented on pos_invoice_postponed/static/src/js/main.js
> +    Copyright 2019 Kildebekoov Anvar <https://it-projects.info/team/kildebekov>
make it stylistically  same with side lines

2019-07-25 09:33 UTC, fedoranvar commented on pos_journal_pin/doc/changelog.rst
> +- **Fix** When payment lines are empty and numpad-button clicked - it request PIN to add payment line, if first payment method in list is PIN (USD)
get it: how the style of writing should be

2019-07-25 12:06 UTC, KolushovAlexandr approved these changes

2019-08-14 09:36 UTC, KolushovAlexandr requested changes
it would be better to make separate PR for the test commit

2019-08-14 09:36 UTC, KolushovAlexandr commented on pos_menu/static/src/js/tour.js
> +                $('.product-list .product-name:contains(' + menu[i] + ')').click();
It does not throw an error if there are no such items. Also, I don't see where the POS selecting happens, so independently on the POS and it's menu it won't throw an error.

2019-08-16 05:42 UTC, closed without merging