:arrow_ip::one::one:,
itpp-labs/pos-addons pull request #1056
Opened 2019-07-22 07:33 UTC by fedoranvar

In models.py added variable 'invoice_flag';
Deleted unused variables;
Edited commentaries in files (i.e. changed version from 10 to 11, added contributors etc.);

2019-08-23 07:30 UTC, KolushovAlexandr approved these changes

2019-08-23 12:29 UTC, Ramil-Mukhametzyanov reviewed
/static/description/index.html contains a reference to Odoo 10.0

2019-08-23 12:40 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-26 07:27 UTC, kaadevelop reviewed
No new features need to be tested.

2019-08-26 11:33 UTC, em230418 requested changes
Исправить мелочь

2019-08-26 11:33 UTC, em230418 commented on pos_invoice_postponed/README.rst
> +Tested on Odoo 11.0 06569efca35ef1eee119a1f9c3f73cf79fb70718
Нет такого коммита. https://github.com/odoo/odoo/commit/06569efca35ef1eee119a1f9c3f73cf79fb70718

2019-08-26 11:52 UTC, kaadevelop reviewed
1 modules is updated:

 Updated files in 1 installable modules:
```
└─ pos_invoice_postponed/
   ├─ README.rst
   ├─ __manifest__.py
   ├─ models/
   |  └─ models.py
   ├─ static/
   |  ├─ description/
   |  |  └─ index.html
   |  └─ src/
   |     └─ js/
   |        └─ main.js
   └─ tests/
      └─ test_default.py
```

 Updated files in 0 non-installable modules:
are absent

You can use this review-bot too. Look: https://odoo-devops.readthedocs.io/en/latest/

No new features to test

2019-08-26 11:53 UTC, fedoranvar commented on pos_invoice_postponed/README.rst
> +Tested on Odoo 11.0 06569efca35ef1eee119a1f9c3f73cf79fb70718
исправил

2019-08-26 12:04 UTC, em230418 approved these changes

2019-08-26 12:35 UTC, merged