:rainbow:, pos_logout
itpp-labs/pos-addons pull request #1058
Opened 2019-07-25 06:23 UTC by fedoranvar

Handled tour of module functionality;

2019-07-25 08:48 UTC, KolushovAlexandr requested changes

2019-07-25 08:48 UTC, KolushovAlexandr commented on pos_logout/README.rst
> +* `Kildebekov Anvar <https://it-projects.info/team/kildebekov>`__
add me here too please

2019-07-25 08:49 UTC, KolushovAlexandr commented
Travis says there are wrong version numbers in readme
Add licences for test files

2019-07-25 09:00 UTC, fedoranvar commented
> Travis says there are wrong version numbers in readme
> Add licences for test files

2019-07-25 10:11 UTC, KolushovAlexandr requested changes

2019-07-25 10:11 UTC, KolushovAlexandr commented on pos_logout/doc/changelog.rst
> +- **Fix:** Handled tour: testing functional of pos_logout module by test user (created in python-part of test)
there is no need to change the version.
look through this 
https://gitlab.com/itpp/handbook/blob/master/documenting-updates.md
and this when and why we change the version 
https://odoo-development.readthedocs.io/en/latest/dev/docs/changelog.rst.html

2019-07-25 10:15 UTC, KolushovAlexandr commented on pos_logout/doc/changelog.rst
> +- **Fix:** Handled tour: testing functional of pos_logout module by test user (created in python-part of test)
the first link is about incorrect commit tag
it should be shield :shield:

2019-07-25 12:04 UTC, KolushovAlexandr approved these changes

2019-07-30 05:57 UTC, Ramil-Mukhametzyanov approved these changes

2019-07-30 08:57 UTC, em230418 commented on pos_logout/tests/test_default.py
>          # this you end up with js, css but no qweb.
Given link: https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/tests/test_frontend.py#L292-L297
is not correct, you need to use permalink with commit hash
https://github.com/odoo/odoo/blob/48dafd5b2011cee966920f664a904de2e2715ae8/addons/point_of_sale/tests/test_frontend.py#L306-L310

2019-08-09 09:33 UTC, em230418 commented
I approve to merge it now

2019-08-09 09:33 UTC, merged