:arrow_up::one::two:, pos_keyboard:
itpp-labs/pos-addons pull request #1059
Opened 2019-07-25 07:29 UTC by fedoranvar

Refactoring

2019-07-25 08:11 UTC, KolushovAlexandr requested changes

2019-07-25 08:11 UTC, KolushovAlexandr commented on pos_keyboard/__manifest__.py
> +    "version": "12.0.1.0.0",
do not change the version when porting, especially downgrading

2019-07-25 08:11 UTC, KolushovAlexandr commented on pos_keyboard/doc/changelog.rst
> +`1.0.0`
revert those changes

2019-07-25 08:11 UTC, KolushovAlexandr commented on pos_keyboard/README.rst
> +Tested on Odoo 12.0 34369ff58121b33387aada0929e34efe783c3baf
change all references to 11.0v here and probably in index.rst

2019-07-25 08:41 UTC, fedoranvar commented on pos_keyboard/__manifest__.py
> +    "version": "12.0.1.0.0",
why porting from 11 to 12 - is downgrading?

2019-07-25 08:41 UTC, fedoranvar commented on pos_keyboard/__manifest__.py
> +    "version": "12.0.1.0.0",
> do not change the version when porting, especially downgrading

why porting from 11 to 12 - is downgrading?

2019-07-25 08:42 UTC, fedoranvar commented on pos_keyboard/README.rst
> +Tested on Odoo 12.0 34369ff58121b33387aada0929e34efe783c3baf
> change all references to 11.0v here and probably in index.rst

why?

2019-07-25 08:43 UTC, KolushovAlexandr commented on pos_keyboard/__manifest__.py
> +    "version": "12.0.1.0.0",
you downgraded modules version 1.1.3 to 1.0.0

2019-07-25 08:50 UTC, KolushovAlexandr commented on pos_keyboard/README.rst
> +Tested on Odoo 12.0 34369ff58121b33387aada0929e34efe783c3baf
sorry, meant to 12.0

2019-07-25 08:51 UTC, KolushovAlexandr commented on pos_keyboard/README.rst
> +Tested on Odoo 12.0 34369ff58121b33387aada0929e34efe783c3baf
but anyway you understood me :+1:

2019-07-25 10:08 UTC, fedoranvar commented on pos_keyboard/__manifest__.py
> +    "version": "12.0.1.0.0",
Resolved

2019-07-25 12:03 UTC, KolushovAlexandr requested changes
@fedoranvar When I click number keys in the password popup they are added doubled

2019-07-25 13:28 UTC, KolushovAlexandr approved these changes

2019-08-12 07:19 UTC, Ramil-Mukhametzyanov reviewed
There is reference to Odoo 10.0 in the static/description/index.html file.

2019-08-12 07:56 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/static/description/index.html
> +                    Tested on Odoo<br/>11.0 community
@fedoranvar  Porting to Odoo 12.0

2019-08-12 08:04 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-14 09:41 UTC, KolushovAlexandr approved these changes

2019-08-15 07:15 UTC, em230418 requested changes
Scenario:
- login as demo
- Point of Sale -> New session
- Click on any item in shop
- Click on "Payment"
- Typing in usual keyboard, for example 987, nothing appears. Expecting something to be appeared.
- Clicking on any button in virtual keyboard. For example 1. Finally something appears with previous "987".

2019-08-16 08:23 UTC, fedoranvar commented
> Scenario:
> 
> * login as demo
> * Point of Sale -> New session
> * Click on any item in shop
> * Click on "Payment"
> * Typing in usual keyboard, for example 987, nothing appears. Expecting something to be appeared.
> * Clicking on any button in virtual keyboard. For example 1. Finally something appears with previous "987".

Эта проблема работы Оду, не работы этого модуля.
проверялось на ранботе оду.

2019-08-16 12:37 UTC, em230418 commented
Давай заодно и это с тестами: https://github.com/it-projects-llc/pos-addons/pull/1084/commits/b30d0a55dcd6dc5ec8745866aff4ac9c7ee53cd5

2019-08-23 06:14 UTC, em230418 approved these changes

2019-08-23 06:15 UTC, em230418 commented
I approve to merge it now

2019-08-23 06:15 UTC, merged

2019-10-18 14:28 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Incompatibility with some modules led to the action duplicating
:+1: checked