11.0 pos menu port
itpp-labs/pos-addons pull request #1065
Opened 2019-07-30 07:58 UTC by fedoranvar

2019-07-30 10:38 UTC, Ramil-Mukhametzyanov requested changes
There is no Available Product Sets option in POS settings.

2019-08-01 13:48 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-07 10:06 UTC, em230418 requested changes
Everything works fine. Nonessential changes required in README.rst

2019-08-07 10:06 UTC, em230418 commented on pos_menu/README.rst
> +Tested on Odoo 11.0 0351677a00df8bd76fa207a38dc2ecdefdc6940a
This commit is from 12.0 branch
https://github.com/odoo/odoo/commit/0351677a00df8bd76fa207a38dc2ecdefdc6940a

2019-08-07 10:06 UTC, em230418 commented on pos_menu/README.rst
> +* `Gabbasov Dinar <https://it-projects.info/team/GabbasovDinar>`_
We don't need to change two underscores to one

2019-08-07 10:23 UTC, fedoranvar commented on pos_menu/README.rst
> +Tested on Odoo 11.0 0351677a00df8bd76fa207a38dc2ecdefdc6940a
changed commit

2019-08-07 10:25 UTC, fedoranvar commented on pos_menu/README.rst
> +* `Gabbasov Dinar <https://it-projects.info/team/GabbasovDinar>`_
checked

2019-08-07 10:28 UTC, em230418 commented on pos_menu/README.rst
> +Tested on Odoo 11.0 e99c6ea835c119b478c853f7b6af511afe453c47
Commit does not exist: https://github.com/odoo/odoo/commit/e99c6ea835c119b478c853f7b6af511afe453c47

2019-08-08 07:36 UTC, fedoranvar commented on pos_menu/README.rst
> +Tested on Odoo 11.0 e99c6ea835c119b478c853f7b6af511afe453c47
how to insert id of commit? 

I'm doing 'git log -1'
putting in readme
git add . && git commit --amend

Am I right?

2019-08-08 07:57 UTC, em230418 commented on pos_menu/README.rst
> +Tested on Odoo 11.0 e99c6ea835c119b478c853f7b6af511afe453c47
Don't know. I do like this:

https://github.com/odoo/odoo/tree/11.0
Ctrl+F "Latest commit"
Copy hyperlink to the right
You will get
https://github.com/odoo/odoo/commit/<COMMIT_ID>

2019-08-08 08:10 UTC, fedoranvar commented on pos_menu/README.rst
> +Tested on Odoo 11.0 e99c6ea835c119b478c853f7b6af511afe453c47
oh, I think I get it 

So we paste commit-id of odoo, not the module

2019-08-08 12:34 UTC, GabbasovDinar commented on pos_menu/README.rst
> +Tested on Odoo 11.0 e99c6ea835c119b478c853f7b6af511afe453c47
git rev-parse HEAD

2019-08-09 06:55 UTC, em230418 approved these changes

2019-08-09 07:47 UTC, yelizariev commented
I approve to merge it now

2019-08-09 07:47 UTC, merged