11.0 pos multisession_menu port
itpp-labs/pos-addons pull request #1077
Opened 2019-08-09 09:30 UTC by fedoranvar

2019-08-09 09:40 UTC, yelizariev approved these changes
No code was changed

2019-08-09 10:20 UTC, Ramil-Mukhametzyanov reviewed
In index.rst file: "Tested  on Odoo 10.0 community". Please change to actual version and comment enterprise.

2019-08-09 10:32 UTC, fedoranvar commented
> In index.rst file: "Tested on Odoo 10.0 community". Please change to actual version and comment enterprise.

check again, please

2019-08-09 10:45 UTC, Ramil-Mukhametzyanov commented
> > In index.rst file: "Tested on Odoo 10.0 community". Please change to actual version and comment enterprise.
> 
> check again, please
Sorry, in index.html

2019-08-09 10:54 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-09 11:00 UTC, Ramil-Mukhametzyanov reviewed
@fedoranvar Please add the module name to the PR title.

2019-08-14 09:21 UTC, KolushovAlexandr approved these changes

2019-08-15 09:39 UTC, em230418 requested changes
Only commit hash change required.

2019-08-15 09:39 UTC, em230418 commented on pos_multi_session_menu/README.rst
> +Tested on Odoo 11.0 dff2e242a5e5288cb3c8408a9b635a4c85034e83
Looks like it is from 12.0 branch
https://github.com/odoo/odoo/commit/dff2e242a5e5288cb3c8408a9b635a4c85034e83

2019-08-16 07:01 UTC, em230418 approved these changes

2019-08-16 07:04 UTC, merged