:ambulance: Added event handler for numpad-click;
itpp-labs/pos-addons pull request #1082
Opened 2019-08-15 10:31 UTC by fedoranvar

2019-08-15 14:34 UTC, KolushovAlexandr approved these changes

2019-08-20 07:42 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-23 09:58 UTC, em230418 requested changes
Демо юзер не может создать сессию.

Вроде можно, не? Та-же функция, где мы делаем sudo, вызывает другую функцию которая пытается создать объект ir.sequence без sudo.

Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:
- Administration/Settings

(Document model: ir.sequence) - (Operation: create, User: 5)

2019-08-26 13:17 UTC, kaadevelop reviewed
1 modules is updated:

 Updated files in 1 installable modules:
```
└─ pos_journal_pin/
   ├─ README.rst
   ├─ __manifest__.py
   ├─ doc/
   |  ├─ changelog.rst
   |  └─ index.rst
   ├─ models/
   |  └─ models.py
   └─ static/
      └─ src/
         └─ js/
            └─ main.js
```

 Updated files in 0 non-installable modules:
are absent

You can use this review-bot too. Look: https://odoo-devops.readthedocs.io/en/latest/

2019-08-26 13:17 UTC, kaadevelop commented on pos_journal_pin/doc/changelog.rst
> +
Has to be tested

2019-08-26 13:28 UTC, fedoranvar commented
> Демо юзер не может создать сессию.
> 
> Вроде можно, не? Та-же функция, где мы делаем sudo, вызывает другую функцию которая пытается создать объект ir.sequence без sudo.
> 
> Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:
> 
> * Administration/Settings
> 
> (Document model: ir.sequence) - (Operation: create, User: 5)

исправлено

2019-09-02 05:24 UTC, kaadevelop reviewed
**1 installable** module is updated:
```
└─ pos_journal_pin/
   ├─ README.rst
   ├─ __manifest__.py
   ├─ doc/
   |  ├─ changelog.rst
   |  └─ index.rst
   ├─ models/
   |  └─ models.py
   ├─ static/
   |  └─ src/
   |     └─ js/
   |        └─ main.js
   └─ tests/
      └─ test_journal_pin.py
```

Not installable modules remain unchanged.
```
```

> sent by [:v: Review Bot](https://odoo-devops.readthedocs.io/en/latest/git/github-review-bot.html)

2019-09-02 05:24 UTC, kaadevelop commented on pos_journal_pin/doc/changelog.rst
> +
Has to be tested

2019-09-03 06:45 UTC, em230418 commented
Не проходят тесты и в тревисе и из под одуап.
[pos1082.log](https://github.com/it-projects-llc/pos-addons/files/3568095/pos1082.log)

2019-11-21 11:43 UTC, em230418 approved these changes

2019-11-21 11:43 UTC, merged