:ambulance: added sudo() in 'models.py' for non-administrators
itpp-labs/pos-addons pull request #1083
Opened 2019-08-15 10:58 UTC by fedoranvar

2019-08-15 14:33 UTC, KolushovAlexandr approved these changes

2019-08-20 07:50 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-20 09:22 UTC, em230418 requested changes
Предполагаю, что после данного изменения тест, который `test_01_pos_postponed_invoice` должен проходить если поставить login=demo. Но тест обламывается после того, как нажали на New session.
![FireShot Capture 14 - Point of Sale - Odoo](https://user-images.githubusercontent.com/52414052/63334483-0bc54b00-c32b-11e9-95a9-7a23c9fda398.png)

Как я выяснил, обламывается **как минимум** на этом: https://github.com/it-projects-llc/pos-addons/blob/2366f46474bb739e065c24efcda47194a1c40817/pos_invoice_postponed/models/models.py#L132-L136

Полагаю там тоже можно использовать sudo, потому-что в официальном point_of_sale так и делается: https://github.com/odoo/odoo/blob/5c70cc24b3ce27ea28c19a53c1886720d56ca0d2/addons/point_of_sale/models/pos_config.py#L215-L224

Вообщем нужно, чтобы данный тест проходил и для admin и для demo.

2019-08-20 09:25 UTC, em230418 commented on pos_invoice_postponed/README.rst
> +Tested on Odoo 10.0 2fc46a064d36d9de2c6debf9582976f938e3568b
Коммит из 12-ой ветки https://github.com/odoo/odoo/commit/2fc46a064d36d9de2c6debf9582976f938e3568b

2019-08-26 12:03 UTC, em230418 approved these changes

2019-08-26 12:05 UTC, em230418 requested changes
По ошибке нажал на Approve

2019-08-26 12:19 UTC, fedoranvar commented on pos_invoice_postponed/README.rst
> +Tested on Odoo 10.0 2fc46a064d36d9de2c6debf9582976f938e3568b
исправил

2019-08-26 12:19 UTC, kaadevelop reviewed
1 modules is updated:

 Updated files in 1 installable modules:
```
└─ pos_invoice_postponed/
   ├─ README.rst
   ├─ __manifest__.py
   ├─ doc/
   |  └─ changelog.rst
   ├─ models/
   |  └─ models.py
   └─ static/
      └─ src/
         └─ js/
            └─ main.js
```

 Updated files in 0 non-installable modules:
are absent

You can use this review-bot too. Look: https://odoo-devops.readthedocs.io/en/latest/

2019-08-26 12:19 UTC, kaadevelop commented on pos_invoice_postponed/doc/changelog.rst
> +
Has to be tested

2019-08-29 11:13 UTC, kaadevelop reviewed
Installable modules remain unchanged.
```
```

**1 not installable** modules  is updated:
```
└─ pos_invoice_postponed/
   ├─ README.rst
   ├─ __manifest__.py
   ├─ doc/
   |  └─ changelog.rst
   ├─ models/
   |  └─ models.py
   ├─ static/
   |  └─ src/
   |     └─ js/
   |        └─ main.js
   └─ tests/
      └─ test_default.py
```

No new features in *doc/changelog.rst* files of installable modules

> sent by [:v: Review Bot](https://odoo-devops.readthedocs.io/en/latest/git/github-review-bot.html)

2019-08-29 11:28 UTC, fedoranvar commented
> Предполагаю, что после данного изменения тест, который `test_01_pos_postponed_invoice` должен проходить если поставить login=demo. Но тест обламывается после того, как нажали на New session.
> ![FireShot Capture 14 - Point of Sale - Odoo](https://user-images.githubusercontent.com/52414052/63334483-0bc54b00-c32b-11e9-95a9-7a23c9fda398.png)
> 
> Как я выяснил, обламывается **как минимум** на этом:
> 
> https://github.com/it-projects-llc/pos-addons/blob/2366f46474bb739e065c24efcda47194a1c40817/pos_invoice_postponed/models/models.py#L132-L136
> 
> Полагаю там тоже можно использовать sudo, потому-что в официальном point_of_sale так и делается: https://github.com/odoo/odoo/blob/5c70cc24b3ce27ea28c19a53c1886720d56ca0d2/addons/point_of_sale/models/pos_config.py#L215-L224
> 
> Вообщем нужно, чтобы данный тест проходил и для admin и для demo.

Проверил этот коммит на ранботе.

ФантомДЖС из под демо отрабатывает нормально

2019-09-02 10:17 UTC, em230418 requested changes
Tour для demo проваливается. Походу кнопочки postponed не появляется у него.

2019-11-13 13:32 UTC, closed without merging