:ambulance: Function 'disconnect' not working in expected way
itpp-labs/pos-addons pull request #1084
Opened 2019-08-15 11:33 UTC by fedoranvar

2019-08-16 08:40 UTC, KolushovAlexandr approved these changes

2019-08-16 11:07 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-16 12:34 UTC, em230418 requested changes
Напиши тест-кейс, который решает это исправление.
Можно отдельным коммитом.

2019-08-19 12:34 UTC, em230418 requested changes
Эти тесты тоже надо проходить

https://travis-ci.com/it-projects-llc/pos-addons/jobs/226270700
https://travis-ci.com/it-projects-llc/pos-addons/jobs/226270702

2019-08-22 09:50 UTC, em230418 requested changes

2019-08-22 09:50 UTC, em230418 commented on pos_keyboard/static/src/js/test_pos_keyboard.js
> +            trigger: '.modal-dialog.cashier .selection-item:contains("Mitchell Admin")',
Предлагаю поменять на "Admin", потому-что скушает "Mitchell Admin" и скушает это: 
![FireShot Capture 17 - Odoo POS](https://user-images.githubusercontent.com/52414052/63504975-33025080-c4c2-11e9-9b90-dda67306af30.png)

2019-08-22 10:56 UTC, em230418 approved these changes

2019-08-23 06:16 UTC, em230418 commented
Merged https://github.com/it-projects-llc/pos-addons/commit/78dcfa2591504685fa7e34f3bd77f60266c9d059

2019-08-23 06:17 UTC, closed without merging