:shield: pos_menu: updated tests
itpp-labs/pos-addons pull request #1085
Opened 2019-08-15 13:07 UTC by fedoranvar

2019-08-19 08:01 UTC, KolushovAlexandr requested changes

2019-08-19 08:01 UTC, KolushovAlexandr commented on pos_menu/static/src/js/tour.js
> +      function pos_closing(){
not necessary, it does not check anything related to the module's functionality. Just takes time

2019-08-19 09:33 UTC, KolushovAlexandr approved these changes

2019-08-20 07:05 UTC, Ramil-Mukhametzyanov approved these changes

2019-09-02 06:52 UTC, kaadevelop reviewed
**1 installable** module is updated:
```
└─ pos_menu/
   ├─ static/
   |  └─ src/
   |     └─ js/
   |        └─ tour.js
   └─ tests/
      ├─ __init__.py
      └─ test_default.py
```

Not installable modules remain unchanged.
```
```

No new features in *doc/changelog.rst* files of installable modules

> sent by [:v: Review Bot](https://odoo-devops.readthedocs.io/en/latest/git/github-review-bot.html)

2019-09-02 06:56 UTC, em230418 commented
Оказывается odoo не принимает тесты, если имя модуля, в котором тест объявлен, не начинается на "test_". [Доказательство](https://github.com/odoo/odoo/blob/00e169c05a270a0943a74fbeb0a884009946c7cd/odoo/modules/module.py#L442-L443). Поскольку сам выяснил, сам же закоммитил.

Приму после проверки тревиса.

2019-09-02 11:46 UTC, em230418 commented
I approve to merge it now

2019-09-02 11:46 UTC, merged