12.0 pos mobile fix clientlist
itpp-labs/pos-addons pull request #1087
Opened 2019-08-21 09:13 UTC by em230418

Reason is that `$('.pos.mobile .window').css({display: 'table'})` from `change_screen_type` was not setting style for all elements in selector due to some bug in jquery 1.11.1. But somehow
`$('.pos.mobile .window').css({display: 'none'})` is working correct, so it works correctly without this css rule.

2019-08-21 10:04 UTC, Ramil-Mukhametzyanov requested changes
There is no vertical scrolling in the customer list screen.

2019-08-21 13:31 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-22 06:52 UTC, yelizariev approved these changes

2019-08-22 07:02 UTC, em230418 commented
I approve to merge it now

2019-08-22 07:02 UTC, merged