12.0 pos multi session port fixes from 10
itpp-labs/pos-addons pull request #1095
Opened 2019-09-10 09:30 UTC by em230418

Ported this using cherry-pick. https://github.com/it-projects-llc/pos-addons/pull/1052

2019-09-10 12:26 UTC, KolushovAlexandr requested changes
Tour pos_order_cancel_tour failed at step .tables .table

```
************* Module pos_multi_session
Odoo version in link https://www.odoo.com/apps/modules/10.0/pos_multi_session/ is not valid
pos_multi_session/__init__.py:1: [E7989(readme-versions), ] Wrong version in module's README.rst
```

2019-09-11 08:24 UTC, Ramil-Mukhametzyanov requested changes
Even if a floor plan is set in a multi-session configuration, there is not floor plan on the POS.

2019-09-12 12:27 UTC, KolushovAlexandr requested changes
Odoo version in link http://runbot.it-projects.info/demo/pos-addons/10.0 is not valid
pos_order_cancel_restaurant/__init__.py:1: [E7989(readme-versions), ] Wrong version in module's README.rst

2019-09-12 12:27 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +    var Model = require('web.Model');
it is obsolete since odoo 11.0. rpc is used now

2019-09-26 07:46 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/doc/changelog.rst
> +
:+1: checked

2019-09-26 08:06 UTC, Ramil-Mukhametzyanov approved these changes

2019-09-26 08:06 UTC, KolushovAlexandr approved these changes
I approve code changes

2019-09-26 12:40 UTC, em230418 commented
I approve to merge it now

2019-09-26 12:40 UTC, merged