:ambulance: Unavailability to return fractional product amount
itpp-labs/pos-addons pull request #1100
Opened 2019-09-16 10:47 UTC by KolushovAlexandr

2019-09-16 12:20 UTC, Ramil-Mukhametzyanov requested changes
Sometimes fractional values appear, such as 4.440892098500626e-16
![image](https://user-images.githubusercontent.com/33877236/64957144-b175c680-d8a5-11e9-84dd-0f0413d9d369.png)

2019-09-17 14:23 UTC, Ramil-Mukhametzyanov requested changes
It is possible to return more than purchased.
![image](https://user-images.githubusercontent.com/33877236/65050166-62e92a80-d980-11e9-8b8e-45cf6b55efbe.png)

2019-09-18 10:18 UTC, Ramil-Mukhametzyanov approved these changes

2019-09-18 10:22 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Unavailability to return fractional product amount
:+1: checked

2019-09-25 12:43 UTC, yelizariev requested changes

2019-09-25 12:43 UTC, yelizariev commented on pos_orders_history_return/static/src/js/models.js
> +            el.html(Math.round((product.max_return_qty - qty) * 1000) / 1000);
use odoo tools instead: round_decimals, round_precision

2019-09-25 12:53 UTC, em230418 requested changes
Тест с этим модулем автоматически не запускаются, т.к. в неподходящее имя файла в котором определен тест - default_test.py. Название модуля должна начинаться с test_

Пруфлинк: https://github.com/odoo/odoo/blob/a22419e45124aa578785853efdb98db79c9ae65c/doc/reference/testing.rst#testing-python-code

2019-09-25 12:55 UTC, KolushovAlexandr commented on pos_orders_history_return/static/src/js/models.js
> +            el.html(Math.round((product.max_return_qty - qty) * 1000) / 1000);
I especially changed them to Math round due to they do not round properly
https://github.com/it-projects-llc/pos-addons/compare/0c216a8129fcef17f32319e567026a49a2cafe3e..dce6bf77ebb57014c65723ae01d3412efa8a71a7
Previous Ramils reviews were fixed by not using them

2019-09-25 13:00 UTC, em230418 commented
Сам tour обламывается на `.control-button.orders-history`

2019-10-11 15:58 UTC, yelizariev commented on pos_orders_history_return/static/src/js/models.js
> +            el.html(Math.round((product.max_return_qty - qty) * 1000) / 1000);
You can use proper number, instead of variable this.pos.currency.rounding

2019-10-14 12:18 UTC, em230418 approved these changes

2019-10-15 11:37 UTC, yelizariev approved these changes

2019-10-15 12:59 UTC, merged