pos_debt_notebook - unit-tour-test
itpp-labs/pos-addons pull request #1101
Opened 2019-09-17 08:20 UTC by fedoranvar

2019-09-17 11:43 UTC, KolushovAlexandr requested changes
add error message checks for all functions **close_error_modal_dialog**
two scenarios are missed in the issue

1
* add not fruits and vegetables product to order
* try to pay with fruits and vegetables paymentmethod
* get error

2
process an order using only autopay button (the green one in the bottom left corner)

Don't forget to increase the timeout in python

Odoo version in link http://runbot.it-projects.info/demo/pos-addons/9.0 is not valid
pos_debt_notebook/__init__.py:1: [E7989(readme-versions), ] Wrong version in module's README.rst

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +    }
for better readability, I can suggest the next:
```
return steps.concat(
    func1(),
    func2(),
    ...
)
```

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +    // Error #1 from https://github.com/it-projects-llc/pos-addons/issues/592
:+1:

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +    // Error #1 from https://github.com/it-projects-llc/pos-addons/issues/592
Add here and everywhere short descriptions like **Error: "You cannot use Debt payment. Select customer first."**
so you dont need to open the link

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        steps = steps.concat(close_error_modal_dialog());
make a check for the alert message inside the function

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        steps = steps.concat(set_customer('Agrolait'));
you dont need to select a customer if you deselect it later

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +    function return_from_paying_to_menu() {
return_from_paymentscreen_to_menu

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        steps = set_numpad_value(steps,"1000");
you need a value bigger than 1000

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        return steps;
make a check the balance has changed

2019-09-17 11:43 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        return steps;
make a check the balance has changed

2019-09-18 07:38 UTC, fedoranvar commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        steps = steps.concat(set_customer('Agrolait'));
It requires in test-scenario

We need to check that to pay by Credit, we need to define the customer
But we can't choose credit payment method without at first selecting the customer

2019-09-18 07:40 UTC, fedoranvar commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        steps = set_numpad_value(steps,"1000");
1000 was enough in tests
Well, what the heck, so 10 000 will be it

2019-09-18 11:09 UTC, closed without merging

2019-09-18 13:37 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        steps = steps.concat(set_customer('Agrolait'));
Ok :+1: