10.0 pos mobile patch
itpp-labs/pos-addons pull request #1110
Opened 2019-10-01 14:30 UTC by Ramil-Mukhametzyanov

2019-10-02 06:50 UTC, yelizariev requested changes

2019-10-02 06:50 UTC, yelizariev commented on pos_mobile/doc/index.rst
> +================
make it subsection of Installation seciton

2019-10-02 06:50 UTC, yelizariev commented on pos_mobile/doc/index.rst
> +[Violation] A non-passive event listener was added to a scroll lock event . Consider marking the event handler as 'passive' to make the page more responsive. See
If you want a new line in rendered page, you need ad extra new line

https://github.com/it-projects-llc/pos-addons/blob/ab527b9324dbabfcb9cd3560cf3d5392b5932f55/pos_mobile/doc/index.rst

2019-10-02 06:50 UTC, yelizariev commented on pos_mobile/doc/index.rst
> +https://github.com/odoo/odoo/commit/2f8bfb77d6f9f957448d6267e4037fabf5665a3c
It's a commit from PR, not the commit that landed to odoo. Correct link: https://github.com/odoo/odoo/commit/d458ec953b179596330091b3efe729868fb56ca2

2019-10-02 06:50 UTC, yelizariev commented on pos_mobile/doc/index.rst
> +The following commit removes fastclick from Odoo:
```suggestion
The following commit removes fastclick in Odoo 12.0:
```

2019-10-02 06:50 UTC, yelizariev commented on pos_mobile/doc/index.rst
> +To apply them you can use git commands or use patch file remove_fastclick.patch. The patch can be found at module source. Exact commands are as following:
```suggestion
To apply the update on earlier odoo version you can use git commands or use patch file remove_fastclick.patch. The patch can be found at module source. Exact commands are as following:
```

2019-10-02 11:36 UTC, yelizariev approved these changes

2019-10-14 13:07 UTC, ilmir-k approved these changes

2019-10-17 14:36 UTC, ilmir-k commented
I approve to merge it now

2019-10-17 14:36 UTC, merged

2019-11-06 07:27 UTC, Ramil-Mukhametzyanov reviewed
This is the patch in Odoo 10.0 https://github.com/it-projects-llc/pos-addons/issues/728