:ambulance: fixed double move lines
itpp-labs/pos-addons pull request #1120
Opened 2019-10-14 13:05 UTC by KolushovAlexandr

2019-10-14 13:40 UTC, Ramil-Mukhametzyanov commented on pos_debt_notebook/doc/changelog.rst
> +
:+1: checked

2019-10-14 13:41 UTC, Ramil-Mukhametzyanov approved these changes

2019-10-18 10:33 UTC, em230418 requested changes
Тесты на odooup обламываются.

Разворачивал проект так:
```
docker-compose run dodoo -- init --new-database pos1120 --demo -m web,uom,mail,web_tour,digest,web_editor,product,base,barcodes,decimal_precision,portal,stock_account,point_of_sale,bus,base_setup,http_routing,analytic,account,stock,pos_debt_notebook
```

Тесты запускал так:
```
docker-compose run odoo -d pos1120 --test-enable --stop-after-init -i pos_debt_notebook
```
[pos1120.log](https://github.com/it-projects-llc/pos-addons/files/3743445/pos1120.log)

2019-10-31 13:00 UTC, em230418 approved these changes

2019-10-31 13:00 UTC, merged