11.0 f31070c4c98055663bf83cdab4d75dbb8117a5f0 3
itpp-labs/pos-addons pull request #1126
Opened 2019-10-17 09:41 UTC by KolushovAlexandr

2019-10-18 14:30 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/changelog.rst
> +
:+1: checked

2019-10-18 14:40 UTC, Ramil-Mukhametzyanov commented on pos_cashier_select/doc/changelog.rst
> +
#976
@Ommo73 @em230418 @KolushovAlexandr 
How to test this?

2019-10-18 14:42 UTC, Ramil-Mukhametzyanov commented on pos_product_available_negative/doc/changelog.rst
> +- **Fix:** Cashier was changed after giving the authorization of the sale
#1040 
@ilmir-k @yelizariev @KolushovAlexandr 
How to test this?

2019-10-18 14:51 UTC, Ramil-Mukhametzyanov commented on pos_longpolling/doc/changelog.rst
> +
:-1: I can not find this field

2019-10-18 14:54 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_restaurant/doc/changelog.rst
> +
:-1: checked

2019-10-18 14:59 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_sync/doc/changelog.rst
> +
:+1: checked

2019-10-18 15:06 UTC, KolushovAlexandr commented on pos_product_available_negative/doc/changelog.rst
> +- **Fix:** Cashier was changed after giving the authorization of the sale
When, for example, Demo is asking for permission to smth, and pos manager gives the permission, then the cashier was changed. But it shouldn't. That's the fix. So, change cashier to rightless demo, try to sell a product with negative quantity and when permission is given check that the cashier has not been changed from Demo to manager

2019-10-18 15:08 UTC, KolushovAlexandr commented on pos_longpolling/doc/changelog.rst
> +
Yep it's hidden, should be :+1:  I think

2019-10-18 15:09 UTC, ilmir-k commented on pos_product_available_negative/doc/changelog.rst
> +- **Fix:** Cashier was changed after giving the authorization of the sale
Once a user who has authorization to confirm the order payment, click on  ``Confirm``, the cashier gets replaced by this authorized user

2019-10-20 13:21 UTC, Ommo73 commented on pos_cashier_select/doc/changelog.rst
> +
@Ramil-Mukhametzyanov before this update, when installing both modules, they did not work properly and caused an error. So after that they just work properly.

2019-10-21 10:13 UTC, yelizariev commented on pos_multi_session_restaurant/doc/changelog.rst
> +
What is the problem? Do do you mean, that something has to be fixed?

2019-10-21 14:40 UTC, KolushovAlexandr commented on pos_cashier_select/doc/changelog.rst
> +
I think he meant scanning barcodes in a POS

2019-10-22 12:27 UTC, Ramil-Mukhametzyanov commented on pos_product_available_negative/doc/changelog.rst
> +- **Fix:** Cashier was changed after giving the authorization of the sale
:+1: checked

2019-10-22 12:37 UTC, Ramil-Mukhametzyanov commented on pos_longpolling/doc/changelog.rst
> +
:+1: checked, fixed

2019-10-22 12:58 UTC, Ramil-Mukhametzyanov commented on pos_invoice_pay/doc/changelog.rst
> +`1.2.2`
:+1: checked

2019-10-22 14:52 UTC, Ramil-Mukhametzyanov approved these changes

2019-10-22 14:54 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_restaurant/doc/changelog.rst
> +
:+1: Not the merge error

2019-10-25 06:31 UTC, em230418 requested changes
Сценарий tour_pos_invoice_pay не проходит, если через одуап запускать.
После Validate появляется вот это.
http://i.imgur.com/1lx3pmN.png

Для разворачивания выполнил это:
```
docker-compose run dodoo -- init --new-database pos1126 --demo -m account_invoicing,http_routing,account,sales_team,base_automation,mail,barcodes,base_setup,sale_management,pos_qr_scan,web_planner,stock,web_editor,point_of_sale,pos_restaurant,pos_disable_payment,analytic,pos_restaurant_base,resource,stock_account,pos_product_available,wechat,base,portal,web_tour,bus,pos_longpolling,product,web,pos_qr_payments,sale,pos_multi_session,qr_payments,pos_qr_show,decimal_precision,pos_pin,pos_cashier_select,pos_disable_payment_restaurant,pos_invoice_pay,pos_keyboard,pos_multi_session_restaurant,pos_multi_session_sync,pos_order_print_check,pos_partner_deselection,pos_product_available_negative,pos_product_lot,pos_scan_ref,pos_wechat
```

Для запуска тестов выполнил это:
```
docker-compose run dodoo -- init --new-database pos1126 --demo -m account_invoicing,http_routing,account,sales_team,base_automation,mail,barcodes,base_setup,sale_management,pos_qr_scan,web_planner,stock,web_editor,point_of_sale,pos_restaurant,pos_disable_payment,analytic,pos_restaurant_base,resource,stock_account,pos_product_available,wechat,base,portal,web_tour,bus,pos_longpolling,product,web,pos_qr_payments,sale,pos_multi_session,qr_payments,pos_qr_show,decimal_precision,pos_pin,pos_cashier_select,pos_disable_payment_restaurant,pos_invoice_pay,pos_keyboard,pos_multi_session_restaurant,pos_multi_session_sync,pos_order_print_check,pos_partner_deselection,pos_product_available_negative,pos_product_lot,pos_scan_ref,pos_wechat
```

Логи:
[pos1126.log](https://github.com/it-projects-llc/pos-addons/files/3770680/pos1126.log)

2019-10-29 13:00 UTC, em230418 commented
Линты надо пропавить. Все остальное - ок.

2019-10-30 07:17 UTC, em230418 commented on pos_invoice_pay/tests/test_pos_invoice.py
> +                self.super()
Там нету такого метода. Предлагается просто сделать так:
```def create(self, param):  # pylint: disable=no-member```

2019-11-01 06:25 UTC, em230418 approved these changes

2019-11-01 06:29 UTC, em230418 commented
I approve to merge it now

2019-11-01 06:29 UTC, merged