:ambulance: non rounded qty values
itpp-labs/pos-addons pull request #1136
Opened 2019-10-22 15:09 UTC by KolushovAlexandr

2019-10-23 05:44 UTC, Ramil-Mukhametzyanov commented on pos_product_available/doc/changelog.rst
> +- **Fix:** Non rounded long values of quantities
:+1: checked

2019-10-23 05:45 UTC, Ramil-Mukhametzyanov approved these changes

2019-10-25 07:15 UTC, em230418 requested changes
Тесты обламываются на
```
extra_trigger: '.product-list .product:contains("LED Lamp") .qty-tag.not-available:not(:contains("0"))'
```
ибо у него теперь всегда есть десятичные нули ("0.000"). Предлагаю эти десятичные нули резать.

Также предлагается перед выполнением сценария выставить количество LED Lamp, т.к. при повторном запуске через браузер (может быть и через odoo-bin --test-enabled), тот может менять количество до -1, -2, -3 и т.д.

2019-10-25 07:18 UTC, em230418 commented
Также надо поправить версию и коммит Odoo в reamde

2019-11-05 07:23 UTC, Ramil-Mukhametzyanov approved these changes

2019-11-14 09:45 UTC, em230418 commented
I approve to merge it now

2019-11-14 09:46 UTC, merged