:arrow_up::one::three: pos_keyboard
itpp-labs/pos-addons pull request #1148
Opened 2019-10-31 14:41 UTC by KolushovAlexandr

2019-11-08 07:49 UTC, Ramil-Mukhametzyanov requested changes
The module does not work as described in the description in the index.html:
1. the keys '/','*','s' do not work
2. the keys '-', '+' have different function

2019-11-08 09:10 UTC, KolushovAlexandr commented
@Ramil-Mukhametzyanov from 13v version odoo added functionality for: '-', '+' buttons, so i removed those functionality 
![Screenshot from 2019-11-08 14-00-49](https://user-images.githubusercontent.com/29929423/68463608-dac12c00-0230-11ea-8bcd-9fc1ac9b97c5.png)
but left functionality for q,d,p,s.
So the idea is not to break standard odoo functionality. We need to change description then. Or i'm open for any suggestions

2019-11-14 08:23 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/index.rst
> ++/-         ``s``
The 's' key does not work. Delete it from the description.

2019-11-14 08:24 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/index.rst
> +  * You can use ``s`` in case of +/-
Does not work

2019-11-15 06:28 UTC, em230418 requested changes

2019-11-15 06:28 UTC, em230418 commented on pos_keyboard/static/src/js/test_pos_keyboard.js
> +// I leave it here for the case when for some module posmodel.config.module_pos_hr is true
Предлагаю все-таки добавить проверку на случай, если `posmodel.config.module_pos_hr is true`. Коммент может быть и непрочитан.

В самих тестах из tests/* предлагаю сделать 2 случая, который будут выполнять этот tour. Когда posmodel.config.module_pos_hr false или когда true.

2019-11-15 06:28 UTC, em230418 commented on pos_keyboard/tests/test_pos_keyboard.py
>  class TestUi(odoo.tests.HttpCase):
https://www.odoo.com/documentation/13.0/reference/testing.html

odoo.tests.common.at_install(flag)
Deprecated since version 12.0

Предлагаю использовать `tagged('at_install', 'post_install')`

2019-11-15 06:28 UTC, em230418 commented on pos_keyboard/tests/test_pos_keyboard.py
> +
См выше коммент про
```
I leave it here for the case when for some module posmodel.config.module_pos_hr is true
```

2019-11-22 07:19 UTC, em230418 approved these changes
По коду предложений нет.

2019-11-22 07:24 UTC, em230418 commented
p, q, d не работают, если капс включен. Если так было в предыдущих версиях, то предлагаю исправить, как отдельное измнение не в рамках портирования.

2019-11-22 07:38 UTC, Ramil-Mukhametzyanov approved these changes

2019-11-22 13:16 UTC, ilmir-k commented
I approve to merge it now

2019-11-22 13:16 UTC, merged