:ambulance: Message for Orders with Invoiced Status. closes 1122
itpp-labs/pos-addons pull request #1158
Opened 2019-11-14 18:08 UTC by KolushovAlexandr

supersede #1143

2019-11-15 14:37 UTC, Ramil-Mukhametzyanov requested changes
Does not work

2019-11-16 11:43 UTC, ImplantiSolucoes commented
> Does not work

It's working, but only works using the order reference:
![Screenshot_3](https://user-images.githubusercontent.com/39229285/68992669-18374200-084d-11ea-8a9e-490d6e496d13.png)
![Screenshot_4](https://user-images.githubusercontent.com/39229285/68992665-179eab80-084d-11ea-90b8-3cca3c835489.png)
![Screenshot_5](https://user-images.githubusercontent.com/39229285/68992666-179eab80-084d-11ea-9d25-e2b60105675b.png)
![Screenshot_6](https://user-images.githubusercontent.com/39229285/68992667-179eab80-084d-11ea-9e96-ecaf979a99e6.png)
![Screenshot_7](https://user-images.githubusercontent.com/39229285/68992668-18374200-084d-11ea-9f43-4e24bf6a05c4.png)

2019-11-16 13:14 UTC, KolushovAlexandr commented
@ImplantiSolucoes Thanks for contributing! I made some changes so your pr satisfies our company rules

2019-11-16 14:41 UTC, ImplantiSolucoes commented
It was very good, I wanted to understand a little javascript like you

2019-11-18 08:38 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/doc/changelog.rst
> +**Improvement:** Show Invoiced Orders option
:+1: checked

2019-11-18 08:38 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_reprint/doc/changelog.rst
> +
:+1: checked

2019-11-18 08:38 UTC, Ramil-Mukhametzyanov approved these changes

2019-11-18 16:50 UTC, ImplantiSolucoes approved these changes
LGTM, tested

2019-11-19 06:57 UTC, em230418 requested changes
Тесты не запускаются автоматически. Такая-же история, как и в ветке постарше
https://github.com/it-projects-llc/pos-addons/pull/1100#pullrequestreview-293051886

2019-11-19 10:07 UTC, em230418 commented
Договорились на том, что тесты будем в рамках другой задачи

2019-11-19 10:07 UTC, em230418 approved these changes

2019-11-19 10:08 UTC, merged