13.0 pos order cancel port
itpp-labs/pos-addons pull request #1159
Opened 2019-11-15 14:54 UTC by KolushovAlexandr

2019-11-20 09:52 UTC, Ramil-Mukhametzyanov approved these changes

2019-11-21 09:53 UTC, em230418 commented on pos_order_cancel/__manifest__.py
> +# Copyright 2017-2019 Gabbasov Dinar <https://it-projects.info/team/GabbasovDinar>
Т.е. Динар удаленно помогал в чем-то?

2019-11-21 09:56 UTC, em230418 requested changes
Файл с тестами для pos_pin неправильно назван (должно начинаться на `test_`) и там вместо `odoo.tests.common.at_install`, `odoo.tests.common.post_install` должны быть `tagged`

2019-11-21 10:27 UTC, KolushovAlexandr commented on pos_order_cancel/__manifest__.py
> +# Copyright 2017-2019 Gabbasov Dinar <https://it-projects.info/team/GabbasovDinar>
https://github.com/it-projects-llc/pos-addons/pull/1159/commits/48fdca8f3d6e2001857f0bfc6a1e17014b609394#diff-319cd8716971b409fb2ac110e96036f5L1
It came out of here. But I do not find any confirmations for this

2019-11-22 06:34 UTC, em230418 approved these changes

2019-11-25 11:09 UTC, merged