13.0 pos longpolling port2
itpp-labs/pos-addons pull request #1170
Opened 2019-11-21 10:52 UTC by KolushovAlexandr

2019-12-04 06:14 UTC, Ramil-Mukhametzyanov requested changes
These options do not work
![image](https://user-images.githubusercontent.com/33877236/70116864-bd437e80-1685-11ea-8600-b7d2c5a95b69.png)

2019-12-06 09:27 UTC, KolushovAlexandr commented
@Ramil-Mukhametzyanov "Show Cancelled Orders" Option works and improvement to hide it when pos_order_cancell is not installed gonna come in 13v soon after merge wave from 11v. The second option should be fixed.

2019-12-06 14:50 UTC, Ramil-Mukhametzyanov approved these changes

2019-12-10 06:53 UTC, em230418 approved these changes

2019-12-11 12:19 UTC, em230418 commented
I approve to merge it now

2019-12-11 12:19 UTC, merged