pos_menu porting 11.0 - > 12.0
itpp-labs/pos-addons pull request #1180
Opened 2019-12-03 12:50 UTC by Enigma228322

2019-12-05 12:33 UTC, yelizariev commented
Сделай в одном комите всё

2019-12-05 12:34 UTC, yelizariev commented
Добавь свои копирайты со ссылкой на гитхаб

2019-12-05 12:37 UTC, Ramil-Mukhametzyanov approved these changes

2019-12-05 12:44 UTC, yelizariev requested changes

2019-12-05 12:44 UTC, yelizariev commented on pos_menu/demo/product_set_demo.xml
> +        </record>
Верни оригинальное выравнинвание. Не меняй отступы, если нет других изменений в той же строке

2019-12-05 12:44 UTC, yelizariev commented on pos_menu/static/src/js/tour.js
> +        content: _t("Ready to launch your <b>point of sale</b>? <i>Click here</i>."),
Почему шаг дублируется? В следующем шаге такое же сообщение

2019-12-05 12:45 UTC, yelizariev commented
Неверное описание комита

arrow_uponetwo bump versions in docs

2019-12-05 14:27 UTC, Enigma228322 commented on pos_menu/static/src/js/tour.js
> +        content: _t("Ready to launch your <b>point of sale</b>? <i>Click here</i>."),
fixed

2019-12-05 14:27 UTC, Enigma228322 commented on pos_menu/demo/product_set_demo.xml
> +        </record>
fixed

2019-12-06 11:42 UTC, yelizariev approved these changes

2020-06-09 19:52 UTC, trojikman commented
I approve to merge it now

2020-06-09 19:52 UTC, merged