porting product_lot 10.0 -> 11.0
itpp-labs/pos-addons pull request #1184
Opened 2019-12-10 11:59 UTC by Enigma228322

Signed-off-by: Vildan Safin <vildan.safin.99@gmail.com>

2019-12-19 15:09 UTC, Enigma228322 commented
@yelizariev @Ramil-Mukhametzyanov pr needs review

2019-12-23 12:22 UTC, KolushovAlexandr requested changes
qty on hand is not updated after `split lot` button clicked

2019-12-23 12:22 UTC, KolushovAlexandr commented on product_lot/doc/index.rst
> +Activate product ``Attributes and Variants``.
* wrong indent
* activate **product**??

2019-12-23 12:22 UTC, KolushovAlexandr commented on product_lot/views.xml
>  <openerp>
`<odoo>`

2019-12-23 12:22 UTC, KolushovAlexandr commented on product_lot/models.py
> +# Copyright 2019 Vildan Safin <https://it-projects.info/team/yelizariev>
sorting done wrong. From first to last ones

2019-12-28 10:39 UTC, KolushovAlexandr requested changes
* Qty on hand is updated after `splitting lot`.
* Forecasted qty is updated twice
For example, if we have 5 'computer case' in 'ice cream' (on hand and forecasted for both of them are 0) then after splitting the lot we have
*  -1 forecasted for 'ice cream'
* 5 on hand for 'computer case'
* 10 forecasted for 'computer case'

@ilmir-k I'm not sure about the first option Is it how it should be?

@Enigma228322 
forecasted should not be updated twice after `splitting`

2019-12-28 10:39 UTC, KolushovAlexandr commented on product_lot/views.xml
> +    <record id="product_lot_normal_form_view" model="ir.ui.view">
Keep commit history clean. Do not change what may not be changed. Leave indents for `<record>...` as they were

2020-06-08 22:47 UTC, closed without merging