12.0 merge
itpp-labs/pos-addons pull request #1185
Opened 2019-12-11 09:19 UTC by KolushovAlexandr

2019-12-17 09:36 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_reprint/doc/changelog.rst
> +- **Fix:** Downloading tickets even if the "Reprint" option is off
:+1:

2019-12-17 09:36 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_reprint/doc/changelog.rst
> +- **Fix:** "Reprint" button on the orders history list was shown when "Reprint" option was off
:+1:

2019-12-17 09:36 UTC, Ramil-Mukhametzyanov requested changes

2019-12-17 09:36 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_reprint/doc/changelog.rst
> +- **Fix:** Correcting "There is No Ticket for the Order" Message for Orders with Invoiced Status
Unable to pay invoice in POS. And can not close the POS by clicking the button in the upper right corner.

2019-12-17 10:16 UTC, Ramil-Mukhametzyanov approved these changes
It was a problem with the network.

2019-12-17 10:57 UTC, KolushovAlexandr commented
@Ramil-Mukhametzyanov I found out the reason for the problem
https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/models/account_invoice.py#L19
this line uses * _compute_average_price * it's the method added in the module `sale_stock`, but the latter module is not presented in the dependencies for `point_of_sale`. The error does not appear if the `sale_stock` module is installed

2019-12-18 08:04 UTC, em230418 commented on pos_qr_scan/doc/changelog.rst
> +
Работает.

2019-12-24 09:06 UTC, em230418 approved these changes

2020-01-13 06:54 UTC, em230418 commented
I approve to merge it now

2020-01-13 06:54 UTC, merged