11.0 implemted printing invoice lines in receipts
itpp-labs/pos-addons pull request #1186
Opened 2019-12-17 07:56 UTC by em230418

Fixes https://github.com/it-projects-llc/pos-addons/issues/1182

2019-12-17 08:25 UTC, Ramil-Mukhametzyanov approved these changes

2019-12-17 09:46 UTC, KolushovAlexandr requested changes
The receipt is not updated

2020-02-03 10:05 UTC, KolushovAlexandr approved these changes

2020-02-03 10:09 UTC, KolushovAlexandr commented
Eugene said orderlines are cut. Confirm. Then only style fixes are needed

2020-06-08 22:28 UTC, trojikman commented
@yelizariev I'll fix it in separate PR

2020-06-08 22:42 UTC, trojikman commented
![Screenshot from 2020-06-09 03-42-20](https://user-images.githubusercontent.com/23641186/84087328-42c43480-aa03-11ea-9403-fd264402f406.png)

2020-06-08 22:43 UTC, trojikman approved these changes

2020-06-09 04:53 UTC, yelizariev approved these changes

2020-06-09 04:53 UTC, yelizariev commented on pos_invoice_pay/doc/changelog.rst
> +**Fix:** Fixed "'bool' object has no attribute 'mapped'" error in get_sale_details
Описания фиксов слишком техническое. Надо пиать когда они происходят, а не в каких функциях

2020-06-09 06:22 UTC, em230418 commented
Нельзя принимать.При печати в POS-принтер там режутся строки на середине и я так и не исправил.

2020-06-09 06:28 UTC, em230418 commented
Задача описана тут: https://www.it-projects.info/web#id=2975&view_type=form&model=project.task

Там в комментариях см. обсуждения на 18-ое декабря 2019.

2024-10-17 06:41 UTC, closed without merging