:arrow_up::one::three: pos_product_available
itpp-labs/pos-addons pull request #1187
Opened 2019-12-18 09:21 UTC by KolushovAlexandr

2019-12-19 08:22 UTC, Ramil-Mukhametzyanov approved these changes

2019-12-20 11:03 UTC, em230418 commented on pos_product_available/static/src/js/pos.js
> +            prod_model = get_product_model(this.models);
Второй раз вычисляется prod_model

2019-12-20 11:03 UTC, em230418 commented on pos_product_available/static/src/js/test_pos_quantities.js
> +        // open_pos_neworder(),
Тесты вроде как и так работаеют, если не комментировать. Предлагаю вернуть.

2019-12-20 11:04 UTC, em230418 commented on pos_product_available/README.rst
> +Tested on Odoo 13.0 53dcdd5a9e22429a9638f68674264436ce21e42b
Заодно предлагаю хэш поправить

2019-12-25 09:45 UTC, KolushovAlexandr commented on pos_product_available/static/src/js/test_pos_quantities.js
> +        // open_pos_neworder(),
it tests nothing and spends time

2020-06-08 18:28 UTC, trojikman requested changes
По интерфейсу работает, но тесты падают

2020-06-09 05:55 UTC, yelizariev commented
В модуле сток проблема с установкой демо данных, поэтому демо данные отключились и тесты не работают. Смотри шаг  Install Additional Dependencies (Modules). 

Это должно помочь: https://github.com/itpp-labs/pos-addons/commit/02d1c6d6b6b7be4214ec0b7a74d0b32ea16d6fa7

2020-06-09 16:21 UTC, trojikman commented
> Это должно помочь: [02d1c6d](https://github.com/itpp-labs/pos-addons/commit/02d1c6d6b6b7be4214ec0b7a74d0b32ea16d6fa7)

Не помогает видимо

2020-06-09 16:49 UTC, trojikman commented
@yelizariev Всё проще оказывается)

2020-06-09 16:50 UTC, trojikman approved these changes

2020-06-10 12:11 UTC, trojikman commented
I approve to merge it now

2020-06-10 12:11 UTC, merged