Porting module pos_partner_deselection from v10 to v11
itpp-labs/pos-addons pull request #1193
Opened 2020-02-05 08:34 UTC by Enigma228322

Signed-off-by: Vildan Safin <safin@it-projects.info>

2020-02-05 09:41 UTC, Ramil-Mukhametzyanov requested changes
"installable": False

2020-02-05 10:24 UTC, Ramil-Mukhametzyanov requested changes

2020-02-05 10:24 UTC, Ramil-Mukhametzyanov commented on pos_partner_deselection/views/pos_config_view.xml
> +                        <label for="iface_display_categ_images" string="Customer deselection interval (sec)"/>
The value of the parameter "for" is incorrect
![image](https://user-images.githubusercontent.com/33877236/73833229-73187e00-482b-11ea-95ec-4329cff86d9e.png)

2020-02-05 10:26 UTC, Enigma228322 commented on pos_partner_deselection/views/pos_config_view.xml
> +                        <label for="iface_display_categ_images" string="Customer deselection interval (sec)"/>
May i just delete this?

2020-02-05 10:27 UTC, Enigma228322 commented on pos_partner_deselection/views/pos_config_view.xml
> +                        <label for="iface_display_categ_images" string="Customer deselection interval (sec)"/>
> May i just delete this?

Tag "for"

2020-02-05 10:37 UTC, Ramil-Mukhametzyanov commented on pos_partner_deselection/views/pos_config_view.xml
> +                        <label for="iface_display_categ_images" string="Customer deselection interval (sec)"/>
Yes.

2020-02-05 12:35 UTC, Ommo73 commented on pos_partner_deselection/README.rst
>  Tested on Odoo 10.0 db994ca57af4f09953946dede3950c2eb7a94871
Please change version and add new commit hash

2020-02-05 12:35 UTC, Ommo73 commented on pos_partner_deselection/views/pos_config_view.xml
> +    Copyright 2019 Vildan Safin <https://it-projects.info/team/KolushovAlexandr>
now 2020

2020-02-05 12:35 UTC, Ommo73 commented on pos_partner_deselection/views/pos_config_view.xml
> +    Copyright 2019 Vildan Safin <https://it-projects.info/team/KolushovAlexandr>
and change the link please

2020-02-05 13:44 UTC, Enigma228322 commented on pos_partner_deselection/views/pos_config_view.xml
> +    Copyright 2019 Vildan Safin <https://it-projects.info/team/KolushovAlexandr>
:two::one::two::one:

2020-02-05 13:46 UTC, Enigma228322 commented on pos_partner_deselection/README.rst
>  Tested on Odoo 10.0 db994ca57af4f09953946dede3950c2eb7a94871
Done

2020-02-06 06:10 UTC, yelizariev approved these changes

2020-02-08 09:35 UTC, Ommo73 approved these changes

2020-02-12 09:18 UTC, ilmir-k commented
@Enigma228322 there is a conflict

2020-02-26 06:48 UTC, yelizariev commented
There are still conflicts

2020-03-09 23:30 UTC, KolushovAlexandr approved these changes

2020-03-11 07:53 UTC, yelizariev commented on pos_partner_deselection/__manifest__.py
> +    "images": ['images/pos_partner_deselection.jpg'],
Fix lints, please

https://github.com/itpp-labs/pos-addons/pull/1193/checks?check_run_id=470431904

2020-06-02 04:59 UTC, yelizariev requested changes
Сделай отдельный комит для линтов, которые не относятся к pos_partner_deselection. Иначе у тебя написано "портирую модуль pos_partner_deselection", в котором куча других модулей изменяется

2020-07-09 09:36 UTC, Enigma228322 commented on pos_partner_deselection/__manifest__.py
> +    "images": ['images/pos_partner_deselection.jpg'],
![image](https://user-images.githubusercontent.com/17904007/87023554-4c52df00-c1f1-11ea-8d66-04633d49f2fc.png)
@yelizariev что с этой ошибкой делать?
Денис предложил подключить или удалить.

2020-07-09 09:43 UTC, trojikman commented on pos_partner_deselection/__manifest__.py
> +    "images": ['images/pos_partner_deselection.jpg'],
либо, если это пригодится в будущем, отключить проверку и сделать туду в роадмап

2020-07-16 09:34 UTC, yelizariev approved these changes

2020-07-19 14:06 UTC, trojikman approved these changes

2020-07-20 11:58 UTC, trojikman commented
I approve to merge it now

2020-07-20 11:58 UTC, merged