Fixing lints in v11.0
itpp-labs/pos-addons pull request #1206
Opened 2020-02-14 12:14 UTC by Enigma228322

2020-02-14 12:42 UTC, yelizariev requested changes

2020-02-14 12:42 UTC, yelizariev commented on pos_invoice_pay/actions/ir_action_server.xml
> +<!-- pylint: disable=file-not-used -->
Надо файл удалять https://github.com/it-projects-llc/pos-addons/pull/732/files#diff-7141021224b148d4318fda9ddb2411a0L30

2020-02-14 12:42 UTC, yelizariev commented on .flake8
> +per-file-ignores = qr_payments/tools/__init__.py:F403
Надо явно импорты указать, чтобы не было ошибки.

2020-02-14 12:42 UTC, yelizariev commented on pos_invoice_pay/static/src/js/main.js
> +            // eslint-disable-next-line  no-sequences, no-unused-expressions
:-1:

2020-02-14 12:42 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +    var posDB = require("point_of_sale.DB"); // eslint-disable-line no-unused-vars
:-1:

2020-02-14 15:06 UTC, yelizariev requested changes
На трависе ошибки в тестах. НАдо это комит применить

https://github.com/it-projects-llc/pos-addons/commit/3b7db2cc32bb416b37b3474c95fa73e59f1f715e

2020-02-14 15:38 UTC, Enigma228322 commented on pos_qr_scan/static/src/js/qr_scan.js
> +/* eslint no-undef: "off"*/
@yelizariev Я не уверен здесь, т.к. там много undef'ов

2020-02-14 15:38 UTC, Enigma228322 commented on pos_invoice_pay/static/src/js/main.js
> +            // eslint-disable-next-line  no-sequences, no-unused-expressions
@yelizariev можно исправить наверное

2020-02-14 15:38 UTC, Enigma228322 commented on .flake8
> +per-file-ignores = qr_payments/tools/__init__.py:F403
@yelizariev 
![Снимок экрана от 2020-02-14 17-34-46](https://user-images.githubusercontent.com/17904007/74532167-53cad080-4f50-11ea-9908-b6db9fa82564.png)
Как иначе исправить не знаю

2020-02-14 15:39 UTC, Enigma228322 commented on pos_invoice_pay/static/src/js/main.js
> +            // eslint-disable-next-line  no-sequences, no-unused-expressions
исправил

2020-02-14 15:39 UTC, Enigma228322 commented on .flake8
> +per-file-ignores = qr_payments/tools/__init__.py:F403
исправил

2020-02-14 15:42 UTC, Enigma228322 commented on pos_qr_scan/static/src/js/qr_scan.js
> +/* eslint no-undef: "off"*/
они же какое-то значение по умолчанию имеют, а я их меняю получается на null, не хорошо получается

2020-02-14 15:42 UTC, Enigma228322 commented on pos_invoice_pay/static/src/js/main.js
> +            // eslint-disable-next-line  no-sequences, no-unused-expressions
исправил

2020-02-14 15:43 UTC, Enigma228322 commented on .flake8
> +per-file-ignores = qr_payments/tools/__init__.py:F403
указал

2020-02-14 16:04 UTC, yelizariev requested changes

2020-02-14 16:04 UTC, yelizariev commented on pos_qr_scan/static/src/js/qr_scan.js
> +/* eslint no-undef: "off"*/
no-undef через специальный комментарий global надо исправлять https://eslint.org/docs/rules/no-undef#top

2020-02-14 16:06 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +    var posDB = require("point_of_sale.DB"); // eslint-disable-line no-unused-vars
![удоли](https://user-images.githubusercontent.com/186131/74547385-dd3ccb80-4f6d-11ea-85ae-1cede7b8929e.jpg)

2020-02-14 16:07 UTC, yelizariev commented on pos_qr_scan/static/src/js/qr_scan.js
> +/* eslint no-alert: "off"*/
ok

2020-02-14 16:29 UTC, Enigma228322 commented on pos_qr_scan/static/src/js/qr_scan.js
> +/* eslint no-undef: "off"*/
![Снимок экрана от 2020-02-14 21-28-34](https://user-images.githubusercontent.com/17904007/74549167-fc892800-4f70-11ea-8925-f6b9100ef076.png)
Когда ставлю global, ругается на переменную webkit

2020-02-17 07:12 UTC, Enigma228322 commented on pos_qr_scan/static/src/js/qr_scan.js
> +                webkit = true; // eslint-disable-line no-undef
@yelizariev это норм?

2020-02-17 07:13 UTC, Enigma228322 commented on pos_qr_scan/static/src/js/qr_scan.js
> +                webkit = true; // eslint-disable-line no-undef
@yelizariev если указать webkit как global, вот такая ошибка вылезает
![Снимок экрана от 2020-02-14 21-28-34](https://user-images.githubusercontent.com/17904007/74631445-d2a55080-517e-11ea-9737-b9b678e8d78a.png)

2020-02-17 07:15 UTC, yelizariev commented on pos_qr_scan/static/src/js/qr_scan.js
> +                webkit = true; // eslint-disable-line no-undef
Нет, удали переменную не успользуется

2020-02-17 07:37 UTC, Enigma228322 commented on .pylintrc
> +    #missing-manifest-dependency,
@yelizariev норм?
pos_multi_session/external_tests/common.py:17: [W7936(missing-manifest-dependency), ] Missing external dependency "xmlrpclib" from manifest. More info: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#external-dependencies

2020-02-17 07:39 UTC, Enigma228322 commented on pos_qr_scan/static/src/js/qr_scan.js
> +                webkit = true; // eslint-disable-line no-undef
@yelizariev удалил

2020-02-17 07:41 UTC, yelizariev commented on .pylintrc
> +    #missing-manifest-dependency,
Нет, в самом файле надо отключить.

2020-02-17 07:42 UTC, yelizariev commented on .pylintrc
> +    #missing-manifest-dependency,
Гугли disable pylint in file

2020-02-17 07:47 UTC, Enigma228322 commented on .pylintrc
> +    #missing-manifest-dependency,
@yelizariev отключил в файле

2020-02-18 10:15 UTC, yelizariev approved these changes
should be safe. I'll merge once travis tests are passed

2020-02-18 10:36 UTC, yelizariev commented
I approve to merge it now

2020-02-18 10:36 UTC, merged