:cherries: renaming
itpp-labs/pos-addons pull request #1229
Opened 2020-03-17 11:16 UTC by trojikman

2020-03-18 07:46 UTC, yelizariev requested changes

2020-03-18 07:46 UTC, yelizariev commented on pos_disable_payment_restaurant/README.rst
> + POS: Disable payments
Модуль ничего не делает про платежи. Старое название ссылалось на модуль pos_disable_payment, который удален в 12

```

* ``Allow change Qty for kitchen orders``
* ``Allow remove kitchen order line``
```

2020-03-18 15:09 UTC, trojikman commented on pos_disable_payment_restaurant/README.rst
> + POS: Disable payments
Какие будут предложения?

2020-03-19 06:01 UTC, yelizariev commented on pos_disable_payment_restaurant/README.rst
> + POS: Disable payments
Может не переименовывать пока?

2020-03-19 06:01 UTC, yelizariev commented on pos_disable_payment_restaurant/README.rst
> + POS: Disable payments
Этот вопрос никто не разбирал, похоже. Забыли

2020-03-19 10:02 UTC, trojikman commented on pos_disable_payment_restaurant/README.rst
> + POS: Disable payments
Done

2020-03-19 15:58 UTC, yelizariev approved these changes

2020-03-19 15:58 UTC, merged