:ambulance: corrected work with pricelist in pos_product_available
itpp-labs/pos-addons pull request #1253
Opened 2020-05-14 13:22 UTC by Enigma228322

There was an error in https://github.com/odoo/odoo/blame/12.0/addons/point_of_sale/static/src/js/models.js#L1282.
So, with pos_product_available it doesnt work correctly, cause 
``` item.product_tmpl_id || item.product_tmpl_id[0] === self.product_tmpl_id ``` in this string are comparing integer with an array. By the way, here's comparing products ids.
Signed-off-by: Vildan Safin <safin@it-projects.info>

2020-05-14 14:42 UTC, Enigma228322 commented on pos_product_available/static/src/js/pos.js
> +                        item.product_tmpl_id[0] === self.product_tmpl_id[0]) &&
self.product_tmpl_id -> self.product_tmpl_id[0]

2020-05-25 14:53 UTC, Ramil-Mukhametzyanov commented
solved https://github.com/itpp-labs/pos-addons/issues/1244 & https://github.com/itpp-labs/pos-addons/issues/1245

2020-05-26 07:10 UTC, yelizariev requested changes
Если ты копипастишь метод, то надо помечать линии, которые ты добавил. Тогда если в оду всё поменяют в методе и нужно будет модуль обновлять, то проще будет понять что именно в новой версии метода нужно изменить в рамках модуля.

Плюс в ридми надо написатЬ, что модуль потенциально несовместим с другими модулями, которые перезаписывают метод get_price

2020-05-26 07:30 UTC, yelizariev commented on pos_product_available/static/src/js/pos.js
> +                        item.product_tmpl_id[0] === self.product_tmpl_id[0]) &&
Такие пояснения надо в комментариях кода делать, а не ПР

2020-06-08 04:38 UTC, yelizariev commented
@Enigma228322 пришлешь исправления по замечаниям?
https://github.com/itpp-labs/pos-addons/pull/1253#pullrequestreview-418024260

2020-06-08 04:38 UTC, yelizariev commented
И это https://github.com/itpp-labs/pos-addons/pull/1253#discussion_r430209780

2020-07-07 13:37 UTC, yelizariev commented on pos_product_available/static/src/js/pos.js
> +            IMPORTANT: Changed lines are 137 and 138.
Ссылки на строки это как бы не очень хорошая идея. Убери или замени на какое-то описание. Или прямо возле измененного кода комментарий добавь

2020-07-07 13:38 UTC, yelizariev commented on pos_product_available/README.rst
> +Module potentialy isn't compatible with modules that overrides 'get_price' method in JS
Сделай нормальное форматирование 


![image](https://user-images.githubusercontent.com/186131/86789740-11ca3480-c081-11ea-8d58-1b5d9445c1a8.png)

2020-07-08 17:12 UTC, trojikman approved these changes
По интерфейсу всё вроде норм

2020-07-08 17:18 UTC, trojikman commented on pos_product_available/README.rst
> +Module potentialy isn't compatible with modules that overrides 'get_price' method in JS
```suggestion
Module potentialy isn't compatible with modules that overrides `get_price` method in JS
```
Об этом ты говоришь?

2020-07-08 17:20 UTC, trojikman commented on pos_product_available/README.rst
> +Module potentialy isn't compatible with modules that overrides 'get_price' method in JS
```suggestion
Module potentialy isn't compatible with modules that overrides `get_price` method in JS
```
Об этом ты говоришь?

2020-07-09 12:34 UTC, yelizariev commented on pos_product_available/README.rst
> +Module potentialy isn't compatible with modules that overrides 'get_price' method in JS
Не только. Прочитай что написано на скриншоте

2020-07-09 12:35 UTC, yelizariev approved these changes

2020-07-09 12:35 UTC, yelizariev commented on pos_product_available/static/src/js/pos.js
> +            IMPORTANT: Changed line - (!item.product_tmpl_id || item.product_tmpl_id[0] === self.product_tmpl_id[0]).
Ivan Yelizariev, [07.07.20 19:31]
Черт ноги сломит, конечно

Ivan Yelizariev, [07.07.20 19:32]
Что на что поменял по описанию не поймёшь

Ivan Yelizariev, [07.07.20 19:32]
Но можешь так оставить, другие программисты оценят когда-нибудь. Или ты сам, когда придёшь обновлять опять

2020-07-09 17:53 UTC, trojikman commented on pos_product_available/README.rst
> +Module potentialy isn't compatible with modules that overrides 'get_price' method in JS
Всё норм же вроде с переносом
![Screenshot from 2020-07-09 22-52-23](https://user-images.githubusercontent.com/23641186/87073457-e0936500-c236-11ea-980b-0dfadf8d486a.png)

2020-07-10 20:06 UTC, trojikman commented
I approve to merge

2020-07-10 20:09 UTC, trojikman commented
I approve to merge it now

2020-07-10 20:09 UTC, merged