:tada::one::one: payment_wechat
itpp-labs/pos-addons pull request #1270
Opened 2020-06-17 22:06 UTC by trojikman

from #1181

2020-06-17 22:09 UTC, trojikman commented on payment_wechat/controllers/p_w_controllers.py
> +        print(r1)
@yelizariev Эти принты для дебага ведь? выпиливаю?

2020-06-18 04:07 UTC, em230418 requested changes
Мимо проходил. В запросы на внешние сервера надо timeout выставить.

https://requests.readthedocs.io/en/master/user/quickstart/#timeouts
> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely

2020-06-18 06:21 UTC, yelizariev commented on payment_wechat/controllers/p_w_controllers.py
> +        print(r1)
Да, убирай

2020-06-18 17:30 UTC, trojikman commented on payment_wechat/views/views.xml
> +<odoo>
@yelizariev нужна эта вьюшка? она в манифесте не подключена

2020-06-18 17:31 UTC, trojikman commented on payment_wechat/views/views.xml
> +<odoo>
Хотя я думал что Динар будет ругаться, не ругается оказывается

2020-06-19 11:38 UTC, yelizariev commented on payment_wechat/views/views.xml
> +<odoo>
Да, нужна скорее всего. Не знаю почему не подключена

2020-06-19 12:00 UTC, trojikman commented
Модуль пока неустанавливаемый так как не закончен, вливаю так

2020-06-19 12:05 UTC, trojikman commented
I approve to merge it now

2020-06-19 12:05 UTC, merged