:rainbow: pre-commit
itpp-labs/pos-addons pull request #1383
Opened 2021-03-17 06:31 UTC by mentalko

2021-03-18 06:48 UTC, trojikman requested changes

2021-03-18 06:48 UTC, trojikman commented on pos_invoice_pay/static/src/js/main.js
> +                item.invoice_payment_state = stateAttr;
Получается бессмысленное переопределение какое-то, не лучше ли эти две строки просто удалить?

2021-03-18 08:16 UTC, mentalko commented on pos_invoice_pay/static/src/js/main.js
> +                item.invoice_payment_state = stateAttr;
Готово. убрал.

2021-03-26 08:08 UTC, trojikman requested changes
@mentalko надо объединить коммиты в один (rebase) и применить тег отсюда https://gitlab.com/itpp/handbook/-/blob/master/documenting-updates.md
:rainbow: вроде бы подходит

2021-05-04 16:26 UTC, trojikman requested changes
добавь свой копирайт в манифесте и в js файле, где ты внёс исправление

2021-05-04 16:28 UTC, trojikman requested changes

2021-05-04 16:28 UTC, trojikman commented on pos_invoice_pay/doc/changelog.rst
> +**Improvement:** Clean js code
я думаю, это слишком общее описание изменений и можно точнее описать , что было сделано.

2021-05-11 11:35 UTC, closed without merging