8.0 [ADD] added function of storing data on a server
itpp-labs/pos-addons pull request #153
Opened 2016-09-23 08:56 UTC by GabbasovDinar

2016-09-23 11:00 UTC, yelizariev commented on pos_multi_session/external_tests/README.rst
> +    pip2 install pyTelegramBotAPI
you don't need pyTelegramBotAPI for this module :smile:

2016-09-23 11:01 UTC, yelizariev commented on pos_multi_session/external_tests/README.rst
> +* not use ``--workers``
* use ``--workers=0``

2016-09-23 11:01 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    _name = 'pos.multi_session.order.list'
No need for ``list`` here

    _name = 'pos.multi_session.order'

2016-09-23 11:03 UTC, yelizariev commented on pos_multi_session/controllers/pos_multi_session.py
> +            return res
move this code to pos_multi_session_models.py and make single call here:

     res = request.env["pos.multi_session"].browse(int(multi_session_id)).on_update_message(message)
      return res

2016-09-23 11:04 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    def get_order(self):
def get_orders(self):

2016-09-23 11:05 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    def get_order(self):
i.e. use plural form

2016-09-23 11:06 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        self.broadcast(message)
:+1:

2016-09-23 11:07 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        if len(order) > 0:
what if ``len(order)==2`` ?

2016-09-23 11:09 UTC, yelizariev reviewed
Currently, only collecting information on server is implemented.

2016-09-24 17:27 UTC, GabbasovDinar commented on pos_multi_session/pos_multi_session_models.py
> +        if len(order) > 0:
@yelizariev  It does not matter. The condition len (order)> 0 means that the object exists with the current UID

2016-09-24 17:30 UTC, GabbasovDinar commented on pos_multi_session/controllers/pos_multi_session.py
> +            return res
@yelizariev  Ok

2016-09-24 18:30 UTC, GabbasovDinar commented on pos_multi_session/pos_multi_session_models.py
> +        if len(order) > 0:
Only len (order) == 1 or len (order) == 0

2016-09-24 18:31 UTC, GabbasovDinar commented on pos_multi_session/pos_multi_session_models.py
> +    def get_order(self):
@yelizariev on all functions ?

2016-09-26 07:03 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    def get_order(self):
for all functions related multi record.

2016-10-18 09:53 UTC, yelizariev requested changes
Don't use online.js, don't save offline messages

2016-10-18 09:53 UTC, yelizariev commented on pos_multi_session/static/lib/online.js
> +})(window);
Delete this file

2016-10-21 09:00 UTC, yelizariev commented
This branch has conflicts that must be resolved

2016-10-27 04:53 UTC, yelizariev requested changes
Clean it up

2016-10-27 04:53 UTC, yelizariev commented on pos_multi_session/external_tests/phantomtest.js
> +                }, 6000);
Why do youo add timeout?

2016-10-27 04:53 UTC, yelizariev commented on pos_multi_session/external_tests/tests/inject.js
> +        console.log(JSON.stringify(order));
return message back

2016-10-27 04:53 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +            }, 15000)
why so big timeout?

2016-10-27 04:53 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        if len(active_sessions) == 1 and active_sessions.user_id.id == self.user_id.id:
You can add this check after calling super and simplify condition:

    if len(active_sessions) == 0:

2016-10-27 04:53 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    if (collection.order_in_server || order.order_in_server ) {
What is collection? Why do you think, that it has order_in_server attribute?

2016-10-27 04:53 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            console.log("пришло сообщение для ",  this.pos_session.user_id[1]);
There is a log message already. No need for another one.

2016-10-27 06:37 UTC, yelizariev requested changes
Whole review. Clean it up.

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/external_tests/tests/inject.js
> -        this._rand($('.product')).click()
undo this change. Add two products here

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +            # admin orders remove
```
 # admin removes orders
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +            # demo orders remove
```
        # demo removes orders
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +                    share.order = mstest.save_order();
don't save order to share object, if you are not going to compare it in the next step. Add a comment, if you use it only to print current state

```
                mstest.fill_order();
                // print current state of the order
                mstest.save_order();
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +            # admin update order
```
        # admin updates order
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    order_ID = fields.Integer(string="Order number", default=1)
```
help="Current Order Number shared across all POS in Multi Session"
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        for r in self:
No need to use `for r in self`, because it's always called with single record in self. Remove it and `self.ensure_one` instead.

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        if order:  # only one object with current order_uid
Correct comment is

```
 # order already exists
```

while your comment says "only one exists" (i.e. it could be zero or multiple orders otherwise)

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    @api.one
don't use `api.one`

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        for r in self:
No need to use `for r in self`, because it's always called with single record in self. Remove it and `self.ensure_one` instead.

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +            for e in order_obj:
what is `e`?

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +            for e in order_obj:
```
 for order in self.order_ids:
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    @api.one
don't use `api.one`

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        # self.broadcast(message)
remove commented code

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        # self.broadcast(message)
remove commented code

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    if (order.ms_info.created.pos.id != self.config.id) {
User shall not be able to remove his order if one is on server already

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            console.log("пришло сообщение для ",  this.pos_session.user_id[1]);
sic!

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    if (self.message_ID + 1 < data.message_ID) {
I suggest to use 

```
                if (self.message_ID + 1 != data.message_ID) {
```

instead

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +                msg['action'] = 'request_sync_all'
```
            msg['action'] = 'sync_all'
```

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    def get_orders(self, message):
rename to `get_sync_all`

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                if (message.action != 'request_sync_all') {
word ``request`` mislead here

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    } else if (action == 'update') {
rename this action to ``update_order`` please

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +
Refactor this block:

    if (self.message_ID + 1 < data.message_ID && action != 'sync_all' ){
        self.multi_session.request_sync_all();

    } else {
         this.message_ID = data.message_ID;
    }

    if (order && action == 'remove_order'){
        order.destroy({'reason': 'abandon'});
    } else {
        this.ms_do_update(order, data);
    }

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            order.order_in_server = true;
order_on_server

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            console.log(arguments);
to delete

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            self.request_sync = false;
At a function with name ``offline_warning`` you can only show warning. You cannot update essential variables here

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            self.request_sync = false;
rename function or move the code to another place

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.request_sync = true;
bad name for the variable. What does it mean?

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.request_sync = true;
Do you really need this variable? Can you use ``client_online`` instead?

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            console.log(message.data);
to delete

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                console.log("Ошибка запроса. Нет соединения с сервером.");
sic!

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    orders.order_in_server = false;
What does it mean? All orders are not on server anymore?

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    console.log("отображаем сообщение об отсутсвии соединения с сервером");
sic!

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                console.log("сообщенеие отправлено успешно");
sic!

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    console.log("Удаляем вызов синхронизации");
sic!

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            self.offline_sync_all = setInterval(function(){
self.offline_sync_all_timer

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +        sync_offline_orders: function() {
Probably better name is ``send_offline_orders``

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +        //сравнить номера
sic!

2016-10-27 06:37 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +        offline_sync: function(){
start_offline_sync_timer

?

2016-10-27 06:37 UTC, yelizariev commented on pos_ticket_custom/static/src/js/pos.js
> -})();
Why do you remove this file from another module?

2016-10-27 09:26 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.request_sync = true;
@yelizariev да, я хочу показывать сообщение клиенту только один раз, а не каждый раз когда он совершает какое либо действие

2016-10-27 09:34 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    orders.order_in_server = false;
@yelizariev how I can select a current order?

2016-10-27 09:36 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.request_sync = true;
Then rename it to show_offline_warning

2016-10-27 09:38 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            self.request_sync = false;
@yelizariev  "self.request_sync = false" is not essential variable. This variable is needed in order not to repeat an alert

2016-10-27 09:39 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    orders.order_in_server = false;
Return deferred object and handle fail event in do_ms_update function

2016-10-27 09:40 UTC, yelizariev commented
- [ ] fix lint errors on travis

2016-10-27 09:41 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +        offline_sync: function(){
yes

2016-10-27 09:44 UTC, GabbasovDinar commented on pos_ticket_custom/static/src/js/pos.js
> -})();
I don't know. It's not me

2016-10-27 14:11 UTC, yelizariev requested changes
- 2 items from previous review are not fixed. 
- Get rid of Cyrillic comments and messages

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +            }, 15000)
why so big timeout?

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            console.log("пришло сообщение для ",  this.pos_session.user_id[1]);
sic!

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                console.log("Ошибка запроса. Нет соединения с сервером.");
sic!

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    console.log("Удаляем вызов синхронизации");
sic

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                console.log("сообщенеие отправлено успешно");
Sic!

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    console.log("отображаем сообщение об отсутсвии соединения с сервером");
sic!

2016-10-27 14:11 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            // отправить исправленные заказы на сервер,
sic!

2016-10-27 14:11 UTC, yelizariev commented on pos_ticket_custom/static/src/js/pos.js
> -})();
Return the file back

2016-10-28 12:24 UTC, GabbasovDinar commented on pos_multi_session/external_tests/tests/test_sync.py
> +            }, 15000)
иначе клиент не успевал синхронизироваться с сервером, сократил до 9 секунд

2016-10-28 12:54 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +            }, 15000)
окей

2016-10-28 12:56 UTC, yelizariev commented
Revert file

2016-10-28 12:57 UTC, yelizariev commented
- [ ] Revert  file access attributes
```

0  pos_multi_session/README.rst 100644 → 100755
No changes.
View 
0  pos_multi_session/__init__.py 100644 → 100755
No changes.
View 
0  pos_multi_session/__openerp__.py 100644 → 100755
No changes.
View 
0  pos_multi_session/controllers/__init__.py 100644 → 100755
No changes.
View 
0  pos_multi_session/controllers/pos_multi_session.py 100644 → 100755
No changes.
View 
0  pos_multi_session/demo/demo.xml 100644 → 100755
No changes.
View 
0  pos_multi_session/doc/changelog.rst 100644 → 100755
No changes.
View 
0  pos_multi_session/doc/index.rst 100644 → 100755
No changes.
View 
0  pos_multi_session/external_tests/README.rst 100644 → 100755
No changes.
View 
0  pos_multi_session/external_tests/__init__.py 100644 → 100755
No changes.
```

2016-10-29 13:04 UTC, yelizariev commented
There are still few lint warnings:
```

======== Testing test_flake8 ========
pos_multi_session/external_tests/common.py:187:39: W291 trailing whitespace
======== Testing test_pylint ========
************* Module pos_multi_session.external_tests.common
pos_multi_session/external_tests/common.py:59: [W0102(dangerous-default-value), ExternalTestCase.execute_kw] Dangerous default value [] as argument
pos_multi_session/external_tests/common.py:59: [W0102(dangerous-default-value), ExternalTestCase.execute_kw] Dangerous default value [] as argument
From https://github.com/it-projects-llc/pos-addons
 * [new branch]      8.0-pos_multi_session-2.0.0 -> origin/8.0-pos_multi_session-2.0.0
Start lint check just in modules changed
************* Module pos_multi_session
pos_multi_session/doc/changelog.rst:1: [E7901(rst-syntax-error), ]  Hyperlink target "changelog" is not referenced.
pos_multi_session/demo/demo.xml:34: [W7907(duplicate-xml-fields), ]  Duplicate xml field "groups_id" in lines 37
************* Module pos_multi_session.pos_multi_session_models
pos_multi_session/pos_multi_session_models.py:77: [W8104(api-one-deprecated), PosMultiSession.get_message_ID] api.one deprecated
```

2016-10-29 13:05 UTC, yelizariev requested changes

2016-10-29 13:05 UTC, yelizariev commented on pos_multi_session/external_tests/common.py
> +    def execute_kw(self, model, method, rpc_args=[], rpc_kwargs=[], uid=None, password=None):
Revert it back and add to the function body instead
```

rpc_args = rpc_args or []
rpc_kwargs = rpc_kwargs or []
```

2016-10-31 08:27 UTC, yelizariev requested changes

2016-10-31 08:27 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
>              if r.multi_session_message_ID:
No need to check it  here. It's not a problem if multi_session_message_ID is zero

2016-10-31 08:41 UTC, yelizariev approved these changes

2016-10-31 09:11 UTC, merged