[WIP] 8.0 fix flake
itpp-labs/pos-addons pull request #155
Opened 2016-10-04 10:56 UTC by manawi

2016-10-05 09:28 UTC, yelizariev commented
runbot warning:

```
2016-10-05 09:18:35,198 18299 INFO 06932-155-e117b1-all openerp.modules.loading: loading tg_partner_firstname/tg_partner_view.xml
2016-10-05 09:18:35,206 18299 WARNING 06932-155-e117b1-all openerp.models: ir.ui.view.create() with unknown fields: view_type
2016-10-05 09:18:35,256 18299 WARNING 06932-155-e117b1-all openerp.models: ir.ui.view.create() with unknown fields: view_type
```

2016-10-11 03:19 UTC, manawi commented
@yelizariev ,done

2016-10-11 03:28 UTC, yelizariev requested changes

2016-10-11 03:28 UTC, yelizariev commented on pos_debt_notebook/README.rst
> +* `IT-Projects LLC <https://it-projects.info>`___
undo triple underscore

2016-10-11 12:40 UTC, merged