[WIP] 9.0 travis fix
itpp-labs/pos-addons pull request #158
Opened 2016-10-05 13:22 UTC by manawi

2016-10-06 12:47 UTC, yelizariev commented on pos_debt_notebook/README.rst
> +* `IT-Projects LLC <https://it-projects.info>`___
revert triple underscore

2016-10-06 12:48 UTC, yelizariev requested changes
```
  find . -type f -name '*.rst' | xargs sed -i 's/___/__/g'
```

2016-10-11 03:21 UTC, manawi commented
@yelizariev ,done

2016-10-11 06:22 UTC, yelizariev commented
:+1:

2016-10-11 06:50 UTC, yelizariev commented
I'm going to merge this PR first https://github.com/it-projects-llc/pos-addons/pull/161

2016-10-11 06:52 UTC, yelizariev commented
Fix conflicts: 
This branch has conflicts that must be resolved

2016-10-11 09:51 UTC, yelizariev commented
fix this PR first
https://github.com/it-projects-llc/pos-addons/pull/155

2016-10-11 13:07 UTC, yelizariev commented
This branch has conflicts that must be resolved

2016-10-13 06:36 UTC, yelizariev requested changes

2016-10-13 06:36 UTC, yelizariev commented on pos_debt_notebook/README.rst
> +* `IT-Projects LLC <https://it-projects.info>`___
triple underscore still present

2016-10-13 07:25 UTC, manawi commented
@yelizariev done

2016-10-13 07:45 UTC, merged