[ADD] added revision ID for message, function order number check
itpp-labs/pos-addons pull request #166
Opened 2016-11-02 13:25 UTC by GabbasovDinar

2016-11-02 13:49 UTC, yelizariev requested changes
You broke `send` function in js and you don't really check revision_ID in server side (result of the function order_number_check is ignored)

Everything else is not bad.

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +            return False
I guess you need to raise an Exception here

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +            print "The client is not updated"
remove print, use ``_logger``

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
>          order = self.env['pos.multi_session.order'].search([('order_uid', '=', order_uid)])
it's better to call ``order_number_check`` here to don't search order twice

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    def order_number_check(self, message):
rename to ``check_order_revision`` for example

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +            res = order.create({
you can use ``order`` here instead of ``res``

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +        message['data']['revision_ID'] = order.revision_ID
Probably, we don't need to send ``revision_ID`` here, because removing cannot be under

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/pos_multi_session_models.py
> +    revision_ID = fields.Integer(default=1, string="Last sent order number")
string="Revision", help="Number of updates received from clients"

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                line.revision_ID = dline.revision_ID || {};
As I understand order line doesn't have ``revision_ID``.

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.revision_ID = 1;
this.revision_ID = options.revision_ID or 1;

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                this.revision_ID = options.revision_ID;
delete it

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            }).done(function(id){
}).done(function(server_revision_ID){

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.revision_ID = 1;
Do we need revision_ID per each order line?

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            data.revision_ID = this.revision_ID;
to delete

2016-11-02 13:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    connection_status.resolve(res.revision_ID);
It has to be always resolved or rejected. You cannot just ignore it.

Don't forget, that function ``send`` is not used for ``update_order`` only and server doesn't return ``update_revision_ID`` always.

2016-11-03 08:20 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    connection_status.resolve(res.revision_ID);
да, именно поэтому делается проверка res.action == "update_revision_ID"
ну и добавил условие else connection_status.resolve()

2016-11-03 08:22 UTC, GabbasovDinar commented on pos_multi_session/pos_multi_session_models.py
> +            return False
наверное тут надо будет вернуть клиенту какое то значение, чтоб знать какая именно ошибка вышла

2016-11-04 09:33 UTC, yelizariev commented
Fix lint
```

======== Testing test_flake8 ========
pos_multi_session/pos_multi_session_models.py:9:1: F401 'openerp.osv.osv' imported but unused
pos_multi_session/pos_multi_session_models.py:10:1: F401 'openerp.tools.translate._' imported but unused
pos_multi_session/pos_multi_session_models.py:11:1: F401 'openerp.exceptions.Warning as UserError' imported but unused
======== Testing test_pylint ========
From https://github.com/it-projects-llc/pos-addons
 * [new branch]      8.0-pos_multi_session-2.0.0 -> origin/8.0-pos_multi_session-2.0.0
Start lint check just in modules changed
************* Module pos_multi_session
pos_multi_session/doc/changelog.rst:1: [E7901(rst-syntax-error), ]  Hyperlink target "changelog" is not referenced.
pos_multi_session/static/src/js/pos_multi_session.js:36: [W7903(javascript-lint), ] Missing semicolon.
pos_multi_session/static/src/js/pos_multi_session.js:445: [W7903(javascript-lint), ] Missing semicolon.
pos_multi_session/static/src/js/pos_multi_session.js:1: [W7908(missing-newline-extrafiles), ]  Missing newline
************* Module pos_multi_session.pos_multi_session_models
pos_multi_session/pos_multi_session_models.py:9: [W0402(deprecated-module), ] Uses of a deprecated module 'openerp.osv'
pos_multi_session/pos_multi_session_models.py:127: [E8102(invalid-commit), PosMultiSession.broadcast_message] Use of cr.commit() directly - More info https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#never-commit-the-transaction

```

2016-11-04 09:40 UTC, yelizariev requested changes
Tiny style updates are required

2016-11-04 09:40 UTC, yelizariev commented on pos_multi_session/external_tests/tests/test_sync.py
> +                 // mstest.check_inclusion(share.demo_order, synced_order);
add a comment

// this test is currently not supported: request from demo is ignored and hist state is rollbacked

2016-11-04 09:40 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    var warning_message = _t('The conflict during of synchronization, repeat your operation');
var warning_message = _t('There is a conflict during synchronization, try your action again');

2016-11-04 10:21 UTC, merged