[ADD] a more load button in POS debt history
itpp-labs/pos-addons pull request #293
Opened 2017-04-27 10:36 UTC by ufaks

2017-04-28 03:29 UTC, yelizariev requested changes
https://en.m.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

2017-04-28 03:29 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                    var new_limit = $('#debt_history tr').length - 2 + this.debt_history_limit;
You cannot do it according to mvc approach. Fix that please

2017-04-28 09:02 UTC, yelizariev requested changes

2017-04-28 09:02 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            this.debt_history_built_lines = 0;
Can it be more clear names? Also, use a separate setting for initial limit.

E.g.

            this.debt_history_limit_initial = 10;
            this.debt_history_limit_increment = 20;
            this.debt_history_built_current = 0;

2017-05-03 16:45 UTC, manu686 commented
yay 👍

2017-05-04 06:51 UTC, merged