[FIX] endless requests and errors POS MS
itpp-labs/pos-addons pull request #346
Opened 2017-08-08 10:28 UTC by KolushovAlexandr

pos multisession not pos multisession restaurant

2017-08-08 11:51 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            alert(this.pos.config.multi_session_id[0])
why?

2017-08-08 11:51 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
Use "this" instead "model"

2017-08-08 11:51 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
Use "this" instead "model"

2017-08-08 11:52 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
Use "this" instead "model"

2017-08-08 12:03 UTC, yelizariev requested changes

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            };
exit from function instead on moving everything to block.

```

if (!condition)
    return
//main block
```

instead of
```

if (condition){
//main block
}

```

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
- [ ] use `` this.multi_session`` to check

- [ ] exit from function instead on moving everything to block.

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
use this.multi_session to check

 exit from function instead on moving everything to block.

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
use this.multi_session to check

 exit from function instead on moving everything to block.

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
use this.multi_session to check

 exit from function instead on moving everything to block.

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +
don't touch git history if possible

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            });
dont' touch git history if  possible

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/xml/pos_multi_session.xml
> +            <t t-if="widget.pos.config.multi_session_id">
Use ``widget.pos.multi_session`` instead

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +        if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
the same as above

2017-08-08 12:03 UTC, yelizariev commented on pos_multi_session/static/src/xml/pos_multi_session.xml
> +    </t>
don't touch git history if possible

2017-08-09 07:25 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (models.pos && models.pos.config.multi_session_id && models.pos.config.multi_session_id[0]){
@KolushovAlexandr @yelizariev тут походу нельзя делать так, потому что на момент загрузки pos, нет параметра settings, скорее всего придется через this.ready и уже там проверять условие

2017-08-28 06:26 UTC, closed without merging