10.0 pos ms 324 split
itpp-labs/pos-addons pull request #352
Opened 2017-08-16 10:13 UTC by KolushovAlexandr

2017-08-17 03:12 UTC, yelizariev commented
@invitu https://github.com/it-projects-llc/pos-addons/issues/321 and @multiwebinc https://github.com/it-projects-llc/pos-addons/issues/268
please review this PR. Use runbot if needed

2017-08-17 03:19 UTC, yelizariev requested changes

2017-08-17 03:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (new_lines && new_lines.length) {
No need for this check. Just use ``new_lines.forEach``

2017-08-17 03:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    new_line = true;
No need for ``new_line`` variable. You can add ``line``  to ``new_lines`` array right here

2017-08-17 03:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            var new_lines = [];
Please, add comment to this file why do you aggregate new lines first and then add it to order, instead of adding lines immediatly (as it was before). Why it didn't work before?

2017-08-17 03:27 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            if (this.temporary){
Add a comment to code, why we cannot call super at this case.

2017-08-17 09:13 UTC, yelizariev requested changes

2017-08-17 09:13 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    new_lines[new_lines.length - 1] = line;
Useless code. No need to update line.

2017-08-17 09:24 UTC, yelizariev commented
- [ ] Resolve  conflicts

This branch has conflicts that must be resolved

2017-08-20 02:24 UTC, yelizariev commented on pos_multi_session_restaurant/doc/changelog.rst
> +- FIX: "ReferenceError: Can't find variable: Model" during new partner creation in POS.
:+1:

2017-08-20 02:24 UTC, yelizariev commented on pos_multi_session_restaurant/doc/changelog.rst
> +- FIX: Issue with bill splitting: incorrect creation of a new order for other POSes after synchronization.
:+1:

2017-08-22 10:40 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                order.new_order = false;
Why do we need it?

2017-08-22 10:54 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                order.new_order = false;
It is needed for correct display of order numbers for those who split a bill. I described it in detail in my task card.

2017-08-22 14:16 UTC, yelizariev requested changes

2017-08-22 14:16 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                line.order.trigger('change:sync');
revert indent

2017-08-22 14:16 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.temporary){
I think ms_check is more proper place to filter out temporary orders

2017-08-22 15:15 UTC, yelizariev commented
Thanks to @invitu for #324
closes #321 
closes #268`
Also, commit 
[PORT] update imports
[DOC] add notes to changelog, bump new version

2017-08-22 15:15 UTC, merged