[FIX] remove sequence field in form and tree view in pos_order_note
itpp-labs/pos-addons pull request #358
Opened 2017-08-21 06:06 UTC by GabbasovDinar

2017-09-02 12:09 UTC, yelizariev requested changes

2017-09-02 12:09 UTC, yelizariev commented on pos_order_note/static/src/js/order_note.js
> +                        }
Use ``continue`` and don't change indent

2017-10-07 02:46 UTC, gustavovalverde commented
@GabbasovDinar, I'll be testing this tomorrow and let you know.

2017-10-17 13:54 UTC, yelizariev commented
test

2017-10-18 09:37 UTC, ilmir-k approved these changes
Approved :+1:

2017-10-18 09:39 UTC, ilmir-k commented
@yelizariev here are lint warnings related to pos_multi_session_restaurant only, so you can merge it

2017-10-19 13:30 UTC, yelizariev requested changes

2017-10-19 13:30 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            return res;
you can always use code

                res[0] = this.uid;
                res.join('|');

no need for two cases

2017-10-19 13:30 UTC, yelizariev commented on pos_order_note/static/src/js/tour.js
> +        trigger: ".product_note #1",
having ``id="1"`` in html is a bad idea

2017-10-26 05:35 UTC, yelizariev approved these changes

2017-10-26 05:35 UTC, merged