[FIX] ms id test
itpp-labs/pos-addons pull request #377
Opened 2017-08-31 13:30 UTC by KolushovAlexandr

2017-08-31 14:39 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
>              }
@KolushovAlexandr сделай нормальное условие

2017-09-01 08:10 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (this.new_order && this.pos.config.multi_session_id) {
```
if (!this.pos.config.multi_session_id)
    return
```

2017-09-05 10:58 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (this.new_order && this.pos.config.multi_session_id) {
Ivan, it leads to incorrect order numbers display

2017-09-06 12:38 UTC, yelizariev commented
Related issue:
https://github.com/it-projects-llc/pos-addons/issues/322

2017-09-17 08:56 UTC, yelizariev requested changes

2017-09-17 08:56 UTC, yelizariev commented on pos_multi_session/multi_session_view.xml
> +                            <field name="pos_ids" widget="one2many" string="POSes in Multi-session"/>
Allow to add only POS with closed sessions (use ``domain``)

2017-09-17 08:56 UTC, yelizariev commented on pos_multi_session/README.rst
> +POSes are able to work without synchronization. Different in behavior: each new order is immediately given a number. Avoid including unsynchronized POS to multi session with unclosed session. It may
If you don't allow to make wrong configuration, you don't need to say "Avoid" here

2017-09-17 08:56 UTC, yelizariev commented on pos_multi_session_restaurant/views/views.xml
> +                        <field name="floor_ids" widget="many2many_tags" attrs="{'required':[('multi_session_id', 'in', [None,False])], 'invisible':[('multi_session_id', 'not in', [None,False])]}"/>
You don't need to make it required

2017-09-17 08:56 UTC, yelizariev commented on pos_multi_session_restaurant/views/views.xml
> +                        <field name="floor_ids" widget="many2many_tags" attrs="{'required':[('multi_session_id', 'in', [None,False])], 'invisible':[('multi_session_id', 'not in', [None,False])]}"/>
Add related field ms_floor_ids and show it in MS section of the form.

2017-09-17 09:01 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.pos.config.multi_session_id){
This code is never used (you have ``return`` above this code)

2017-09-18 09:31 UTC, KolushovAlexandr commented on pos_multi_session/multi_session_view.xml
> +                            <field name="pos_ids" widget="one2many" string="POSes in Multi-session"/>
@yelizariev Is it possible to get current_session_state field which is stored in pos.config from pos.multi_session form by pos_ids if pos_ids is one2many field?

2017-09-20 11:35 UTC, yelizariev requested changes

2017-09-20 11:35 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    current_session_state = fields.Char(compute='_compute_current_session', search='_search_current_session_state')
You don't need to specify _compute_current_session again

2017-09-20 11:35 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +        value_ids = map(lambda x: x.state == value and x.user_id.id or -1, self.env["pos.session"].search([]))
Use domain in ``search`` instead of filtering it in python

2017-09-20 11:35 UTC, yelizariev commented on pos_multi_session_restaurant/README.rst
>  FIXME: there is issue with floor real-time synchronization, to synchronize tables after modifying them it is mandatory to refresh all POSes pages, also deleting a table with open order on it leads to
Fix format. FIXME has to be on a new line (paragraph). See how it's formatted now:  https://github.com/KolushovAlexandr/pos-addons/blob/5163a688f6c61f88e809d2beeb9d47b07ec28fd2/pos_multi_session_restaurant/README.rst

2017-09-20 11:35 UTC, yelizariev commented on pos_multi_session/README.rst
> +POSes are able to work without synchronization, like without the module. Different in behavior: each new order is immediately given a number.
Incorrect statement: ``Different in behavior: each new order is immediately given a number.``

2017-09-21 07:52 UTC, yelizariev requested changes

2017-09-21 07:52 UTC, yelizariev commented on pos_multi_session/multi_session_view.xml
> +                            <field name="pos_ids" widget="many2many_tags" string="POSes in Multi-session" domain="[('current_session_state', '!=', 'opened')]"/>
Avoid to use string in View. Use fields defenition in python instead

2017-09-21 07:52 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +//            }
remove commented code

2017-09-21 07:52 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                if (!this.config.multi_session_id){
How ``this.multi_session`` may be set without ``this.config.multi_session_id``?

2017-09-21 07:52 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            this.models.splice(11, 0, ms_floor_model);
What is ``11``?

2017-09-21 07:52 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            this.models.splice(this.models.lastIndexOf(ms_floor_model) + 1, 1);
Why you take it out here?

2017-09-21 08:44 UTC, KolushovAlexandr commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            this.models.splice(this.models.lastIndexOf(ms_floor_model) + 1, 1);
i moved it forward in order to on that line (before call the super) it would be uploaded and it may be used to floor definition. Super defines floors from pos.config only

2017-09-21 10:50 UTC, yelizariev requested changes

2017-09-21 10:50 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            var ms_floor_model = _.find(this.models, function(model){ return model.model === 'pos.multi_session'; });
bad name for variable. It doesn't have floor model

2017-09-21 10:50 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            this.models.splice(this.models.lastIndexOf(ms_floor_model), 1);
Why don't create model here and add

2017-09-24 13:01 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    pos_ids = fields.One2many('pos.config', 'multi_session_id', string='POSes in Multi-session', ondelete="restrict")
Why do you change ``ondelete``?

2017-09-24 13:01 UTC, yelizariev commented on pos_multi_session/multi_session_view.xml
> +                            <field name="pos_ids" widget="many2many_tags" domain="[('current_session_state', '!=', 'opened')]" options="{'not_delete': True}"/>
why ``not_delete``?

2017-09-24 13:01 UTC, yelizariev commented on pos_multi_session_restaurant/models/pos_multi_session_restaurant_models.py
> +                                 ondelete="restrict")
Why do you change ``ondelete``?

2017-09-24 13:01 UTC, yelizariev commented on pos_multi_session_restaurant/models/pos_multi_session_restaurant_models.py
> +    ms_floor_ids = fields.Many2many(related='multi_session_id.floor_ids', ondelete="restrict")
Why do you change ``ondelete``?

2017-09-24 13:16 UTC, yelizariev commented on pos_multi_session/multi_session_view.xml
> +                            <field name="pos_ids" widget="many2many_tags" domain="[('current_session_state', '!=', 'opened')]" options="{'not_delete': True}"/>
ok, I got it: it allows to don't remove POS record, when you remove it from one2many field (pos_ids in this case)

2017-09-26 10:39 UTC, yelizariev requested changes

2017-09-26 10:39 UTC, yelizariev commented on pos_multi_session/tests/test_test.py
> +        poses_with_opened_sessions = map(lambda x: x.id, poses_with_opened_sessions)
you can use ``poses_with_opened_sessions.ids``

2017-09-27 11:13 UTC, merged