10.0 pos ms
itpp-labs/pos-addons pull request #387
Opened 2017-09-07 12:53 UTC by KolushovAlexandr

2017-09-07 14:31 UTC, yelizariev requested changes

2017-09-07 14:31 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
>                      this.send({action: 'remove_order', data: data});
call super instead of duplicating code

2017-09-07 14:31 UTC, yelizariev commented on pos_multi_session/views.xml
> +                            <field name="multi_session_id" attrs="{'readonly':[('current_session_state', '=', 'opened')]}"/>
Add a text note : "You need to close current session to set Multi-session parameter". Show it only:
* in edit mode
* AND if current_session_state==opened

2017-09-07 14:31 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.pos.config.multi_session_id){
prevent to call this function instead of checking MS here

2017-09-07 14:31 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.pos.config.multi_session_id){
this function is already not called when MS is false

2017-09-07 14:31 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.pos.config.multi_session_id){
this function is already not called when MS is false

2017-09-07 14:31 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                    }
this function is already not called when MS is false

2017-09-08 07:31 UTC, KolushovAlexandr commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                    }
@yelizariev  These lines prevent the error:
TypeError: multi_session_update() takes exactly 3 arguments (2 given)
it is called.

2017-09-08 07:34 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.pos.config.multi_session_id){
@yelizariev  TypeError: multi_session_update() takes exactly 3 arguments (2 given) - without it

2017-09-08 08:10 UTC, KolushovAlexandr commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
>                      this.send({action: 'remove_order', data: data});
on the moment of a call of the super and a line after, pos.config haven't been uploaded yet and equals to null

2017-09-08 08:20 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (!this.pos.config.multi_session_id){
moved it to ms_check()

2017-09-08 13:01 UTC, yelizariev requested changes

2017-09-08 13:01 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                self.add_channel(channel_name, callback, self);
ok

2017-09-08 13:01 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                        this.send({action: 'remove_order', data: data});
Call super please

2017-09-11 11:05 UTC, merged