[FIX] some errors for compatibility pos_multi_session and pos_order_cancel
itpp-labs/pos-addons pull request #397
Opened 2017-09-19 12:21 UTC by GabbasovDinar

TODO: Update changelog in pos_multi_session and pos_multi_session_restaurant

2017-09-19 13:07 UTC, yelizariev requested changes

2017-09-19 13:07 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +        get_user_id: function() {
YOu can probably use function existing method get_cachier

2017-09-19 13:07 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +        apply_ms_data: function(data) {
add comment what is the function

2017-09-19 13:07 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +        */
use reference to pos_multi_session instead of copy-pasting comment

2017-09-19 13:07 UTC, yelizariev commented on pos_order_cancel/static/src/js/widgets.js
> +                return false;
When order may be undefined?

2017-09-19 13:07 UTC, yelizariev commented on pos_order_cancel_restaurant/static/src/js/widgets.js
> +                return false;
probably imposible case

2017-09-20 06:59 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +            this.trigger('change:sync');
add comment what this trigger is

2017-09-22 12:17 UTC, yelizariev requested changes

2017-09-22 12:17 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +            line.cancelled_line = this.canceled_lines.find(function(exist_line) {
You shall not search it if you just created and added it

2017-09-22 14:27 UTC, yelizariev reviewed
I doubt about this updates. Please check

2017-09-22 14:27 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +                var index = this.canceled_lines.indexOf([0, 0, line.cancelled_line]);
Are you sure that it works? I may create new link and try to search new link which is obviously not presented in the array.

More safe way to to search by [2] param directly like you below:


```
+                var cancelled_line = this.order.canceled_lines.find(function(line) {
 +                    return line[2].id === data.cancelled_line.id;
 +                });
```

2017-09-22 14:27 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
> +                }
Something wrong here. Don't you should replace local variables with ``data.cancelled_line``?

2017-09-25 13:13 UTC, GabbasovDinar commented on pos_order_cancel/static/src/js/models.js
> +                }
@yelizariev here I create a link to order.cancelled_lines

2017-09-26 10:27 UTC, yelizariev requested changes

2017-09-26 10:27 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
>                  this.canceled_lines.splice(index, 1);
Try to use ``indexBy_`` to don't search line twice

2017-09-26 11:04 UTC, yelizariev commented on pos_order_cancel/static/src/js/models.js
>                  this.canceled_lines.splice(index, 1);
I said wrong, you need to use ``filter``

2017-09-26 11:11 UTC, yelizariev approved these changes

2017-09-26 16:50 UTC, ilmir-k approved these changes
Approved

2017-09-27 10:03 UTC, merged