10.0 pos multi session sync
itpp-labs/pos-addons pull request #412
Opened 2017-09-28 08:56 UTC by KolushovAlexandr

2017-09-28 09:19 UTC, yelizariev requested changes

2017-09-28 09:19 UTC, yelizariev commented on pos_longpolling/models/pos_longpolling_models.py
> +    longpolling_enabled = fields.Boolean('Longpolling in use', default=True)
rename to 
 autostart_longpolling = fields.Boolean('Autostart longpolling', default=True, help='When switched off longpoling will start only when other module start it')

2017-09-28 09:19 UTC, yelizariev commented on pos_longpolling/static/src/js/pos_longpolling.js
> +            session.rpc(serv_adr + '/longpolling/poll', data, {shadow : true}).then(function(result) {
use comment to mark updated code from copy-pasted

2017-09-28 09:19 UTC, yelizariev commented on pos_multi_session/controllers/pos_multi_session.py
> +    @odoo.http.route('/pos_multi_session_sync/update', type="json", auth="public")
controller must be moved to new module

2017-09-28 09:19 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    sync_server = fields.Char('Longpolling Server Address', default='')
It's not a longpolling server only

2017-09-28 09:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                session.longpolling_server = self.config.sync_server;
Why pos_longpolling cannot use just ``config.sync_server`` 
Why do you copy it to ``session``?

2017-09-28 10:41 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                session.longpolling_server = self.config.sync_server;
@yelizariev  because there were some problems with access to pos.config via models.PosModel.  
web.session is used for making a request to a server, so i decided to use it also for transfer data from pos.config to the longpolling module.

2017-09-30 13:19 UTC, yelizariev requested changes

2017-09-30 13:19 UTC, yelizariev commented on pos_longpolling/static/src/js/pos_longpolling.js
> +        remove_channel_callback: function(channel_name) {
Rename to ``remove_channel`` bacause it removes all callbacks

2017-09-30 13:19 UTC, yelizariev commented on pos_longpolling/static/src/js/pos_longpolling.js
> +        init_channel: function(channel_name){
Rename to ```activate_channel``

2017-09-30 13:19 UTC, yelizariev commented on pos_longpolling/static/src/js/pos_longpolling.js
> +                            console.log('POS LONGPOLLING', self.pos.config.name, channel[1], JSON.stringify(message));
print Bus name too (it's 'DEFAULT' or the same as key in add_bus)

2017-09-30 13:19 UTC, yelizariev commented on pos_longpolling/static/src/js/pos_longpolling.js
> +            //new added lines for modifying url
don't need this comment here

2017-09-30 13:19 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    sync_server_secondary = fields.Char(related='multi_session_id.sync_server_secondary')
remove sync_server_secondary

2017-09-30 13:19 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    sync_server_secondary = fields.Char('Server Address', default='')
remove sync_server_secondary

2017-09-30 13:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    self.add_bus('default', '', channel_name);
Rename default to sync_server

2017-09-30 13:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.pos.bus.longpolling_connection.on("change:poll_connection", function(status){
this.pos.bus must be always use for connection to current server

2017-09-30 13:19 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    self.pos.bus.longpolling_connection.network_is_off();
this.pos.bus must be always use for connection to current server

2017-09-30 13:23 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                session.longpolling_server = self.config.sync_server;
You have to fix the problems and don't use ``session``

2017-09-30 13:24 UTC, yelizariev commented
* [ ] don't use session
* [ ] remove "secondary" stuff

2017-09-30 14:03 UTC, merged