[10.0][ADD] pos_disable_payment: new option 'Allow refunds'
itpp-labs/pos-addons pull request #436
Opened 2017-10-11 11:09 UTC by ilmir-k

[ADD] pos_disable_payment: new option 'Allow refunds'

2017-10-11 12:09 UTC, ilmir-k commented
@yelizariev review it please

2017-10-13 06:12 UTC, yelizariev commented
Basically, you need to add test for new feature:

* disable refunds
* load POS
* check that Refund button is not visible

2017-10-20 09:43 UTC, yelizariev commented
Tests don't work.
Also, there there is not check that Refund button is not visible

2017-10-20 09:44 UTC, yelizariev commented
You can update settings via python, no need tour for this

2017-10-20 09:51 UTC, yelizariev commented
.numpad-minus[style="visibility: hidden;"]

2017-10-29 08:19 UTC, yelizariev requested changes
Tests are not passed in travis

2017-10-29 08:19 UTC, yelizariev commented on pos_disable_payment/static/src/js/tour.js
> +        trigger: '.product-list .product',
This step cannot be done when pos_restaurant is installed. You need to add extra step which works both with restaurant and without one, e.g.

{
        content: "Swicth to table or make dummy action",
        trigger: '.table, .neworder-button:not(.oe_invisible .neworder-button)',
    }

2017-10-30 06:23 UTC, yelizariev commented
Fix lints
don't override commits and add new ones intead

2017-10-30 06:28 UTC, yelizariev commented
tests are not passed

2017-10-30 08:45 UTC, yelizariev requested changes

2017-10-30 08:45 UTC, yelizariev commented on pos_disable_payment/static/src/js/tour.js
> +        position: "bottom"
```
       content: _t("Hidden"),
        trigger: '.pads',
       run: function(){
// check that the button is hidden
}
```

2017-10-31 06:54 UTC, yelizariev requested changes
remove ``_t`` from test tour -- we don't want to see those phrases in translations files

2017-10-31 09:02 UTC, ilmir-k commented
it seems that travis has broken

2017-10-31 10:01 UTC, yelizariev commented
2017-10-31 09:50:10,462 5497 ERROR openerp_test odoo.tests.common: phantomjs: error The button is not hidden

2017-11-01 11:47 UTC, yelizariev approved these changes

2017-11-01 11:47 UTC, merged