[PORT] pos_restaurant_base from 10.0 to 11.0
itpp-labs/pos-addons pull request #470
Opened 2017-11-02 09:41 UTC by GabbasovDinar

2017-11-02 10:54 UTC, yelizariev approved these changes
code updates (without running app) is checked

2017-11-02 14:15 UTC, yelizariev requested changes

2017-11-02 14:15 UTC, yelizariev commented on pos_printer_network/static/src/js/network_printer.js
> +    var mixins = requere("web.mixins");
requere :grimacing:

2017-11-03 05:25 UTC, GabbasovDinar commented on pos_printer_network/static/src/js/network_printer.js
> +    var mixins = requere("web.mixins");
@yelizariev ooops

2017-11-09 10:14 UTC, merged