[11.0][PORT] from 10.0 to 11.0 (pos_category_multi)
itpp-labs/pos-addons pull request #488
Opened 2017-11-16 12:50 UTC by GabbasovDinar

2017-11-17 12:13 UTC, yelizariev commented
- [ ] fix lints
```

pos_category_multi/static/src/js/db.js:29: [W7903(javascript-lint), ] Expected '===' and instead saw '=='. [Error/eqeqeq]
pos_category_multi/static/src/js/db.js:59: [W7903(javascript-lint), ] Unexpected use of undefined. [Error/no-undefined]
pos_category_multi/static/src/js/db.js:73: [W7903(javascript-lint), ] Unexpected use of undefined. [Error/no-undefined]
```

2017-11-17 12:15 UTC, yelizariev requested changes

2017-11-17 12:15 UTC, yelizariev commented on pos_category_multi/static/src/js/tour.js
> +    }]);
add step to wait finish POS loading

2017-11-23 09:24 UTC, ilmir-k approved these changes

2017-11-23 09:39 UTC, merged