[11.0][PORT] pos_product_lot, product_lot
itpp-labs/pos-addons pull request #522
Opened 2017-12-07 06:03 UTC by GabbasovDinar

2017-12-14 08:03 UTC, yelizariev requested changes
Add more tests or create an issue with the scenarios (one issue per each module)

2017-12-14 08:03 UTC, yelizariev commented on pos_product_lot/static/src/js/tour.js
> +        }
Add more steps according to workflow

2017-12-14 08:03 UTC, yelizariev commented on pos_product_available/static/src/js/tour.js
> +        }
Add more tests: 
* Buy products
* Check that quantity is decreased

2018-02-07 12:00 UTC, yelizariev commented
@Railia check that new tours are enough to test workflow

2018-02-07 12:02 UTC, yelizariev requested changes

2018-02-07 12:02 UTC, yelizariev commented on pos_product_lot/static/src/js/tour.js
> +        trigger: '.product .not-available:contains("-1")',
Test that amount of unpacked products were increased

2018-02-21 07:46 UTC, Railia commented on pos_product_lot/static/src/js/tour.js
> +        trigger: '.product .not-available:contains("-1")',
@GabbasovDinar Amount of unpacked products weren't increased. Quantity on hand shows negative value (should be positive). Forecasted value isn't equal On hand value.

2018-09-20 06:45 UTC, yelizariev commented
Too much conflicts

2018-12-05 08:26 UTC, GabbasovDinar commented
need a new PR with fixes

2018-12-05 08:26 UTC, closed without merging