[FIX] floors undefined error
itpp-labs/pos-addons pull request #536
Opened 2017-12-18 08:43 UTC by GabbasovDinar

2017-12-18 12:33 UTC, yelizariev requested changes

2017-12-18 12:33 UTC, yelizariev commented on pos_mobile/static/src/js/gui.js
> +                $('.paymentlines-container').css({height: height - paymentmethods - 750});
Can this number 760 be computed?

2017-12-18 12:33 UTC, yelizariev commented on pos_mobile_restaurant/static/src/js/chrome.js
> +                this.pos.floors.forEach(function(floor, index){
don't use forEach
![wrong](https://user-images.githubusercontent.com/186131/34106285-77fa411a-e419-11e7-805d-9133de9b5b05.png)

2017-12-18 12:37 UTC, GabbasovDinar commented on pos_mobile/static/src/js/gui.js
> +                $('.paymentlines-container').css({height: height - paymentmethods - 750});
@yelizariev it's fixed size for numpad

2017-12-19 11:29 UTC, yelizariev commented on pos_mobile/static/src/js/gui.js
> +                $('.paymentlines-container').css({height: height - paymentmethods - 750});
Add comment what 750 is (how to compute it) or make it computable

2017-12-21 11:09 UTC, yelizariev requested changes

2017-12-21 11:09 UTC, yelizariev commented on pos_mobile_restaurant/static/src/js/floors.js
> +         the scrolling when touch a table.
I don't understand

2017-12-21 11:09 UTC, yelizariev commented on pos_mobile_restaurant/static/src/js/floors.js
> +                this.$el.off('dragend');
Put your comment inside ``if`` block

2017-12-21 13:05 UTC, yelizariev approved these changes
code is reviewed

2017-12-21 13:47 UTC, ilmir-k approved these changes
:+1:

2017-12-21 13:51 UTC, merged