[REF] refactoring code
itpp-labs/pos-addons pull request #541
Opened 2017-12-21 14:13 UTC by GabbasovDinar

2017-12-21 15:20 UTC, yelizariev requested changes

2017-12-21 15:20 UTC, yelizariev commented on pos_order_note/static/src/js/order_note.js
> +    });
Use ``load_fields`` instead

2017-12-22 05:35 UTC, yelizariev approved these changes
code is reviewed

2017-12-22 08:33 UTC, ilmir-k approved these changes
:+1:

2017-12-22 08:34 UTC, merged