10.0 pos debt notebook journal
itpp-labs/pos-addons pull request #544
Opened 2017-12-25 11:52 UTC by KolushovAlexandr

2017-12-26 09:12 UTC, yelizariev requested changes

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    journal_ID = fields.Integer(string='Appropriate journal id')
Many2one

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/report/pos_debt_report.py
> +    journal_ids = fields.Many2many('account.journal', string='Journals', readonly=True)
Many2one

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    categories_ids = fields.Many2one('product.category', string='Product categories',
Many2many

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    account_ids = fields.One2many('res.partner.account', 'account_journal')
remove

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        return float(debt_limit)
This method is not required. Set zero by default always

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        'res.partner', string='Account owner')
remove class

2017-12-26 09:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        help='Special credits for inner purchases')
remove field

2017-12-26 09:22 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        help='Special credits for inner purchases')
Rename to credit_balance_ids

2017-12-26 09:23 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    _name = 'res.partner.account'
rename to res.partner.credit_balance

2017-12-26 09:36 UTC, yelizariev requested changes

2017-12-26 09:36 UTC, yelizariev commented on pos_debt_notebook/report/pos_debt_report.py
> +    journal_ids = fields.Many2one('account.journal', string='Journals', readonly=True)
Many2one fields has to be ended with **_id**

2017-12-26 09:44 UTC, yelizariev commented
base branch is updated

2017-12-26 17:51 UTC, yelizariev requested changes

2017-12-26 17:51 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                <field string="Debts/Credits" name="pos_order_count" widget="statinfo"/>
What is pos_order_count? Why it's here?

2017-12-26 17:58 UTC, yelizariev requested changes

2017-12-26 17:58 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                context="{'search_default_partner_id': active_id,'default_partner_id': active_id}"
Records  must be grouped by journal right after clicking the button. Add appropriate context

2017-12-27 08:45 UTC, yelizariev requested changes

2017-12-27 08:45 UTC, yelizariev commented on pos_debt_notebook/views/pos_debt_report_view.xml
> +            <field name="context">{'group_by':'journal_id'}</field>
update context in smart button instead

2017-12-27 12:00 UTC, yelizariev commented
```
 File "/mnt/odoo-extra/runbot/static/build/12498-544-da5777/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12498-544-da5777/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: pos_debt_notebook.action_report_pos_debt_all" while parsing /mnt/odoo-extra/runbot/static/build/12498-544-da5777/odoo/addons/pos_debt_notebook/views.xml:7, near
<record id="view_partner_form_debt" model="ir.ui.view">
    <field name="name">res.partner.form.debt</field>
    <field name="model">res.partner</field>
    <field name="inherit_id" ref="point_of_sale.view_partner_property_form"/>
    <field name="arch" type="xml">
        <data><xpath expr="//field[@name='barcode']" position="after">
            <field name="debt_type" invisible="1"/>
            <field name="debt" attrs="{'invisible': [('debt_type', '!=', 'debt')]}"/>
            <field name="credit_balance" attrs="{'invisible': [('debt_type', '!=', 'credit')]}"/>
            <field name="debt_company" attrs="{'invisible': ['|',('debt_type', '!=', 'debt'),('is_company', '=', False)]}"/>
            <field name="credit_balance_company" attrs="{'invisible': ['|',('debt_type', '!=', 'credit'),('is_company', '=', False)]}"/>
        </xpath>
        <xpath expr="//button[@class='oe_stat_button']" position="after">
            <button class="oe_stat_button" type="action" name="%(pos_debt_notebook.action_report_pos_debt_all)d" context="{'group_by':'journal_id'}" attrs="{'invisible': [('customer', '=', False)]}" icon="fa-money">
                <div class="o_form_field o_stat_info">
                    <span class="o_stat_text">Debts/Credits</span>
                </div>
            </button>
        </xpath>
    </data></field>
```

2017-12-27 13:03 UTC, yelizariev requested changes

2017-12-27 13:03 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                attrs="{'invisible': [('customer', '=', False)]}"
remove this condition

2017-12-27 13:05 UTC, yelizariev requested changes

2017-12-27 13:05 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                    <span class="o_stat_text">Debts/Credits</span>
It must show total debts (or Credit depending on settings -- add second button and make visible only one)

2017-12-28 08:10 UTC, yelizariev requested changes

2017-12-28 08:10 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                    <span attrs="{'invisible': [('debt_type', '=', 'credit')]}" class="o_stat_text">Credits </span>
Label must be before value

2017-12-28 08:10 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                    <span attrs="{'invisible': [('debt_type', '=', 'credit')]}" class="o_stat_text">Credits </span>
Also, change label color depending on credit sign

2017-12-28 08:37 UTC, yelizariev requested changes

2017-12-28 08:37 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                    <span attrs="{'invisible': [('debt_type', '=', 'credit')]}" class="o_stat_text text-success">Credits </span>
Color must depend on balance, not on debt_type

2017-12-28 08:39 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                    <span attrs="{'invisible': [('debt_type', '=', 'credit')]}" class="o_stat_text text-success">Credits </span>
Also, make bold font

2017-12-28 08:39 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +                    <span attrs="{'invisible': [('debt_type', '=', 'credit')]}" class="o_stat_text text-success">Credits </span>
(the  same as in Invoiced)

2018-01-10 09:03 UTC, yelizariev requested changes

2018-01-10 09:03 UTC, yelizariev commented on pos_debt_notebook/wizard/pos_credit_invoices.py
> +        domain="[('credit_product', '=', partner_id)]",
WHAT?

2018-01-10 09:03 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +            <field name="credits_via_discount"/>
New fields must be hidden if journal is not debt

2018-01-10 09:03 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        help='The partner is not allowed to have a debt more than this value')
The partner -> Partners are not allowed ...

2018-01-10 09:03 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    pos_cash_out = fields.Boolean(string='Allow to cash out these credits', default=True)
pos_cash_out = fields.Boolean(string='Allow cash out credits', default=False, help='Partner can exchange credits to cash in POS')

2018-01-10 09:03 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                           'all categories if length is zero')
Fix help sentence. Use comma, point, whatever or change structure of the statement.

Product categories that may be paid with this type of credits all categories if length is zero

2018-01-19 09:33 UTC, yelizariev requested changes
You must to find another solution for render list problem

2018-01-19 09:33 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                    this.trigger('updateDebtHistory', partner_ids);
You must always trigger it

2018-01-24 10:56 UTC, stfl commented
Hi. can you please post the runbot link. thanks.

2018-01-24 11:38 UTC, KolushovAlexandr commented
@stfl http://13012-544-ee24f6-base.runbot.it-projects.info

2018-01-26 15:55 UTC, yelizariev requested changes

2018-01-26 15:55 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        default=False, string='Discount method',
It sounds like "Method of Discount". It should be something like
```
string="Zero transactions on credit payments"
help='Discount the order (mostly 100%) when user pay via this type of credits')
```
String could be just ``Zero transactions on payments`` or ``Zero payments`` if you put this field to "Credits" group in the form

2018-01-26 15:55 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            entry.balance = update['balance']
Why you set ``balance``  again after creation?

2018-01-26 15:55 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        for payments in pos_order['statement_ids']:
it should be singular I guess: ``payment``

2018-01-26 15:55 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        map(lambda p: self.env['pos.credit.update'].create(p), credit_updates)
Why you create records again?

2018-01-26 15:57 UTC, yelizariev commented on pos_debt_notebook/models.py
> +from copy import deepcopy
unused

2018-01-26 15:59 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            is_restrictions = _.filter(paymentlines, function(pl){
Don't use name ``is_restrictions`` for non-boolean fields

2018-01-26 16:18 UTC, yelizariev commented
- [ ] Fix lints 


`2018-01-26 15:35:12,473 10042 WARNING 13105-544-8b154f-all odoo.modules.loading: The model pos.debt.reward has no access rules, consider adding one. E.g. access_pos_debt_reward,access_pos_debt_reward,model_pos_debt_reward,,1,0,0,0
`

2018-01-30 07:25 UTC, yelizariev commented
- [ ] Fix lints

```
base_attendance/static/src/js/greeting_message.js:56: [W7903(javascript-lint), ] Expected an assignment or function call and instead saw an expression. [Error/no-unused-expressions]
base_attendance/static/src/js/kiosk_mode.js:24: [W7903(javascript-lint), ] Expected an assignment or function call and instead saw an expression. [Error/no-unused-expressions]
base_attendance/security/hr_attendance_security.xml:21: [W7909(redundant-modulename-xml), ]  Redundant name module reference in xml_ids "group_hr_attendance_manager".
base_attendance/security/hr_attendance_security.xml:25: [W7909(redundant-modulename-xml), ]  Redundant name module reference in xml_ids "group_hr_attendance_user".
```

2018-01-30 07:40 UTC, yelizariev commented on base_attendance/README.rst
> + HR Partners Attendance
- [ ] Remove  reference to HR in module name. 

- [ ] Add to README that module is copy-pasted hr_attendance and modifed to work with res.partner records

2018-01-30 07:41 UTC, yelizariev commented on base_attendance/__manifest__.py
> +    "category": "Human Resources",
Extra Tools

2018-01-30 07:54 UTC, yelizariev requested changes
- [ ] Be sure, that you install it only when demo is true in ``ir.module.module``
- [ ] Create records ``ir.model.data`` to clean up database in case of module uninstallation

2018-01-30 07:54 UTC, yelizariev commented on pos_debt_notebook/data/demo.xml
> +</openerp>
Demo journals must be created in ``init_debt_journal``, because it breaks installation.


```

2018-01-29 14:13:54,074 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading point_of_sale/data/point_of_sale_demo.xml
2018-01-29 14:14:10,576 13562 INFO 13128-544-2a8577-base odoo.modules.registry: module pos_debt_notebook: creating or updating database tables
2018-01-29 14:14:12,283 13562 INFO 13128-544-2a8577-base odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
2018-01-29 14:14:12,508 13562 INFO 13128-544-2a8577-base odoo.models: Storing computed values of pos.order fields product_list
2018-01-29 14:14:12,604 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/data/product.xml
2018-01-29 14:14:13,127 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/views/pos_debt_report_view.xml
2018-01-29 14:14:13,468 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/views.xml
2018-01-29 14:14:14,309 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/views/pos_credit_update.xml
2018-01-29 14:14:14,594 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/wizard/pos_credit_invoices_views.xml
2018-01-29 14:14:14,717 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/data.xml
2018-01-29 14:14:14,796 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/security/ir.model.access.csv
2018-01-29 14:14:14,904 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading pos_debt_notebook/data/demo.xml
2018-01-29 14:14:15,974 13562 INFO 13128-544-2a8577-base odoo.modules.loading: 36 modules loaded in 252.09s, 232 queries
2018-01-29 14:14:15,984 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading 39 modules...
2018-01-29 14:14:16,229 13562 INFO 13128-544-2a8577-base odoo.modules.registry: module account_check_printing: creating or updating database tables
2018-01-29 14:14:16,886 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading account_check_printing/data/account_check_printing_data.xml
2018-01-29 14:14:16,983 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading account_check_printing/views/account_journal_views.xml
2018-01-29 14:14:17,185 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading account_check_printing/views/account_payment_views.xml
2018-01-29 14:14:17,556 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading account_check_printing/wizard/print_prenumbered_checks_views.xml
2018-01-29 14:14:18,326 13562 INFO 13128-544-2a8577-base odoo.modules.registry: module l10n_generic_coa: creating or updating database tables
2018-01-29 14:14:18,431 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading l10n_generic_coa/data/l10n_generic_coa_chart_data.xml
2018-01-29 14:14:18,740 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading l10n_generic_coa/data/account_chart_template_data.yml
2018-01-29 14:14:18,819 13562 INFO 13128-544-2a8577-base odoo.addons.account.models.chart_template: Could not install chart of account since some accounts already exists for the company ((1,))
2018-01-29 14:14:18,819 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading l10n_generic_coa/../account/demo/account_bank_statement.yml
2018-01-29 14:14:18,831 13562 INFO 13128-544-2a8577-base odoo.modules.loading: loading l10n_generic_coa/../account/demo/account_invoice_demo.yml
2018-01-29 14:14:19,124 13562 ERROR 13128-544-2a8577-base odoo.tools.yaml_import: (u'Cannot find a chart of accounts for this company, You should configure it. \nPlease go to Account Configuration.', 217, u'Go to the configuration panel')
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/tools/yaml_import.py", line 880, in process
    self._process_node(node)
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/tools/yaml_import.py", line 891, in _process_node
    self.process_record(node)
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/tools/yaml_import.py", line 324, in process_record
    record_dict = self._create_record(model, fields, view_info, default=default, context=context)
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/tools/yaml_import.py", line 477, in _create_record
    result = recs.onchange(dict(record_dict, **parent_values), field_name, onchange_spec)
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/models.py", line 5494, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/models.py", line 5392, in _onchange_eval
    method_res = method(self)
  File "/mnt/odoo-extra/runbot/static/build/13128-544-2a8577/odoo/addons/account/models/account_invoice.py", line 481, in _onchange_partner_id
    raise RedirectWarning(msg, action.id, _('Go to the configuration panel'))
RedirectWarning: (u'Cannot find a chart of accounts for this company, You should configure it. \nPlease go to Account Configuration.', 217, u'Go to the configuration panel')

```

2018-01-30 10:25 UTC, KolushovAlexandr commented
@yelizariev "base_attendance/static/src/js/greeting_message.js:56: [W7903(javascript-lint), ] Expected an assignment or function call and instead saw an expression. [Error/no-unused-expressions]
" Idk how to fix it, https://eslint.org/docs/rules/no-unused-expressions here it is shown as a correct example. Maybe i've missed something

2018-01-30 11:28 UTC, yelizariev commented
I activated option allowTernary

2018-01-31 12:35 UTC, yelizariev requested changes
Fix unit tests instead of removing them

2018-01-31 12:35 UTC, yelizariev commented on base_attendance/models/hr_attendance.py
> +        super(HrAttendance, self).copy()
Why?

2018-01-31 12:35 UTC, yelizariev commented on base_attendance/security/hr_attendance_security.xml
> +        <field name="implied_ids" eval="[(4, ref('hr.group_hr_user')),(4, ref('hr.group_hr_attendance'))]"/>
It should new groups, rather than one from module ``hr``, which might not be installed at all

2018-01-31 12:35 UTC, yelizariev commented on base_attendance/security/hr_attendance_security.xml
> +        <field name="implied_ids" eval="[(4, ref('base_attendance.group_hr_attendance_user')),(4, ref('hr.group_hr_attendance'))]"/>
the same

2018-01-31 12:35 UTC, yelizariev commented on base_attendance/static/src/js/kiosk_mode.js
> +        var init_super = this._super;
Add a comment why we need to put in a variable

2018-01-31 12:35 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            if not journal_obj.search([('code', '=', 'XCRD')]):
YOu can put check for existing journal in ``create_journal``

2018-01-31 12:35 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            if not journal_obj.search([('code', '=', 'DCRD')]):
the same

2018-01-31 12:35 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            if not journal_obj.search([('code', '=', 'FCRD')]):
the same

2018-01-31 12:35 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            debt_journal = journal_obj.search([('code', '=', 'TDEBT'),
You can use return value for debt_journal instead of search the journal

2018-01-31 12:38 UTC, KolushovAlexandr commented on base_attendance/models/hr_attendance.py
> +        super(HrAttendance, self).copy()
it was a LINT error

2018-01-31 12:47 UTC, KolushovAlexandr commented on base_attendance/security/hr_attendance_security.xml
> +        <field name="implied_ids" eval="[(4, ref('hr.group_hr_user')),(4, ref('hr.group_hr_attendance'))]"/>
base_attendance, like the hr_attendance are dependent on hr

2018-01-31 12:51 UTC, KolushovAlexandr commented on base_attendance/models/hr_attendance.py
> +        super(HrAttendance, self).copy()
Missing `super` call in "copy" method.

2018-01-31 13:05 UTC, KolushovAlexandr commented on base_attendance/security/hr_attendance_security.xml
> +        <field name="implied_ids" eval="[(4, ref('hr.group_hr_user')),(4, ref('hr.group_hr_attendance'))]"/>
but, i think, its possible to unlink this dependency

2018-02-01 11:25 UTC, yelizariev commented on base_attendance/models/hr_attendance.py
> +        super(HrAttendance, self).copy()
@KolushovAlexandr Add it to comments in code

2018-02-01 11:33 UTC, yelizariev requested changes
Small styling issues

2018-02-01 11:33 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            self.create_journal({'sequence_name': 'Account Default Credit Journal ',
Add new method ``create_demo_debt_journals`` and call it here -- it simplifies ``init_debt_journal`` for reading and allows to don't add indents

2018-02-01 11:33 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        if not self.env['account.journal'].search([('code', '=', vals['code'])]):
if self.env['account.journal'].search([('code', '=', vals['code'])]):
            return False

2018-02-01 11:33 UTC, yelizariev commented on base_attendance/models/res_attendance.py
> +        raise exceptions.UserError(_('You cannot duplicate an attendance.'))
add comment why we need to call copy if next line of code will revert it

2018-02-01 13:54 UTC, yelizariev requested changes
Also, fix lints 

```
base_attendance/models/res_partner.py:106:21: E128 continuation line under-indented for visual indent
pos_debt_notebook_rewards/models/models.py:3:1: F401 'odoo._' imported but unused

************* Module base_attendance.tests
base_attendance/tests/__init__.py:3: [W0403(relative-import), ] Relative import 'test_hr_attendance_constraints', should be 'base_attendance.tests.test_hr_attendance_constraints'
base_attendance/tests/__init__.py:4: [W0403(relative-import), ] Relative import 'test_hr_attendance_process', should be 'base_attendance.tests.test_hr_attendance_process'
count_errors 2
```

2018-02-01 13:54 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        allowed_category = self.env['pos.category'].search([('name', '=', 'Fruits and Vegetables')])
Use self.env.ref instead

2018-02-02 15:56 UTC, yelizariev commented
```
  File "/mnt/odoo-extra/runbot/static/build/13268-544-7d8184/odoo/addons/pos_debt_notebook/models.py", line 104, in debt_history
    r2['journal_code'] = self.env['account.journal'].search([('id', '=', r2['journal_id'][0])]).code
TypeError: 'bool' object has no attribute '__getitem__'
```

2018-02-02 16:18 UTC, yelizariev requested changes

2018-02-02 16:18 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +    _name = 'pos.debt.reward'
Rename to ``pos.credit.update.reward.type``

2018-02-02 16:18 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +    _name = 'pos.credit.update.rewards'
rename to ``pos.credit.update.reward``

2018-02-02 16:18 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +    reward_type = fields.Many2one(
many2one fields must end with _id

``reward_type_id``

2018-02-02 16:18 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +        return self.credit_update_id.switch_to_confirm()
set journal_id too

2018-02-02 16:18 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +        self.credit_update_id.balance = len(self.attendance_ids) * self.reward_type.amount
No need to make any multiplication

2018-02-02 16:18 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +        self.attendance_ids = [(6, 0, attendances.ids)]
Don't update self.attendance_ids here

2018-02-02 16:31 UTC, yelizariev requested changes

2018-02-02 16:31 UTC, yelizariev commented on pos_debt_notebook_rewards/views/reward_form.xml
> +    <menuitem id="menu_pos_credit_update_rewards" name="Reward Credit Updates" action="action_pos_credit_update_rewards" parent="base_attendance.menu_hr_attendance_manage_attendances" groups="base_at
Rename to "Attendance Rewards"

2018-02-02 16:31 UTC, yelizariev commented on base_attendance/security/res_attendance_security.xml
> +        <field name="comment">The user will gain access to the human resources attendance menu, enabling him to manage partners attendance.</field>
Wrong comment, unclear Name.

rename to ``Attendance rewards``

2018-02-02 16:45 UTC, yelizariev requested changes

2018-02-02 16:45 UTC, yelizariev commented on pos_debt_notebook_rewards/tests/test_reward.py
> +        # Sure that next reward will be for the unpaid attendance, not for the both
As requested earlier reward amount shall not depend on count of attendancees, so this comment becomes useless.

What cat test here, is that

* credit balance is updated for proper journal
* Form is auto filled with new attendance only (call corresponding onchange method and check result)

2018-02-02 16:45 UTC, yelizariev commented on pos_debt_notebook_rewards/tests/test_reward.py
> +        self.pcu_reward_model = self.env['pos.credit.update.rewards']
self.reward_model

2018-02-02 16:45 UTC, yelizariev commented on pos_debt_notebook_rewards/tests/test_reward.py
> +        self.p_debt_reward = self.env['pos.debt.reward']
self.reward_type_model

2018-02-05 08:20 UTC, KolushovAlexandr commented on pos_debt_notebook_rewards/models/models.py
> +        self.credit_update_id.balance = len(self.attendance_ids) * self.reward_type.amount
Why? If there are more than one unrewarded attendances?

2018-02-05 08:51 UTC, KolushovAlexandr commented on pos_debt_notebook_rewards/models/models.py
> +        self.credit_update_id.balance = len(self.attendance_ids) * self.reward_type.amount
resolved

2018-02-06 12:36 UTC, yelizariev requested changes

2018-02-06 12:36 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +            .search([('id', '=', reward_type_id)]).journal_id.id
Don't duplicate code

2018-02-06 12:36 UTC, yelizariev commented on base_attendance/security/res_attendance_security.xml
> +        <field name="comment">The user will gain access to the human resources attendance menu, enabling him to manage partners attendance.</field>
There is no  human resources attendance menu

2018-02-06 12:36 UTC, yelizariev commented on pos_debt_notebook_rewards/tests/test_reward.py
> +        self.assertEqual(self.test_partner.credit_balance, self.pcu_reward.balance)
There is no pcu_reward.

What you can test here, is that

* credit balance is updated for proper journal
* Form is auto-filled with new attendance only (call corresponding onchange method and check result)

2018-02-06 12:36 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +    journal_id = fields.Many2one('account.journal', string='Journal', help='journal to convert hours to credits in it')
make it required

2018-02-06 12:36 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +    name = fields.Char('Name')
make it required

2018-02-06 14:52 UTC, yelizariev commented
ttt

2018-02-06 14:53 UTC, yelizariev commented
ping

2018-02-06 15:09 UTC, KolushovAlexandr commented
What you can test here, is that

credit balance is updated for proper journal
Form is auto-filled with new attendance only (call corresponding onchange method and check result)

2018-02-06 15:32 UTC, yelizariev requested changes

2018-02-06 15:32 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    ], default='draft', required=True, track_visiblity='always')
track_visibility

2018-02-07 09:33 UTC, yelizariev requested changes

2018-02-07 09:33 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +            reward_type_id = self.reward_type_id
If reward_type_id is not changed, you don't need to change journal_id

2018-02-07 09:35 UTC, yelizariev requested changes

2018-02-07 09:35 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +            reward_type_id = self.reward_type_id.id
If reward_type_id is not changed, you don't need to change journal_id

2018-02-07 09:35 UTC, KolushovAlexandr commented on pos_debt_notebook_rewards/models/models.py
> +            reward_type_id = self.reward_type_id
@yelizariev in case of it is called from write function reward_type_id might not be in vals

2018-02-07 10:45 UTC, yelizariev requested changes

2018-02-07 10:45 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                                'debt_limit': 1000,
Set it to 1000 only in demo and 0 otherwise

2018-02-07 10:45 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +            <field name="category_ids" attrs="{'invisible': [('debt', '!=', True)]}"/>
use ``many2many_widget``

2018-02-07 10:45 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +            <field name="credits_via_discount" attrs="{'invisible': [('debt', '!=', True)]}"/>
Put all fields to new group ``Credits``

2018-02-07 10:45 UTC, yelizariev commented on pos_debt_notebook/views.xml
> +            <field name="credits_via_discount" attrs="{'invisible': [('debt', '!=', True)]}"/>
For ``credits_via_discount`` use ``string="Zero transactions"``, because word "Credits" is already in the group

2018-02-07 10:45 UTC, yelizariev commented on pos_debt_notebook/models.py
>      debt = fields.Boolean(string='Debt Payment Method')
Rename to "Credits Journal"

2018-02-07 10:45 UTC, yelizariev commented on base_attendance/security/res_attendance_security.xml
> +        <field name="comment">The user will gain access to the attendances menu, enabling him to manage partners attendance.</field>
This module doesn't provide any reward feature. Move this to appropriate module

2018-02-07 10:45 UTC, yelizariev commented on base_attendance/models/res_attendance.py
> +                result.append((attendance.id, _("%(partner_name)s from %(check_in)s to %(check_out)s") % {
Update to the following format: "3h 50m by Administrator from ... to ..."

2018-02-07 10:45 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +    note = fields.Text(default='Reward for an attendance')
Remove default here and update in _onchange_reward_type -- set to reward type name

2018-02-08 11:51 UTC, yelizariev requested changes

2018-02-08 11:51 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                                'debt_limit': 0,
It must be 1000 on demo and 0 otherwise

2018-02-08 11:51 UTC, yelizariev commented on pos_debt_notebook_rewards/views/reward_type_view.xml
> +    <menuitem id="menu_pos_credit_update_reward_type" name="Reward Types" action="action_pos_credit_update_reward_type" parent="base_attendance.menu_hr_attendance_manage_attendances" groups="base_att
Show it for Manager only

2018-02-08 12:34 UTC, yelizariev requested changes

2018-02-08 12:34 UTC, yelizariev commented on base_attendance/__manifest__.py
> +    "version": "(10.0).1.0.0",
:hankey::hankey::hankey:

2018-02-08 12:34 UTC, yelizariev commented on pos_debt_notebook/__openerp__.py
> +    'version': '(10.0).5.0.0',
:hankey::hankey::hankey:

2018-02-08 12:34 UTC, yelizariev commented on pos_debt_notebook_rewards/__manifest__.py
> +    "version": "(10.0).1.0.0",
:hankey: :hankey: :hankey:

2018-02-08 12:34 UTC, yelizariev commented on pos_debt_notebook_rewards/models/models.py
> +                                 domain="[('debt', '=', True)]")
:+1:

2018-02-08 12:41 UTC, yelizariev commented
- [ ] replace ``You cannot sell products on credit to the customer, because his max debt value will be exceeded.`` to ``You cannot sell products on credit journal <b>JOURNAL_NAME</b> to the customer because its max debt value will be exceeded.`` -- max debt is per journal and not per partner

2018-02-08 15:18 UTC, merged

2018-02-08 15:18 UTC, yelizariev commented
Thank you for your work :+1: