[DOC] update index.rst
itpp-labs/pos-addons pull request #556
Opened 2018-01-15 11:11 UTC by Railia

"Full debt button" explanation.

2018-01-15 13:46 UTC, yelizariev requested changes

2018-01-15 13:46 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +*	set Max Debt value
Shall it be one space or you want to make indent?

2018-01-15 13:46 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +*	set Max Debt value
Anyway, this feature is about to be removed. We will use Max Debt per journal

2018-01-15 13:46 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +If you click on this button, then to the amount of payment for the product will add the amount of unpaid debt.
``the amount of payment for the product`` what is it?

2018-01-15 13:46 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +If you click on this button, then to the amount of payment for the product will add the amount of unpaid debt.
``will add `` shall it be passive?

2018-01-15 13:46 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +If you click on this button, then to the amount of payment for the product will add the amount of unpaid debt.
There are two buttons *Pay Full debt*. You need to describe both of them.

2018-01-15 14:14 UTC, ilmir-k commented on pos_debt_notebook/doc/index.rst
> +If you click on this button, then to the amount of payment for the product will add the amount of unpaid debt.
more correctly:
`[Pay Full Debt] ` button is displayed and may be used when Customer has unpaid debt

2018-01-16 23:48 UTC, yelizariev requested changes

2018-01-16 23:48 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +Also this button is displayed on the payment page. If you click this button, then the amount of unpaid debt will be added to the payment amount for the product.
Can you make it more clear, that there are two usage scenario and after being nagivating to payment page you don't need to click Button again

2018-01-17 17:36 UTC, yelizariev requested changes
FIx format. It should not be in bold font
See https://github.com/it-projects-llc/pos-addons/blob/8636cdf9307cb9922b51cd47b3c0e4c063938436/pos_debt_notebook/doc/index.rst

And https://odoo-development.readthedocs.io/en/latest/dev/docs/rst-requirements.html#extra-lines

2018-01-17 17:36 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> + * At the top of the Customer's card.
Customer's form or Customer's profile, but not card

2018-01-17 17:36 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> + * If you don't use the button on the Customer's card  you can  use another Pay Full Debt button on the payment page.
It's unclear what happens when you click the button at payment page

2018-01-18 08:12 UTC, ilmir-k commented on pos_debt_notebook/doc/index.rst
> + * If you click on the button on the Customer's card then unpaid debt will be added to the payment amount for the product immediatly.
immediately

2018-01-18 08:26 UTC, ilmir-k commented
@Railia please fix all @yelizariev's requests
 

> https://odoo-development.readthedocs.io/en/latest/dev/docs/rst-requirements.html#extra-lines
>  Customer's form

2018-01-18 11:37 UTC, yelizariev requested changes

2018-01-18 11:37 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +* If you don't use the button on the Customer's form  you can  use another ``[Pay Full Debt]`` button on the payment page. If you click on the button then unpaid debt will be added to the payment amo
I don't understand what are difference between actions after clicking any of those buttons. If there are  no difference, we probably shall not repeat about two different places again

2018-01-19 10:07 UTC, yelizariev approved these changes
@ilmir-k check it too please

2018-01-19 12:08 UTC, ilmir-k approved these changes

2018-01-19 12:09 UTC, ilmir-k commented
@yelizariev it can be merged

2018-01-23 07:17 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +When you click ``[Pay Full Debt]`` button, the debt amount will be added to the payment list with negative sign. This negative amount has to be covered by normal payment (e.g. by cash). After that th
Actually, it's ``That`` https://english.stackexchange.com/questions/42306/this-vs-that

2018-01-23 07:21 UTC, merged