11.0 pos debt notebook port
itpp-labs/pos-addons pull request #557
Opened 2018-01-15 14:01 UTC by KolushovAlexandr

2018-01-18 01:53 UTC, yelizariev requested changes

2018-01-18 01:53 UTC, yelizariev commented on pos_debt_notebook/__init__.py
> +
Fix empty lines

2018-01-18 01:53 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                                'In both cases debt will be red, credit - green')
This setting is used in partner form, so it has to be global and not per POS

2018-01-18 08:30 UTC, KolushovAlexandr commented on pos_debt_notebook/models.py
> +                                                'In both cases debt will be red, credit - green')
@yelizariev in odoo 11.0 model pos.config.settings is included in pos.config, so i made the same changes. Where should they be then?

2018-01-18 09:16 UTC, KolushovAlexandr commented on pos_debt_notebook/models.py
> +                                                'In both cases debt will be red, credit - green')
@yelizariev on the partner form it works correctly, but the partner form is reachable now only after installing account_invoicing, because the debendent module account is "Core mechanisms for the accounting modules. To display the menuitems, install the module account_invoicing."

2018-01-18 11:53 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                                'In both cases debt will be red, credit - green')
Use ``res.config.settings`` for settings
Install module ``contacts`` to get partner views

2018-01-19 11:48 UTC, Railia approved these changes

2018-01-19 15:58 UTC, ilmir-k approved these changes

2018-01-19 16:00 UTC, ilmir-k commented
@yelizariev functional part has been reviewed, review the code please

2018-01-22 11:20 UTC, yelizariev approved these changes

2018-01-22 11:21 UTC, merged

2018-08-09 16:28 UTC, yelizariev commented on pos_debt_notebook/__init__.py
> +    env = api.Environment({})
WTF?