[REF] for compatitbility with pos_cache
itpp-labs/pos-addons pull request #560
Opened 2018-01-19 13:51 UTC by KolushovAlexandr

2018-01-21 18:54 UTC, yelizariev requested changes

2018-01-21 18:54 UTC, yelizariev commented on pos_product_available/static/src/js/pos.js
> +            models.load_models({
Try to load qty_available separately only when pos_cache in affect, i.e. when 'product.product' not in models list

2018-01-23 11:02 UTC, Railia approved these changes

2018-01-23 11:21 UTC, Railia requested changes
Change version in corresponding docs, files

2018-01-24 08:58 UTC, Railia approved these changes

2018-01-24 10:47 UTC, yelizariev approved these changes

2018-01-24 10:49 UTC, yelizariev requested changes

2018-01-24 10:49 UTC, yelizariev commented on pos_product_available/tests/test_quantities.py
> +@odoo.tests.common.at_install(False)
Switch to True or add a comment why it cannot be True. Consult to @GabbasovDinar if needed

2018-01-31 12:04 UTC, yelizariev approved these changes
code seems ok

2018-02-06 09:00 UTC, merged