[10.0][NEW] pos_invoice_pay module
itpp-labs/pos-addons pull request #566
Opened 2018-01-26 09:03 UTC by ilmir-k

[10.0][NEW] pos_invoice_pay module

2018-01-30 22:29 UTC, ilmir-k commented
issue for unitest: #569

2018-02-02 13:15 UTC, yelizariev commented
`phantomjs: u"null is not an object (evaluating 'order.get_paymentlines') render_paymentlines@http://127.0.0.1:8069/pos_invoice_pay/static/src/js/main.js:867`

2018-02-02 14:19 UTC, yelizariev requested changes
Clean up html and add clean templates to odoo-development if you use new template

2018-02-02 14:19 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> + 		<font size="3px">Go to <em>Sales &rarr; Sales Orders</em> menu. Create and confirm a sale order.</font>
clean up html. WHat is ``3px``?

2018-02-02 14:19 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +		<div class="alert alert-info" style="padding:8px;font-weight: 300; font-size: 20px;">
Clean up html https://odoo-development.readthedocs.io/en/latest/description/index.html.html#key-features

2018-02-02 14:19 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> + 		<font size="3px">Once you click on <span style="color: black;">Create Invoice</span> button, the corresponding invoice is created and validated automatically, and you will be redirected to POS pay
clean up html. WHat is 3px?

2018-02-02 14:19 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +      <img style="max-width: 80%" src="pay_so_screen.png"/>
Use existing classes 
https://odoo-development.readthedocs.io/en/latest/description/index.html.html#text-image

2018-02-05 19:53 UTC, ilmir-k commented
it's strangely that `--force-with-lease` didn't affect

2018-02-07 09:04 UTC, yelizariev commented
``--force-with-lease`` works exactly as it's should be

2018-02-22 04:34 UTC, blaggacao requested changes
Hi, I just had a look on the code, here is what I spotted...

This image: pos_invoice_pay/static/description/pay_invoice_screen.png Shoud there really be the invoice button available?

2018-02-22 04:34 UTC, blaggacao commented on pos_invoice_pay/models.py
> +                writeoff_acc_id = self.env['account.account'].search([('code', '=', 220000)]).id
hard coded?

2018-02-22 04:34 UTC, blaggacao commented on pos_invoice_pay/static/src/js/main.js
> +        this.models.push(
Nooo :smile: 

There is an official hook for that:

```js
// Loads openerp models at the point of sale startup.
// load_models take an array of model loader declarations.
// - The models will be loaded in the array order. 
// - If no openerp model name is provided, no server data
//   will be loaded, but the system can be used to preprocess
//   data before load.
// - loader arguments can be functions that return a dynamic
//   value. The function takes the PosModel as the first argument
//   and a temporary object that is shared by all models, and can
//   be used to store transient information between model loads.
// - There is no dependency management. The models must be loaded
//   in the right order. Newly added models are loaded at the end
//   but the after / before options can be used to load directly
//   before / after another model.
//
// models: [{
//  model: [string] the name of the openerp model to load.
//  label: [string] The label displayed during load.
//  fields: [[string]|function] the list of fields to be loaded. 
//          Empty Array / Null loads all fields.
//  order:  [[string]|function] the models will be ordered by 
//          the provided fields
//  domain: [domain|function] the domain that determines what
//          models need to be loaded. Null loads everything
//  ids:    [[id]|function] the id list of the models that must
//          be loaded. Overrides domain.
//  context: [Dict|function] the openerp context for the model read
//  condition: [function] do not load the models if it evaluates to
//             false.
//  loaded: [function(self,model)] this function is called once the 
//          models have been loaded, with the data as second argument
//          if the function returns a deferred, the next model will
//          wait until it resolves before loading.
// }]
//
// options:
//   before: [string] The model will be loaded before the named models
//           (applies to both model name and label)
//   after:  [string] The model will be loaded after the (last loaded)
//           named model. (applies to both model name and label)
//
exports.load_models = function(models,options) {
    options = options || {};
    if (!(models instanceof Array)) {
        models = [models];
    }

    var pmodels = exports.PosModel.prototype.models;
    var index = pmodels.length;
    if (options.before) {
        for (var i = 0; i < pmodels.length; i++) {
            if (    pmodels[i].model === options.before ||
                    pmodels[i].label === options.before ){
                index = i;
                break;
            }
        }
    } else if (options.after) {
        for (var i = 0; i < pmodels.length; i++) {
            if (    pmodels[i].model === options.after ||
                    pmodels[i].label === options.after ){
                index = i + 1;
            }
        }
    }
    pmodels.splice.apply(pmodels,[index,0].concat(models));
};
```

2018-02-24 01:23 UTC, yelizariev commented
@blaggacao Thank you for review!

@GabbasovDinar will work on it

@ilmir-k , can you check question with pos_invoice_pay/static/description/pay_invoice_screen.png

2018-03-01 07:12 UTC, GabbasovDinar commented on pos_invoice_pay/models.py
> +                writeoff_acc_id = self.env['pos.config'].search([]).pos_invoice_pay_writeoff_account_id.id
@yelizariev @ArtyomLosev  What happens if a query returns multiple objects? e.g. returns the pos.config(1,2,3)
I think that we will have an error

2018-03-01 13:27 UTC, yelizariev commented on pos_invoice_pay/models.py
> +                writeoff_acc_id = self.env['pos.config'].search([]).pos_invoice_pay_writeoff_account_id.id
Yes

2018-03-04 07:46 UTC, yelizariev reviewed
Not blocking from my side, but functional review is required

2018-03-27 16:35 UTC, yelizariev approved these changes
Approved as I did earlier.

2018-03-27 17:33 UTC, ilmir-k commented
@blaggacao 
> This image: pos_invoice_pay/static/description/pay_invoice_screen.png Shoud there really be the invoice button available?

I think we should leave it there, because someone might want to print invoice directly from POS payment screen rather than from backend

2018-04-04 13:35 UTC, Railia approved these changes

2018-04-04 14:18 UTC, yelizariev requested changes
Can we remove word ``Fetch`` from POS UI. Just ``Orders`` and ``Invoices``

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +	      automatically filter all SO&amp;Invoices by customer selected
Use spaces `` SO &amp; Invoices ``

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +    <h4 class="oe_slogan"><b>Fetch Sale Orders</b></h4>
If we use bold font for subsection, update it in templates: https://odoo-development.readthedocs.io/en/latest/description/index.html.html#subsection

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +    <h4 class="oe_slogan"><b>Fetch Sale Orders</b></h4>
I think subsection can be just ``Sale Orders``

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +    <h4 class="oe_slogan"><b>Fetch Invoices</b></h4>
Remove or replace word Fetch

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> + 	<font style="font-size: 120%;">Go to <em>Point of Sale &rarr; Dashboard</em> and open POS session. To see sale orders to be paid, click on <span style="color: black;">Fetch Orders</span> button</fo
Add to templates section *Reference to menu*
https://odoo-development.readthedocs.io/en/latest/description/index.html.html

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +      <img style="max-width: 80%" src="sale_order.png"/>
Can we remove this section? It's too boring for first picture

2018-04-04 14:18 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> + 	<font style="font-size: 120%;">Go to <em>Point of Sale &rarr; Dashboard</em> and open POS session. To see sale orders to be paid, click on <span style="color: black;">Fetch Orders</span> button</fo
No need to describe how to open POS. It's well-known and too boring

2018-04-06 09:30 UTC, ilmir-k commented on pos_invoice_pay/static/description/index.html
> +      <img style="max-width: 80%" src="sale_order.png"/>
I think we need to leave that. It's used for comparing, i.e. used to show invoiceable lines for SO in backend and to see how it looks in POS then

2018-04-06 10:42 UTC, ilmir-k commented on pos_invoice_pay/static/description/index.html
> + 	<font style="font-size: 120%;">Go to <em>Point of Sale &rarr; Dashboard</em> and open POS session. To see sale orders to be paid, click on <span style="color: black;">Fetch Orders</span> button</fo
Done https://github.com/it-projects-llc/odoo-development/pull/152

2018-04-06 10:42 UTC, ilmir-k commented on pos_invoice_pay/static/description/index.html
> +    <h4 class="oe_slogan"><b>Fetch Invoices</b></h4>
Removed

2018-04-06 10:42 UTC, ilmir-k commented on pos_invoice_pay/static/description/index.html
> +    <h4 class="oe_slogan"><b>Fetch Sale Orders</b></h4>
Done https://github.com/it-projects-llc/odoo-development/pull/152

2018-04-06 10:43 UTC, ilmir-k commented on pos_invoice_pay/static/description/index.html
> +	      automatically filter all SO&amp;Invoices by customer selected
Done

2018-04-06 10:44 UTC, ilmir-k commented
> Can we remove word Fetch from POS UI. Just Orders and Invoices

I renamed it as ``Sale Orders`` and ``Invoices``, because ``Orders`` may be used for POS orders history

2018-04-06 11:22 UTC, ilmir-k commented
@yelizariev you can check it

2018-04-06 12:52 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +      <img style="max-width: 80%" src="sale_order.png"/>
Move it from first position at least. E.g. after showing in POS, next slide -- picture from backend

2018-04-06 12:55 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> +      <img style="max-width: 80%" src="sale_order.png"/>
Or screentshot at the end of story -- where you have invoice

2018-04-06 12:55 UTC, yelizariev commented
First image still boring

2018-04-10 12:49 UTC, yelizariev commented on pos_invoice_pay/static/description/index.html
> + 	<font style="font-size: 120%;">The above sale order we get from backend</font>
The sale order above is gotten from backend


Sounds better?

2018-04-12 20:50 UTC, yelizariev approved these changes
New guidelines for copyrights are not applied. We can do it later

2018-04-13 08:54 UTC, ilmir-k commented on pos_invoice_pay/static/description/index.html
> + 	<font style="font-size: 120%;">The above sale order we get from backend</font>
Another variant:
``The sale order above is taken from backend``

2018-04-17 11:47 UTC, merged

2021-05-13 15:54 UTC, yelizariev commented on pos_invoice_pay/models.py
> +                'payment_method_id': 1,
Кажется кто-то пытался нас наебать