[IMP] pos_order_cancel, pos_product_category_discount and other
itpp-labs/pos-addons pull request #567
Opened 2018-01-30 07:37 UTC by GabbasovDinar

2018-02-01 13:55 UTC, ilmir-k commented
@GabbasovDinar fix lint error

2018-02-02 07:06 UTC, GabbasovDinar commented
@ilmir-k DONE

2018-02-02 15:21 UTC, yelizariev requested changes

2018-02-02 15:21 UTC, yelizariev commented on pos_multi_session_restaurant/models/res_users_model.py
> +    allow_decrease_kitchen_only = fields.Boolean('Allow change Qty for kitchen orders', default=False)
I think it should be pos_disable_payment or pos_disable_payment_restaurant

2018-02-07 12:08 UTC, yelizariev commented
@GabbasovDinar Try to move ``allow_decrease_kitchen_only`` feature to ``pos_disable_payment`` without adding the restaurant dependency. It seems to be possible on js part. At the pos.config form, you can add invisible field ``is_restaurant_installed`` and show the field in that case only

2018-02-07 12:18 UTC, yelizariev commented
@GabbasovDinar Prepare an issue with scenarios for tests

2018-02-07 12:18 UTC, yelizariev requested changes

2018-02-07 12:18 UTC, yelizariev commented on pos_disable_payment/README.rst
> +* Dinar Gabbasov <gabbasov@it-projects.info>
Replace emails to team links

2018-02-08 06:47 UTC, GabbasovDinar commented
@yelizariev You can check the improvement for pos_disable_payment

2018-02-12 09:26 UTC, ilmir-k commented on pos_order_cancel/static/src/css/pos.css
> +    margin-left: 13px;
@GabbasovDinar I think we can remove `margin-left` from here or use more less value . Also add `margin-bottom: 3px;`

2018-02-12 09:46 UTC, GabbasovDinar commented on pos_order_cancel/static/src/css/pos.css
> +    margin-left: 13px;
@ilmir-k DONE

2018-02-12 15:03 UTC, ilmir-k commented
@yelizariev your review is needed

2018-02-13 08:54 UTC, yelizariev requested changes

2018-02-13 08:54 UTC, yelizariev commented on pos_disable_payment/__openerp__.py
> +        'pos_discount'
Try without it

2018-02-13 08:54 UTC, yelizariev commented on pos_disable_payment/static/src/js/pos_disable_payment.js
> +            }
``need_check`` is not needed to be checked.

```
if (user.allow_decrease_amount or user.allow_decrease_kitchen_only) {
return true;
}
```

2018-02-13 08:57 UTC, yelizariev commented on pos_disable_payment/static/src/js/pos_disable_payment.js
> +            }
![original](https://user-images.githubusercontent.com/186131/36141226-cef2fe8e-10c5-11e8-9dc6-b3066e965b20.jpeg)

2018-02-13 08:57 UTC, yelizariev commented on pos_disable_payment/static/src/js/pos_disable_payment.js
> +            }
![original](https://user-images.githubusercontent.com/186131/36141238-d689ab66-10c5-11e8-86a8-102fdafcfdc0.jpeg)

2018-02-14 13:22 UTC, ilmir-k approved these changes
:+1:

2018-02-14 13:25 UTC, ilmir-k commented
@yelizariev we need your approve

2018-02-14 13:34 UTC, yelizariev approved these changes

2018-02-14 13:42 UTC, merged