[IMP] Merged synchronization icons for longpolling
itpp-labs/pos-addons pull request #568
Opened 2018-01-30 13:06 UTC by KolushovAlexandr

2018-01-31 12:47 UTC, ilmir-k commented
@yelizariev review it please

2018-01-31 12:54 UTC, yelizariev reviewed
I doubt that we need merge icons into one. It doesn't allows us to 3 longpollings or understand situation when local server works, but remote has connection problems

2018-01-31 12:54 UTC, yelizariev commented on pos_longpolling/__manifest__.py
> +    "version": "2.0.1",
2.0.0

2018-01-31 12:54 UTC, yelizariev commented on pos_longpolling/doc/index.rst
> +The meaning of icon colors:
It's not clear which icons you are talking about

2018-01-31 12:54 UTC, yelizariev commented on pos_longpolling/doc/index.rst
> +* Green - local synchronization (i.e. without using a separate server)
Separate server is usually local server. Something wrong with this explanation

2018-02-01 06:49 UTC, KolushovAlexandr commented on pos_longpolling/__manifest__.py
> +    "version": "2.0.1",
2.0.0 was the previous version, it seems that i forgot to change it in manifest, check the changelog

2018-02-05 12:32 UTC, KolushovAlexandr commented
@yelizariev check documentation changes, please

2018-02-09 12:02 UTC, ilmir-k commented
@yelizariev your review is required

2018-02-11 09:32 UTC, yelizariev requested changes

2018-02-11 09:32 UTC, yelizariev commented on pos_longpolling/doc/changelog.rst
> +- **IMP:** Sync icons are merged into one widget, deactivated pollings are hidden
As I understand, they are not merged

2018-02-15 13:58 UTC, ilmir-k approved these changes

2018-02-15 14:02 UTC, ilmir-k commented
@yelizariev leave your review

2018-02-20 19:05 UTC, yelizariev requested changes

2018-02-20 19:05 UTC, yelizariev commented on pos_longpolling/static/src/js/pos_longpolling.js
> +            // Check https://github.com/odoo/odoo/commit/906a9af8f22eb46bf806d624c69799750fc3a78c
It's not added, actually. It's the same as in odoo now. Just put this reference to commit message, rather than in the code

2018-02-20 19:35 UTC, yelizariev approved these changes

2018-02-20 21:23 UTC, merged