[IMP] autopay journal
itpp-labs/pos-addons pull request #583
Opened 2018-02-13 16:41 UTC by KolushovAlexandr

2018-02-14 09:40 UTC, yelizariev commented
![misha](https://user-images.githubusercontent.com/186131/36197178-f218a72c-1194-11e8-9fa1-ca66a32c5bd2.jpg)

2018-02-17 01:47 UTC, yelizariev reviewed
Docs can be improved

2018-02-17 01:47 UTC, yelizariev commented on pos_debt_notebook/doc/index.rst
> +After a successfully proceeded autopay a thumb up is shown on the screen.
👍

2018-02-17 01:47 UTC, yelizariev commented on pos_debt_notebook_rewards/doc/index.rst
> +Be aware that reward amount is fixed value and not depend on quantity of attendances.
‘’Amount of attendee time’’ is better

2018-02-17 01:47 UTC, yelizariev commented on pos_debt_notebook_rewards/doc/index.rst
> +To create *Reward Type*
Create Create

Try to remake it someway

2018-02-17 01:47 UTC, yelizariev commented on base_attendance/doc/index.rst
> +* Click ``ok``
No information about barcode scanning usage

2018-02-17 02:37 UTC, yelizariev requested changes

2018-02-17 02:37 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            if (debt_updates) {
Shall it depend on cashregister?

2018-02-17 02:37 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                        return memo + pl.amount;
Don’t copy paste code. You can use variable right here to decided extract change or not

2018-02-17 02:37 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            });
Shall it depend on sum for current register?

2018-02-17 02:37 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
>                      return memo + pl.amount - self.get_change(pl);
Why we actually need to deduct change?

2018-02-17 12:22 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/pos.js
> +            if (debt_updates) {
@yelizariev  No, because, credit transfers are for different journals, so we should check debt updating at all.

2018-02-17 12:56 UTC, KolushovAlexandr commented on pos_debt_notebook/static/src/js/pos.js
>                      return memo + pl.amount - self.get_change(pl);
@yelizariev Don't clearly remember why, but there were some problems with the exceeding debts check correctness. Now, this check is enhanced with pos_cash_out check.

2018-02-17 13:07 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                    if (cash_out || debt_updates) {
memo + pl.amount

It’s still a copy paste

2018-02-17 17:10 UTC, yelizariev commented on base_attendance/doc/index.rst
> +* If you want to use barcodes install module ``Point of sale``, or add barcode field to the partners form manually
Partner form

2018-02-19 14:55 UTC, closed without merging

2018-02-21 09:34 UTC, Railia commented
@KolushovAlexandr please add description of new function