10.0 pos debt notebook journal 9
itpp-labs/pos-addons pull request #597
Opened 2018-02-20 13:10 UTC by KolushovAlexandr

2018-02-20 17:30 UTC, yelizariev requested changes

2018-02-20 17:30 UTC, yelizariev commented on base_attendance/views/res_attendance_view.xml
> +    <record id="base.action_partner_customer_form" model="ir.actions.act_window">
You shall not change built-in action. Make a copy instead

2018-02-20 17:30 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            : 0;
data.amount_via_discount = Math.max(0, this.get_summary_for_discount_credits())

-- it allows to don't compute twice

2018-02-20 17:30 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +        has_credits_via_discounts: function(){
``has`` usually means that method returns true or false

rename to paymentlines_with_credits_via_discounts

2018-02-20 17:30 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            : order.get_change();
var change = order.get_change() - Math.max(order.get_summary_for_discount_credits(), 0)

2018-02-20 17:30 UTC, yelizariev commented on pos_debt_notebook/static/src/xml/pos.xml
> +            <t t-set="credits_via_discounts_amount" t-value="order.get_summary_for_discount_credits() &lt; 0 ? 0 : order.get_summary_for_discount_credits()"/>
Try to don't call get_summary_for_discount_credits twice

2018-02-20 17:44 UTC, yelizariev commented
Receipt seems ok for now
![reward-receipt](https://user-images.githubusercontent.com/186131/36439746-9e23a54a-168f-11e8-8560-0fe1b108570c.png)

2018-02-21 13:24 UTC, yelizariev commented on base_attendance/views/res_attendance_view.xml
> +    <menuitem id="menu_hr_attendance_view_partners_kanban" name="Partners" parent="menu_hr_attendance_manage_attendances" sequence="15" groups="base_attendance.group_hr_attendance_user" action="res_p
Weird

2018-02-21 13:26 UTC, yelizariev reviewed
Code seems ok

2018-02-22 13:59 UTC, Railia approved these changes

2018-02-22 14:25 UTC, merged