10.0 pos debt notebook debt history reloading
itpp-labs/pos-addons pull request #616
Opened 2018-02-25 06:07 UTC by KolushovAlexandr

2018-02-28 01:21 UTC, yelizariev requested changes

2018-02-28 01:21 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                    r2['journal_code'] = self.env['account.journal'].browse(r2['journal_id'][0]).code
:+1:

2018-02-28 01:21 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +        show_debt_history_click: function(){
Make a separate PR for this update

2018-02-28 10:46 UTC, Railia commented on pos_debt_notebook/models.py
> +                    r2['journal_code'] = self.env['account.journal'].browse(r2['journal_id'][0]).code
@KolushovAlexandr An issue is produced when I first select Customer, and then when I cancel it, his values ​​remain in POs screen

2018-03-01 03:14 UTC, yelizariev approved these changes

2018-03-01 03:15 UTC, merged