10.0-ref-pos_debt_notebook : clean up and refactoring
itpp-labs/pos-addons pull request #632
Opened 2018-03-03 10:58 UTC by KolushovAlexandr

2018-03-03 14:17 UTC, yelizariev requested changes

2018-03-03 14:17 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        self.env["ir.config_parameter"].set_param("pos_debt_notebook.debt_type", self.debt_type)
This has to be in pos.config.settings. Otherwise it's confusing that debt_type is per POS, but it's no

2018-03-03 14:17 UTC, yelizariev commented on pos_debt_notebook/models.py
> -        return {'debt_limit': debt_limit}
removing debt_limit is ok, but the rest is not

2018-03-06 18:30 UTC, yelizariev reviewed
Looks good

2018-03-07 11:51 UTC, Railia approved these changes

2018-03-07 19:01 UTC, merged