[IMP] debt history updating on incoming partner balance updates
itpp-labs/pos-addons pull request #639
Opened 2018-03-06 14:39 UTC by KolushovAlexandr

2018-03-06 17:02 UTC, yelizariev requested changes

2018-03-06 17:02 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                        limit = Math.min(Math.max($('#debt_history tr').length - 2, 0), partner.records_count);
Don't get logic information from UI

2018-03-06 17:02 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                        limit = Math.min(Math.max($('#debt_history tr').length - 2, 0), partner.records_count);
Save history length somewhere in js model instead

2018-03-06 17:02 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                    // updating only opened partner profile and deebt history
deebt

2018-03-06 17:02 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                        if (!limit && !partner.records_count){
Should it be just ``if (!limit)`` ?

2018-03-07 11:11 UTC, Railia approved these changes

2018-03-07 19:20 UTC, yelizariev approved these changes
code looks good

2018-03-07 19:34 UTC, merged