[IMP] reload partners of opened orders
itpp-labs/pos-addons pull request #647
Opened 2018-03-09 12:29 UTC by KolushovAlexandr

2018-03-09 14:02 UTC, yelizariev requested changes
It has to be completly remade.

* use Events instead of  calling method directly, so we can add more event handlers later if needed
* Reloading must be done not at the moment of load failing, but at the moment of restoring connection. Because debt might be loaded successfully, but we lost connection lately and partner balance was chnaged in another pos, while we lost notification about it through longpolling

2018-03-09 17:58 UTC, yelizariev requested changes

2018-03-09 17:58 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +                this.trigger('restoredConnection');
This must be moved to pos_longpolling

2018-03-09 17:58 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +            }
Instead of redefining method, it's better to trigger event in main module and handle it here

2018-03-09 17:58 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +        _failed_load_debts: function(load_partner_ids){
No need for this method. Update reload_debts to make postpone as amount of delay before loading, so you can replace
```
 setTimeout(_.bind(self.reload_debts, self,
                                load_partner_ids, 0, {"postpone": true, "shadow": false}), 3000);
```

with 
```
 self.reload_debts(load_partner_ids, 0, {"postpone": 4000, "shadow": false})
```

2018-03-09 17:58 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +                this.trigger('restoredConnection');
Or at least pos_longpolling has to trigger the event too (i.e. create new event , say change:http_connection)

2018-03-09 17:58 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +                        client_list_screen.update_debt_history([partner.id]);
update_debt_history is already called via updateDebtHistory event, isn't?

2018-03-12 23:19 UTC, yelizariev reviewed
Nothing suspicious on the code

2018-03-13 10:54 UTC, Railia commented
This does not work. When I switch from offline to online, the data does not change. And the system shows errors.

2018-03-14 16:04 UTC, yelizariev submitted a review, later dismissed

2018-03-14 16:04 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +                debts = _.filter(debts, function(deb){
Add comment explaining **why** you filter out it

2018-03-14 16:04 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +            var pushed_orders = $.Deferred();
No need for this. push_order already returns object that can be used to call ``then``

2018-03-14 16:04 UTC, yelizariev commented on pos_debt_notebook_sync/static/src/js/sync.js
> +                partners_in_orders.push(partner.id);
Rename ``partners_in_orders``, because you put there partner from clien list.
It could be ``partners_to_reload`` or something

2018-03-17 00:39 UTC, yelizariev reviewed
It should work

2018-03-20 04:31 UTC, yelizariev approved these changes

2018-03-20 04:44 UTC, yelizariev requested changes

2018-03-20 04:44 UTC, yelizariev commented on pos_debt_notebook/doc/changelog.rst
> +- **ADD:** Autopay button in POS
There is no Autopay button in POS (i.e. in /pos/web). There is no such button at all.

2018-03-20 04:44 UTC, yelizariev commented on pos_debt_notebook/doc/changelog.rst
> +- **IMP:** Updating opened sessions partners debts/credits after restoring the internet connection
``opened sessions partners debts/credits `` -- what is it? Did you mean opened orders?
Anyway, you must remake that sentence, because you have here ``adjective + noun + noun + noun``

2018-03-23 10:43 UTC, Railia approved these changes

2018-03-23 13:13 UTC, merged