[FIX] change for credits via discounts, that cause standard payments …
itpp-labs/pos-addons pull request #650
Opened 2018-03-13 11:58 UTC by KolushovAlexandr

…instead of manual credit updates

2018-03-13 13:49 UTC, yelizariev requested changes

2018-03-13 13:49 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                    var diff_of_rounding = order.get_total_paid() - order.get_total_with_tax() - sum;
Try to recompute percentage in the lines above instead (i.e. recompute percentage for each line). The way you did it now looks ugly and difficult to understand

``ol.set_discount(( 1 - ( ol.get_price_with_tax() + diff_of_rounding )/ol.get_unit_price()) * 100);``

2018-03-14 13:32 UTC, yelizariev requested changes

2018-03-14 13:32 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                        remained_amount -= ol.get_unit_price();
Can you call ``get_total_with_tax`` after each discount instead of introducing new variables and making computtation that difficult to understand

2018-03-23 02:18 UTC, yelizariev approved these changes
The code updates look fine

2018-03-23 08:57 UTC, Railia approved these changes

2018-03-23 08:58 UTC, merged