[IMP] not block UI after first load data from server
itpp-labs/pos-addons pull request #652
Opened 2018-03-13 14:17 UTC by GabbasovDinar

2018-03-13 20:00 UTC, yelizariev requested changes

2018-03-13 20:00 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                framework.blockUI();
Make it as a part of initial black screen (the same as you did with @KolushovAlexandr  for pos_debt_notebook)

2018-03-14 07:14 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                framework.blockUI();
@yelizariev 
![no-god-please-onyf30](https://user-images.githubusercontent.com/15119940/37388189-470aaaee-2781-11e8-886d-e58652ae8a99.jpg)

2018-03-15 15:49 UTC, yelizariev requested changes

2018-03-15 15:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            }
You can use $.when(res). No need for if-then. Neither for ``loaded``

2018-03-15 15:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.multi_session = new exports.MultiSession(self);
It's better to do it in ``initilalize`` or ``init`` method

2018-03-15 16:00 UTC, yelizariev requested changes
Not making timeout for rendering on initial sync is a good idea. Are you sure, that those order are not rendered on "Black screen stage"?

2018-03-15 16:00 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (this.first_load_data_from_server) {
Add new variable to ``request_sync_all``, say ``options`` and pass it to here when data are received. Try to make code without "side effects".

2018-03-15 16:00 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                self.pos.ms_on_update(item, true);
It's a code duplicate. Try to use variable in ``sync_all`` method to define do we need to use timeout or not

2018-03-16 08:20 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.multi_session = new exports.MultiSession(self);
@yelizariev it's not possible. We cannot check this.config.multi_session_id condition since this.config available after completing the load_server_data function only. The deferred object this.ready get 'resolve' object after completing the after_load_server_data function so I think it's right to initialize the multi-session here.

2018-03-16 09:08 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (this.first_load_data_from_server) {
@yelizariev why? in this case, we need send the parameter to the server and get a result with this parameter for sending to sync_all function

2018-03-16 15:21 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (this.first_load_data_from_server) {
No need to send anything to the server to call method with extra argument

2018-03-16 15:23 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            if (this.first_load_data_from_server) {
Still bad idea. Use extra argument instead

2018-03-20 04:16 UTC, yelizariev requested changes

2018-03-20 04:16 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            var res = PosModelSuper.prototype.after_load_server_data.apply(self, arguments);
You can remake this code without calling ``after_load_server_data`` in two places (hint: move ``var res = .... `` at the beginning.

2018-03-20 04:16 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                message.first_load = options.first_load;
No need to send this argument to the server. Put extra arg to method ``send`` instead.

2018-03-21 09:43 UTC, GabbasovDinar commented
@yelizariev DONE

2018-03-21 19:35 UTC, yelizariev approved these changes
Almost ready.

2018-03-21 19:35 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            }
uid is specific for sync_all only. Move it to request_sync_all

2018-03-21 19:40 UTC, yelizariev requested changes

2018-03-21 19:40 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            } else {
Option name must describe how method shall be processed and not in which cases (when) it's used.

2018-03-21 19:43 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            } else {
rename ``first_load`` to immediate_rerendeing,  or sync_update or similar

2018-03-23 01:41 UTC, yelizariev requested changes
Alternative name: update_orders_immediatly

2018-03-23 01:41 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return self.multi_session.request_sync_all({'immediate_rerendeing': true}).then(function() {
fix spelling ``immediate_rerendeing``

2018-03-23 01:41 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return self.multi_session.request_sync_all({'immediate_rerendeing': true}).then(function() {
Also, the name is not ideal as you said, that on initial black screen orders are not rendered at all

2018-03-23 06:39 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return self.multi_session.request_sync_all({'immediate_rerendeing': true}).then(function() {
@yelizariev What name can I use for this variable?

2018-03-23 06:40 UTC, GabbasovDinar commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return self.multi_session.request_sync_all({'immediate_rerendeing': true}).then(function() {
@yelizariev update_orders_immediatly or immediate_rerendeing?

2018-03-23 21:22 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return self.multi_session.request_sync_all({'immediate_rerendeing': true}).then(function() {
You still want to use wrong spelling **rerendeing**? :smile:

2018-03-23 21:22 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return self.multi_session.request_sync_all({'immediate_rerendeing': true}).then(function() {
Choose yourself

2018-03-25 12:52 UTC, yelizariev approved these changes
Code is fine now

2018-03-30 14:43 UTC, yelizariev approved these changes
I looked through. It looks fine

2018-04-03 12:21 UTC, ilmir-k approved these changes

2018-04-03 13:19 UTC, merged