[NEW][10.0] pos_cashbox module
itpp-labs/pos-addons pull request #659
Opened 2018-03-29 10:13 UTC by ilmir-k

[NEW][10.0] pos_cashbox module

2018-03-29 11:46 UTC, ilmir-k commented
issue for unitest #662

2018-04-04 13:29 UTC, Railia approved these changes

2018-04-04 13:29 UTC, Railia approved these changes
👍

2018-04-04 13:50 UTC, yelizariev requested changes
Also, add copyright lines

2018-04-04 13:50 UTC, yelizariev commented on pos_cashbox/views/pos_cashbox_view.xml
> +                    </button>
Why there are two the same buttons?

2018-04-04 13:50 UTC, yelizariev commented on pos_cashbox/static/src/js/tour.js
> +});
It's stupid test which open POS, while the feature (button) is in backend

2018-04-04 13:50 UTC, yelizariev commented
![default](https://user-images.githubusercontent.com/186131/38311625-160b0fe2-3839-11e8-9b18-5b8961c01242.jpg)

2018-04-12 10:32 UTC, ilmir-k commented on pos_cashbox/views/pos_cashbox_template.xml
> +                <script type="text/javascript" src="/pos_cashbox/static/src/js/tour.js"></script>
@GabbasovDinar I suppose it can be removed due to tour.js was removed

2018-04-14 17:03 UTC, yelizariev approved these changes
Previous requests are done

2018-04-25 12:14 UTC, ilmir-k commented
@GabbasovDinar 2 remaining lints to be fixed

2018-04-26 08:15 UTC, GabbasovDinar commented
@ilmir-k DONE (I sent the PR to your branch)

2018-04-26 11:08 UTC, ilmir-k commented
@yelizariev I think it can be merged. It's ready for publication

2018-05-09 09:44 UTC, ilmir-k commented
![dva-zhduna](https://user-images.githubusercontent.com/14342645/39808080-6e595662-5397-11e8-9013-26f6058365c9.jpg)

2018-05-09 21:09 UTC, yelizariev commented
We need to fix pos_invoice_pay and check are there other errors or not

2018-05-23 12:34 UTC, GabbasovDinar commented
@yelizariev We have one lint error about test only. I think we can merge it

2018-08-09 15:24 UTC, merged