[NEW][11.0] pos_logout module
itpp-labs/pos-addons pull request #660
Opened 2018-03-29 10:33 UTC by ilmir-k

[NEW][11.0] pos_logout module

2018-03-29 11:06 UTC, ilmir-k commented
issue for unitests #661

2018-04-04 12:59 UTC, ilmir-k commented
@yelizariev it can be merged

2018-04-04 13:33 UTC, Railia approved these changes

2018-04-04 14:01 UTC, yelizariev requested changes
Why ``pos_pin`` is not used? I believe some code can be moved to it

2018-04-28 23:52 UTC, gustavovalverde commented on pos_logout/doc/index.rst
> +  * Click the ``Logout`` icon - the screen is locked
A great feature for this would be:
- On the POS Config, set a **timeout** and/or an **autolock** after each order.

This is commonly required.

2018-04-29 18:26 UTC, invitu commented on pos_logout/doc/index.rst
> +  * Click the ``Logout`` icon - the screen is locked
I think we did something like that in OCA https://github.com/OCA/pos/tree/10.0/pos_quick_logout

2018-05-12 03:16 UTC, gustavovalverde commented on pos_logout/doc/index.rst
> +  * Click the ``Logout`` icon - the screen is locked
oh, thanks @invitu, we'll be migrating that one to 11 👍

2018-08-15 18:48 UTC, yelizariev commented on pos_logout/models/logout_config.py
> +    logout_interval = fields.Integer(string='Screen Autolock', default=0, help="Interval after the last activity before screen is blocked. Zero if autolocking is not needed")
No information about it in index.rst

2018-08-15 18:48 UTC, yelizariev commented on pos_logout/__manifest__.py
> +        "pos_pin",
Is it really used? If not, why not?

2018-08-16 08:37 UTC, KolushovAlexandr commented on pos_logout/__manifest__.py
> +        "pos_pin",
@yelizariev example of usage
https://github.com/it-projects-llc/pos-addons/pull/660/files#diff-03dce2b88baa56cca829af7380b187f7R69

2018-08-16 18:16 UTC, yelizariev approved these changes

2018-08-17 10:38 UTC, merged