disabe autopay for some cases
itpp-labs/pos-addons pull request #663
Opened 2018-03-30 12:36 UTC by KolushovAlexandr

2018-04-02 13:30 UTC, yelizariev requested changes
Add copyrights and license to all files, please

2018-04-02 13:30 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                                'credits_autopay': False,
I think we should keep it True, i.e. activate feature in new installation

2018-04-02 14:11 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            if (!order.get_paymentlines().length || order.has_credit_product()){
``render_paymentlines`` probably need to be updated. It looks strange, that it makes update only when there are no lines

2018-04-03 19:47 UTC, yelizariev approved these changes
Code is ok

2018-04-04 08:54 UTC, ilmir-k approved these changes

2018-04-04 14:39 UTC, merged