[REF] separated calculating of discounts for credits via discounts pa…
itpp-labs/pos-addons pull request #667
Opened 2018-04-03 10:50 UTC by KolushovAlexandr

…yments

2018-04-14 17:04 UTC, yelizariev commented
Is it ready to review?

2018-04-16 09:04 UTC, KolushovAlexandr commented
@yelizariev No, I know the scenario that doesn't work on

2018-04-24 15:43 UTC, yelizariev requested changes
set_discounts looks frighteningly

2018-04-24 15:43 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        print pos_order
remove please

2018-04-24 15:43 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +//                }
Don't forget to remove

2018-04-24 15:43 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +//            var change = order.get_change() - Math.max(order.get_summary_for_discount_credits(), 0);
don't forget to remove

2018-04-24 15:43 UTC, yelizariev commented on pos_debt_notebook/static/src/xml/pos.xml
> +                    <!--<t t-esc="widget.format_currency(order.get_change() - credits_via_discounts_amount)"/>-->
don't forget to remove

2018-04-24 15:43 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            line['tax_ids'] = False
Can we use some built-in methods for this?
E.g. https://github.com/odoo/odoo/blob/11.0/addons/sale/models/sale.py#L1154-L1174
or (better)

https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L25-L31
https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L504-L513
https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L967-L976
https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L993-L1003

2018-04-25 15:12 UTC, yelizariev requested changes

2018-04-25 15:12 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            amount -= old_price - new_price
Can this be done via built-in methods too?
https://github.com/it-projects-llc/pos-addons/pull/667#discussion_r183782447

2018-04-26 08:23 UTC, KolushovAlexandr commented on pos_debt_notebook/models.py
> +            amount -= old_price - new_price
@yelizariev I haven't seen any methods in the built-in code for recalculating absolute discount into a relative one

2018-04-26 20:53 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            amount -= old_price - new_price
ok, got it

2018-04-26 20:54 UTC, yelizariev requested changes

2018-04-26 20:54 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                'discount': round(max(min(line.discount + (amount / full_price) * 100, 100), 0), 2),
Use round methods from odoo framework

2018-04-30 15:58 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                'discount': currency.round(max(min(line.discount + (amount / full_price) * 100, 100), 0)),
![default](https://user-images.githubusercontent.com/186131/39437039-2265dfc6-4cb9-11e8-9850-95d26c867eb4.jpg)

2018-05-16 18:15 UTC, yelizariev requested changes

2018-05-16 18:15 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        if abs(rounding_diff) > 0.00001:
use ``float_is_zero``

2018-05-16 18:15 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            if abs(amount) < 0.00001:
use ``float_is_zero``

2018-05-16 18:15 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            full_price = disc and (price / (100 - disc)) * 100 or price
Put it directly to discount formula

2018-05-16 18:15 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            amount -= price - new_price
Try to use line.price_subtotal_incl:

`amount -= price - line.price_subtotal_incl`

2018-06-05 15:03 UTC, yelizariev requested changes
It's wrong check in general. It should be:

* if discount is not 100% (DONE)
* AND if product doesn't have taxes that are not included in the price (TODO)

2018-06-05 15:03 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            if (discount_pls.length){
Make ``discount_pls``  boolean and don't use ``discount_pls.length``

2018-06-05 15:11 UTC, yelizariev requested changes

2018-06-05 15:11 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +        },
Split in two checks and rename method:
```

check_....: function(){
    ...
   if (has_only_payments_via_discount)
       return OK
   if (!has_products_with_not_included_taxes)
       return OK
   return ERROR
}
```

2018-06-06 09:24 UTC, yelizariev approved these changes

2018-06-20 13:21 UTC, merged