[IMP] required multi session for POS
itpp-labs/pos-addons pull request #679
Opened 2018-04-19 12:09 UTC by GabbasovDinar

2018-04-20 16:00 UTC, yelizariev requested changes

2018-04-20 16:00 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    multi_session_id = fields.Many2one('pos.multi_session', 'Multi-session', required=True, help='Set the same value for POSes where orders should be synced. Keep empty if this POS should not use syn
Fix this note:

     Keep empty if this POS should not use syncing

2018-05-22 13:37 UTC, yelizariev requested changes
Update Version to 4.1.0

2018-05-22 13:47 UTC, yelizariev requested changes
Also, there should be Default Session for normal (non-demo installation)

2018-05-22 13:47 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    multi_session_id = fields.Many2one('pos.multi_session', 'Multi-session', required=True, help='Set the same value for POSes where orders should be synced. Deselect checkbox of "Active" if this POS
Put required to the form instead

```
2018-05-22 11:37:27,076 25268 WARNING 16780-679-04dd3a-base odoo.models: WARNING: unable to set column multi_session_id of table pos_config not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE pos_config ALTER COLUMN multi_session_id SET NOT NULL
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/16780-679-04dd3a/odoo/models.py", line 2537, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, name))
  File "/mnt/odoo-extra/runbot/static/build/16780-679-04dd3a/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/16780-679-04dd3a/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "multi_session_id" contains null values

```

2018-05-22 13:53 UTC, yelizariev commented
```
************* Module pos_multi_session
pos_multi_session/multi_session_view.xml:7: [W7939(deprecated-data-xml-node), ]  Use <odoo> instead of <odoo><data> or use <odoo noupdate="1">instead of <odoo><data noupdate="1">
pos_multi_session/demo/demo.xml:8: [W7939(deprecated-data-xml-node), ]  Use <odoo> instead of <odoo><data> or use <odoo noupdate="1">instead of <odoo><data noupdate="1">
pos_multi_session/views/pos_multi_session_views.xml:8: [W7939(deprecated-data-xml-node), ]  Use <odoo> instead of <odoo><data> or use <odoo noupdate="1">instead of <odoo><data noupdate="1">

```

2018-05-24 14:44 UTC, yelizariev requested changes
Default Multi-Session must be applied automatically on POS creation

2018-05-24 14:44 UTC, yelizariev commented on pos_multi_session/data/pos_multi_session_data.xml
> +        <field name="name">multi session</field>
Rename. Add word *Default*

2018-05-24 14:44 UTC, yelizariev commented on pos_multi_session/demo/demo.xml
> -            <field name="multi_session_id" ref="demo_multi_session2"/>
Why did you remove demo_multi_session2?

2018-06-05 08:13 UTC, yelizariev requested changes

2018-06-05 08:13 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **NEW:** A setting in POS config Enable or Disable Synchronization for the POS
It's not in POS config. Also, add information about required field and explain why we did it

2018-06-05 12:13 UTC, yelizariev requested changes

2018-06-05 12:13 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +        for pos in configs:
Use just ``configs.write``

2018-06-05 12:13 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    def action_default_multi_session(self):
The name doesn't describe what the method does

2018-06-05 12:13 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    multi_session_active = fields.Boolean(string="Active", help="Select the checkbox to enable synchronization for this POS", default=False)
Not sure about this. Probably default True is better

2018-06-05 12:13 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **NEW:** Field "Active" to enable/disable synchronization for POSes. The multi-session parameter is required now to provide compatibility with "POS Multi Session Menu" module
... and other modules that put common settings in POS Multi Session

2018-06-05 12:13 UTC, yelizariev commented on pos_multi_session/demo/demo.xml
> -        <field name="multi_session_active">False</field>
Keep the value even if it's the default one

2018-06-05 14:37 UTC, yelizariev requested changes

2018-06-05 14:37 UTC, yelizariev commented on pos_multi_session/demo/demo.xml
> +        <field name="active">True</field>
For ``active``  fields odoo hides non-active fields form search results by default

2018-06-05 14:37 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +            for all POSes for which not specified multi_session_id
for all POSes for which multi_session_id is not specified

2018-06-05 14:37 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +        name = self.name or self._name
call super to get base name

2018-06-05 15:33 UTC, yelizariev approved these changes

2018-06-05 16:38 UTC, ilmir-k approved these changes

2018-06-21 09:56 UTC, merged