[10.0][DOC] pos_debt_notebook documentation
itpp-labs/pos-addons pull request #681
Opened 2018-04-24 17:51 UTC by ilmir-k

2018-04-24 19:48 UTC, yelizariev commented
pos_debt_notebook_sync has obsolete information, e.g.


> Step 1. Use the Max Debt Limit setting to specify should customers have to pay in advance (Max Debt = 0) or they allowed to pay later (Max Debt > 0). You can also specify different settings for different customers.

2018-04-24 20:11 UTC, yelizariev requested changes
Also, Autopay button is not really presented as needed. It must show how cool it is. It could be here, in pos_debt_notebook_sync or both

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      make sale on credit in a single click
Uppercase for first letter should be better

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      ability to pay full debt at once
:-1: it's kind of obvious thing, but it's difficult to understand it here, while we shall not lose attention at the beginning of reading. It's better to remove

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      ability to cash out credits
I'd not put it here. Replace with something related to rewards, that are our of fiscal controls (volunteer rewards, employee rewards, etc.)

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      ability to transfer debts/credits from one credit journal to another one in POS
It's not popular feature

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      new autopay option to add credit journal to payment line automatically
This can be merged with ``+	      make sale on credit in a single click``, which is not really true (not a single click)

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      track all debts/credits by reports generated
It's too similar to 

+	      see all debt/credit history of customers in both POS and backend

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	  The module allows to make sale on credit in a single click. You do not need to take money from a customer each time. You'll be able to offer your customer to make prepayment or pay periodically, e
Too long. Try to make it shorter or split into usage cases:

* festival: control cash flow in a single point
* Small shops: 

  * get payment in advance  
  * or ask payment periocall, e.g every month
  * or make round payments and small change on customer profile

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	  The customer is able to pay some part by Cash/Bank and the rest by debt using available credit journal(s) (or pay all the order amount by debt). You may use as many credit journals as you wish.
If your remove Bank, it would be more real usage case (accounting cash changes)

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +      <img style="max-width: 80%" src="pos_debt_1.png"/>
Screenshots contains demo Journals, which is more testing purpose and not for demonstration. You probably need to change demo data names to make them more real live examples.

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	  You can easily put the customer change to his credit account if needed.
Explain why (to don't care about small change)

2018-04-24 20:11 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	  All customer debts/credits balances are shown on client list view
This can be part of ``Customer Debt/Credit History`` section, which should be move here, because ``Pay Full Debt`` is too boring

2018-04-27 14:40 UTC, ilmir-k commented
@yelizariev 
It has not been completed yet

> pos_debt_notebook_sync has obsolete information

I know and planned to send the updates in another commits.

2018-05-09 09:29 UTC, ilmir-k commented
@yelizariev check the updates for pos_debt_notebook description, then I'll send update for pos_debt_notebook_sync

2018-05-09 22:02 UTC, yelizariev requested changes
Autopay feature is not demonstrated as a cool thing, that dramatically speeds the process up (scan barcode, scan or click product, bum-bum-bum-ready)

2018-05-09 22:02 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +		    let a customer to make payment by credit from different points
make payment = buy

2018-05-09 22:02 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      Ability to update several users credits at once
The feature you mean works only for users of the same company

2018-05-09 22:02 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +    <h4 class="oe_slogan"><b>Handling several employees/clients at once</b></h4>
The feature you mean works only for users of the same company

2018-05-09 22:02 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +    <h4 class="oe_slogan"><b>Purchase Credits</b></h4>
Add a screentshot that the product can be used to buy via eCommerce

2018-05-15 20:09 UTC, yelizariev requested changes
It's probably easier to make a video of the process 

* use some tool that shows where the push (click) was made
* The video shall not show mouse cursor

2018-05-15 20:09 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +      <img style="max-width: 80%" src="pos_debt_thumbs_up.png"/>
Too small. The icon is actually bigger.

2018-05-15 20:09 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +	      Validate the payment
* Payment is automatically filled
* Click Validate button which is located at the same place as Button to open payment screen

2018-06-19 10:14 UTC, merged