[IMP] pos_multi_session: new option for POS in offline mode
itpp-labs/pos-addons pull request #700
Opened 2018-06-06 09:14 UTC by GabbasovDinar

New option to save orderlines added to existing orders in offline mode

2018-06-06 09:48 UTC, yelizariev requested changes
Blocked until tests are done

2018-06-06 11:05 UTC, Railia approved these changes

2018-08-06 08:29 UTC, yelizariev reviewed
It shall not be an option. Always try to send updates to server (i.e. multi_session_block_exist_order is always false)

2018-08-06 08:29 UTC, yelizariev commented on pos_multi_session/models/pos_multi_session_models.py
> +    multi_session_block_exist_order = fields.Boolean('Block existing order', default=True, help='Block the existing order if the POS does not have a connection to the server')
Order is not blocked. But updates of existing order are ignored

2018-10-11 09:04 UTC, GabbasovDinar commented
was fixed here https://github.com/it-projects-llc/pos-addons/pull/747

2018-10-11 09:04 UTC, closed without merging