10.0 ms sync conflicts imp
itpp-labs/pos-addons pull request #721
Opened 2018-07-19 15:42 UTC by GabbasovDinar

2018-07-19 15:59 UTC, yelizariev reviewed
Rename

2018-07-19 15:59 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                var callback = self.ms_update_callback;
updates_from_server_callback?

2018-07-19 15:59 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                return;
:+1:

2018-07-20 08:20 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                var callback = self.ms_update_callback;
yep, it were done before the renamings

2018-07-24 06:44 UTC, yelizariev requested changes

2018-07-24 06:44 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    }, 2000);
Naive approach. Make more stable solution

2018-07-26 04:09 UTC, merged