:ambulance: issue related to debt loading after creating a new partner
itpp-labs/pos-addons pull request #729
Opened 2018-08-03 09:37 UTC by KolushovAlexandr

2018-08-03 10:13 UTC, ilmir-k approved these changes

2018-08-03 10:13 UTC, ilmir-k commented
@KolushovAlexandr change version

2018-08-03 11:14 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +                            // In case this function was called from saved_client_details load_new_partners may work asynchronously
You can create a PR to odoo to fix that

2018-08-30 15:53 UTC, yelizariev requested changes

2018-08-30 15:53 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **FIX:** Error related to debt loading after creating a new partner in POS
Wrong changelog file

2018-08-31 08:48 UTC, merged