10.0 ms sync conflicts SYNC ALL REF
itpp-labs/pos-addons pull request #731
Opened 2018-08-07 11:14 UTC by KolushovAlexandr

2018-08-07 13:03 UTC, yelizariev commented
- [ ] variable ``sync_all`` is specified and method args, but not used

2018-08-07 13:05 UTC, yelizariev commented
- [ ] ``sync_all`` method has destroy_removed_orders. Can it be moved to ``updates_from_server``?

2018-08-07 13:06 UTC, yelizariev commented
- [ ] update changelog

2018-08-08 08:45 UTC, yelizariev requested changes

2018-08-08 08:45 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    this.multi_session.destroy_removed_orders(_.map(data.orders, function(o){
Do you remove all orders here?

2018-08-08 08:48 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    this.multi_session.destroy_removed_orders(_.map(data.orders, function(o){
ok, you don't

2018-08-08 08:50 UTC, yelizariev requested changes

2018-08-08 08:50 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.destroy_removed_orders(server_orders_uid);
It's already called in updates_from_server

2018-08-08 08:53 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.pos.pos_session.sequence_number = Math.max(Boolean(sequence_number) && sequence_number, data.order_ID + 1 || 1);
Why there is no the same code in updates_from_server?

2018-08-09 07:59 UTC, yelizariev requested changes
Could you make more clean work work with .offline_orderline? For example mark all new lines as offline and unmark once it’s send successfully to server

2018-08-09 11:30 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    multiprint_resume: data.multiprint_resume,
this lins is useless

2018-08-09 13:42 UTC, yelizariev requested changes

2018-08-09 13:42 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                        self.is_loaded = true;
use ``pos.ready....`` instead

2018-08-09 13:42 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                line.offline_orderline = false;
Consider to update this variable via options (like not_render)

2018-08-09 13:42 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                order.init_locked = false;
You don't need it here if you remove it from ms_create_order

2018-08-10 09:36 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                line.offline_orderline = false;
@yelizariev they are partially correlated, but I see no way to make offline_orderline depends on not_render

2018-08-10 09:52 UTC, KolushovAlexandr commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                order.init_locked = false;
@yelizariev 
// init_locked blocks execution of save_to_db
// the order is unlocked at the end of ms_update_order
probably the removing might causes some problems?

2018-08-14 16:44 UTC, ilmir-k commented
@yelizariev the changes requested are fixed I suppose

2018-08-14 16:49 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                line.offline_orderline = false;
I meant to set ``offline_orderline`` in the same way as ``not_render`` (via options, not by setting it directly)

2018-08-14 16:50 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                order.init_locked = false;
no

2018-08-14 16:51 UTC, yelizariev commented
@ilmir-k not really

2018-08-15 14:49 UTC, GabbasovDinar approved these changes

2018-08-16 18:13 UTC, yelizariev approved these changes

2018-08-17 07:27 UTC, merged