:ambulance: fixed wrong calculation of partner debts
itpp-labs/pos-addons pull request #744
Opened 2018-08-28 10:42 UTC by KolushovAlexandr

2018-08-29 15:22 UTC, yelizariev requested changes
Could you fix the previous implementation, because it's quicker way to compute (it makes only one sql request to db instead of num(partners)

2018-08-29 15:23 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                    res[o.partner_id.id] += s.amount
Why don't you check statement state?

2018-08-30 11:52 UTC, yelizariev requested changes

2018-08-30 11:52 UTC, yelizariev commented on pos_debt_notebook/models.py
> +        statements_ids = [st.id for o in orders for st in o.statement_ids]
Can you use ``mapped`` intead?

2018-08-30 11:52 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                     account_bank_statement_line AS absl
three FROM without JOIN looks like a bad idea

2018-08-30 11:52 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                                                                     ('id', 'in', statements_ids)])
Instead of
                                                                     ('id', 'in', statements_ids)])

You might use something like ``(pos_order_id.partner_id', 'in', self.ids)``?

2018-08-30 13:19 UTC, yelizariev requested changes

2018-08-30 13:19 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                    LEFT JOIN pos_order po ON (absl.pos_statement_id=po.id)
po.id and absl.pos_statement_id looks like ids in didfferent tables

2018-08-30 13:21 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                    LEFT JOIN pos_order po ON (absl.pos_statement_id=po.id)
ok, pos_statement_id is pos.order

2018-08-30 13:24 UTC, yelizariev commented on pos_debt_notebook/doc/changelog.rst
> +- **FIX:** Wrong calculation of partner debts
clarify how it worked before

2018-08-30 13:37 UTC, yelizariev approved these changes

2018-09-12 13:37 UTC, ilmir-k approved these changes

2018-09-12 13:39 UTC, ilmir-k commented
@yelizariev it can be merged

2018-09-13 08:31 UTC, merged