:ambulance: Product quantities representation according to the set lo…
itpp-labs/pos-addons pull request #745
Opened 2018-08-29 09:32 UTC by KolushovAlexandr

…cation

2018-08-29 11:51 UTC, yelizariev commented
There is more simple way at least in another version https://github.com/it-projects-llc/pos-addons/commit/b83570361569d6072cc5c827bbdc745dd186f315#diff-98128c6f5bc800511052fa25a4bfbbfe

2018-08-29 15:28 UTC, yelizariev commented on pos_product_available/static/src/js/pos.js
> +                        });
When pos_cache is not installed you make two requests instead of one. You need to update exising "model" instead

2018-08-30 13:35 UTC, yelizariev requested changes

2018-08-30 13:35 UTC, yelizariev commented on pos_product_available/static/src/js/pos.js
> +                return new Model('product.product').query(['qty_available']).
I make second call when pos_cache is not installed for data that already loaded

2018-08-30 14:13 UTC, KolushovAlexandr commented on pos_product_available/static/src/js/pos.js
> +                return new Model('product.product').query(['qty_available']).
@yelizariev return on the 37 line prevents it

2018-08-30 14:14 UTC, yelizariev approved these changes

2018-09-12 13:58 UTC, ilmir-k commented on pos_product_available/__init__.py
> +from . import models
@KolushovAlexandr  no need to import ``models``

2018-09-17 13:07 UTC, ilmir-k approved these changes

2018-09-20 07:23 UTC, yelizariev commented
Travis needs to be fixed

2018-09-26 12:11 UTC, merged