:heart_eyes: show popup if a table does not exist
itpp-labs/pos-addons pull request #757
Opened 2018-09-19 11:39 UTC by GabbasovDinar

2018-09-19 11:44 UTC, yelizariev approved these changes

2018-09-19 11:44 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +        ms_update_exist_order: function(order, data) {
existing

2018-09-19 11:44 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                'title': _t('Not found table'),
Got unknown table

2018-09-19 12:15 UTC, yelizariev commented
My comments are fixed :+1:

2018-10-05 12:15 UTC, Ramil-Mukhametzyanov requested changes
(-) there is no toolbar to manage the configuration of the tables for demo user
(+) after the modification of the table configuration by the administrator and entering a table, a popup window appears for the demo user and the user can see the changes
(-) after the second modification, a pop-up window for admin appears
(+) but the latest changes for the administrator are still there
(-) demo user can operate on a deleted table
(-) the initialization of tables stops in the "Sync Order" process
The error in the browser console:
point_of_sale.assets.js:299 Uncaught TypeError: Cannot read property 'show' of undefined
	at Class.show_popup (point_of_sale.assets.js:299)
	at child.ms_create_order (point_of_sale.assets.js:661)
	at child.ms_update_order (point_of_sale.assets.js:603)
	at child.ms_update_order (point_of_sale.assets.js:664)
	at point_of_sale.assets.js:594
	at Function._.each._.forEach (web.assets_common.js:12)
	at child.updates_from_server (point_of_sale.assets.js:594)
	at child.updates_from_server (point_of_sale.assets.js:663)
	at Object.<anonymous> (point_of_sale.assets.js:650)
	at fire (web.assets_common.js:541)

Tested in pos-addons 757 runbot with updated and explicit modules

2018-10-18 09:32 UTC, GabbasovDinar commented
@Ramil-Mukhametzyanov https://github.com/odoo/odoo/pull/27924

2018-10-30 13:29 UTC, Ramil-Mukhametzyanov commented
> @Ramil-Mukhametzyanov you can check the PR [odoo/odoo#27924](https://github.com/odoo/odoo/pull/27924) I think it is related

The Odoo PR [odoo/odoo#27924] is closed, but nothing has changed.

2018-11-05 11:29 UTC, Ramil-Mukhametzyanov requested changes
The last changes didn't pass a test with two users admin and demo:
1. If demo user deletes a table and admin clicks on this table, pop-up "unknown table" appears for demo user, not for admin. ( it's the same crosswise)
2. The 'unknown' table displayed on the floor plan. (if we can detect it as unknown we can hide it after the click)
3. Deleting the first table causes continuous loop of errors. (orders are transfered on the first table, but not on the first free table.)

A table must be protected from deleting if it is only one table on the floor.

2018-11-08 11:02 UTC, GabbasovDinar commented
> A table must be protected from deleting if it is only one table on the floor.

This question does not apply to this PR. In addition, you can always turn off the table edit setting for the user.

2018-11-09 10:01 UTC, Ramil-Mukhametzyanov requested changes
Almost perfect, but one thing should be fixed.

Steps:
1. Delete all the tables by an user
2. Click on a table by another user
Result:
The error 'transfer_table is undefined' in the first user's POS session.

It is necessary to protect the last table from deleting.

2018-11-09 13:07 UTC, Ramil-Mukhametzyanov approved these changes
:+1:

2018-11-12 07:46 UTC, yelizariev requested changes
No changelog available

2018-11-12 10:47 UTC, yelizariev requested changes
Make just 3 commits for each update: 
*  pos_debt_notebook/doc/changelog.rst (lint)
* pos_multi_session
* pos_multi_session_restaurant

2018-11-12 10:47 UTC, yelizariev commented on pos_multi_session_restaurant/doc/changelog.rst
> +- **IMP:** Synchronize the process of deleting or adding tables
Use new tags for changelog

2018-11-12 10:47 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **IMP:** Code refactoring to support the "Sync restaurant orders" module
Use new tags

2018-11-12 11:01 UTC, yelizariev requested changes

2018-11-12 11:01 UTC, yelizariev commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            return d;
Doubtful solution

2018-11-21 07:57 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +**Improvement:** Code refactoring to support the "Sync restaurant orders" module
I don't see why this refactoring is needed

2018-11-21 07:59 UTC, GabbasovDinar commented on pos_multi_session/doc/changelog.rst
> +**Improvement:** Code refactoring to support the "Sync restaurant orders" module
@yelizariev Code refactoring to support **removing/adding tables** for the "Sync restaurant orders" module. Is it correctly?

2018-11-21 08:36 UTC, merged