:arrow_up::one::one: pos_cashbox
itpp-labs/pos-addons pull request #763
Opened 2018-09-25 12:39 UTC by GabbasovDinar

2018-10-01 07:01 UTC, yelizariev commented
For lints use :rainbow:

2018-10-01 07:02 UTC, yelizariev commented
travis checks are too red

2018-11-21 11:17 UTC, yelizariev requested changes

2018-11-21 11:17 UTC, yelizariev commented on pos_cashbox/tests/test_js.py
> +        self.phantom_js('/web/tests?mod=web&failfast', "", "", login='admin', timeout=1800)
![wrong](https://user-images.githubusercontent.com/186131/48838009-db0ab200-eda8-11e8-8296-26ed2742730e.png)

2018-11-26 08:30 UTC, GabbasovDinar commented on pos_cashbox/tests/test_js.py
> +        self.phantom_js('/web/tests?mod=web&failfast', "", "", login='admin', timeout=1800)
![image](https://user-images.githubusercontent.com/15119940/49001722-61473f80-f17f-11e8-86d4-5adf73f467a2.png)

2019-01-16 13:01 UTC, Ramil-Mukhametzyanov reviewed
:+1: "Open Cashbox" Button works in payment screen from POS

2019-01-16 14:49 UTC, GabbasovDinar commented
` "Open Cashbox" Button works in payment screen from POS`

@Ramil-Mukhametzyanov It's a default feature. But this module adds a new button in form view for open cashbox

2020-06-05 22:01 UTC, closed without merging