10.0 pos debt notebook generate invoices Updates
itpp-labs/pos-addons pull request #776
Opened 2018-10-05 13:37 UTC by KolushovAlexandr

2018-10-09 13:13 UTC, yelizariev requested changes
I'd suggest remove new fields, add return data in _compute_partner_journal_debt

2018-10-09 13:13 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    @api.depends('journal_debt', 'journal_credit_balance')
Those fields are computed in this method and cannot be used in depends

2018-10-09 13:13 UTC, yelizariev commented on pos_debt_notebook/models.py
> +            r['journal_debt'] = -res_index[r.id]['balance']
that it's bracketed and not dot-notation (r.journal_debt)?

2018-10-09 13:13 UTC, yelizariev commented on pos_debt_notebook/models.py
> +    journal_credit_balance = fields.Float(string='Credit Balance per Journal')
You store values in DB that depends on journal and recomputed each time. It doesn't make sense

2018-10-09 13:25 UTC, KolushovAlexandr commented on pos_debt_notebook/models.py
> +    journal_credit_balance = fields.Float(string='Credit Balance per Journal')
@yelizariev If I make the field computed then it will be recalculated when it is not necessary, also it won't have arguments for that. The field was recalculated, and only then I use its value

2018-10-10 08:12 UTC, yelizariev approved these changes
LGTM

2018-10-22 12:28 UTC, merged