:ambulance: pos_invoice diff acc fix
itpp-labs/pos-addons pull request #778
Opened 2018-10-10 08:58 UTC by KolushovAlexandr

2018-10-10 11:24 UTC, yelizariev approved these changes

2018-10-10 13:11 UTC, ilmir-k requested changes
@KolushovAlexandr We need to consider the case with empty `writeoff_acc_id`. If we have not set ``writeoff_acc_id`` but pay more than invoice amount in POS we could show a warning message to warn that there is no account to put the difference.

2018-10-12 12:42 UTC, yelizariev commented
:bath: is only for development. Use :rose: instead

2018-10-12 14:58 UTC, ilmir-k commented
> bath is only for development. Use rose instead

Ok

2018-10-12 14:58 UTC, ilmir-k approved these changes

2018-10-12 15:04 UTC, merged