:heart_eyes: don't use the 'change' trigger to save to the local storage
itpp-labs/pos-addons pull request #783
Opened 2018-10-11 11:52 UTC by GabbasovDinar

If an order is changed every time this PR fixes an issue with rerendering of the product list. It's related to new changes in Odoo 11.0 https://github.com/odoo/odoo/blame/11.0/addons/point_of_sale/static/src/js/screens.js#L846

2018-10-11 11:56 UTC, GabbasovDinar commented
@yelizariev Can you check it?

2018-10-18 12:24 UTC, yelizariev requested changes
Can there be other reason to use ``trigger('change')``?

Anyway, you have to update change log and *Tested on* note in README

2018-10-29 13:32 UTC, GabbasovDinar commented
@yelizariev Who can test these changes? 
![image](https://user-images.githubusercontent.com/15119940/47652886-008d0d00-dba9-11e8-8e5f-c62f0c7ed5de.png)

2018-11-09 14:53 UTC, yelizariev requested changes

2018-11-09 14:53 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **FIX:** Rerendering the Products list after change a current order
What is the problem with rerendering?

2018-11-12 07:37 UTC, GabbasovDinar commented on pos_multi_session/doc/changelog.rst
> +- **FIX:** Rerendering the Products list after change a current order
@yelizariev  If we have a rerender of the product list every time, then we will get a hang and slow response of the system. 

How can I change the log message?

2018-11-15 13:19 UTC, GabbasovDinar commented
I will make cherry-pick of a commit from https://github.com/it-projects-llc/pos-addons/pull/809 after merging it

2018-11-15 13:19 UTC, closed without merging