11.0 pos qr scan and payment
itpp-labs/pos-addons pull request #793
Opened 2018-10-18 10:50 UTC by KolushovAlexandr

2018-10-18 12:07 UTC, yelizariev requested changes

2018-10-18 12:07 UTC, yelizariev commented on pos_qr_payments/doc/changelog.rst
> +- **FIX** - Error related to pos reference in different encodings
The problem is in translation, not encoding

2018-10-18 12:07 UTC, yelizariev commented on pos_qr_payments/models/pos_order.py
> +            reference = re.search('\d{5}\-\d{3}-\d{4}', r.pos_reference)
Amount of number is minimal, not exact value

2018-10-18 12:07 UTC, yelizariev commented on pos_qr_scan/static/src/js/qr_scan.js
> +                        });
:+1:

2018-10-18 15:37 UTC, yelizariev approved these changes

2018-10-19 07:56 UTC, yelizariev commented
Checks are red :disappointed: 
```

2018-10-18 15:50:51,739 4645 ERROR openerp_test odoo.addons.pos_wechat.tests.test_wechat_order: `   File "/home/travis/build/it-projects-llc/pos-addons/pos_qr_payments/models/pos_order.py", line 16, in _compute_pos_reference_uid
2018-10-18 15:50:51,740 4645 ERROR openerp_test odoo.addons.pos_wechat.tests.test_wechat_order: `     reference = re.search(u'\d{1,}-\d{1,}-\d{1,}', r.pos_reference)
2018-10-18 15:50:51,740 4645 ERROR openerp_test odoo.addons.pos_wechat.tests.test_wechat_order: `   File "/home/travis/virtualenv/python3.5.6/lib/python3.5/re.py", line 173, in search
2018-10-18 15:50:51,740 4645 ERROR openerp_test odoo.addons.pos_wechat.tests.test_wechat_order: `     return _compile(pattern, flags).search(string)
2018-10-18 15:50:51,740 4645 ERROR openerp_test odoo.addons.pos_wechat.tests.test_wechat_order: ` TypeError: expected string or bytes-like object
```

2018-11-22 15:37 UTC, KolushovAlexandr commented
@ilmir-k Check it please

2018-11-27 12:24 UTC, Ramil-Mukhametzyanov approved these changes

2018-11-27 12:28 UTC, yelizariev commented
too red https://travis-ci.com/it-projects-llc/pos-addons/jobs/152935235

2018-12-03 11:29 UTC, yelizariev approved these changes

2018-12-03 11:30 UTC, merged