12.0 product available
itpp-labs/pos-addons pull request #801
Opened 2018-10-22 16:29 UTC by GabbasovDinar

2018-10-23 10:40 UTC, ilmir-k submitted a review, later dismissed
@GabbasovDinar  ``website`` must be link to apps store now

2018-11-13 08:04 UTC, Ramil-Mukhametzyanov requested changes
After selecting the cashier who has the permission to make payment for the out-of-stock order, the user can not set himself the cashier of the POS.
The user of POS should be set as cashier in the next sessions.

2018-11-13 08:26 UTC, Ramil-Mukhametzyanov approved these changes
I can change POS cashier manually.
Approved.

2018-11-13 09:37 UTC, yelizariev approved these changes

2018-11-14 13:36 UTC, merged