10.0 pos invoice mobile
itpp-labs/pos-addons pull request #803
Opened 2018-10-25 10:16 UTC by KolushovAlexandr

2018-10-25 12:28 UTC, GabbasovDinar requested changes

2018-10-25 12:28 UTC, GabbasovDinar commented on pos_mobile/static/src/xml/pos.xml
> +        </t>
don't replace this element

2018-10-25 12:28 UTC, GabbasovDinar commented on pos_invoice_pay/static/src/js/main.js
>  var InvoicePayment = screens.PaymentScreenWidget.extend({
why not "include" instead of "extend"?

2018-11-14 13:48 UTC, yelizariev commented
@KolushovAlexandr

2018-11-14 13:55 UTC, yelizariev commented
WIP

2018-11-20 09:30 UTC, GabbasovDinar commented
fixes here: https://github.com/it-projects-llc/pos-addons/pull/833

2018-11-26 10:23 UTC, closed without merging