12.0 multi session
itpp-labs/pos-addons pull request #809
Opened 2018-10-29 13:56 UTC by GabbasovDinar

2018-11-13 06:44 UTC, yelizariev commented
Please rebase to upstream to restart travis with proper configuration

2018-11-13 06:45 UTC, yelizariev requested changes
Code looks good, though following commit message doesn't explain why it's better

 *:heart_eyes: don't use the 'change' trigger to save to the local storage*

2018-11-13 06:46 UTC, yelizariev approved these changes

2018-11-19 13:00 UTC, Ramil-Mukhametzyanov approved these changes
No errors were found

2018-11-20 11:48 UTC, merged