10.0 pos orders history
itpp-labs/pos-addons pull request #810
Opened 2018-10-30 11:07 UTC by GabbasovDinar

2018-10-30 17:06 UTC, ilmir-k approved these changes

2018-11-14 14:01 UTC, yelizariev requested changes

2018-11-14 14:01 UTC, yelizariev commented on pos_orders_history/models/pos_orders_history_models.py
> +    load_orders_of_last_n_days = fields.Boolean("Orders of last 'n' days", default=True)
It should be False by defaul

2018-11-14 14:01 UTC, yelizariev commented on pos_orders_history_return/doc/changelog.rst
> +- **FIX:** Product price is taken from original order rather than Sale Price
It's not obvious which variant is correct and which is fixed

2018-11-14 14:01 UTC, yelizariev commented on pos_orders_history/models/pos_orders_history_models.py
> +    load_orders_of_last_n_days = fields.Boolean("Orders of last 'n' days", default=True)
load_limit_orders or something like that sounds better IMO

2018-11-15 12:53 UTC, GabbasovDinar commented on pos_orders_history/models/pos_orders_history_models.py
> +    load_orders_of_last_n_days = fields.Boolean("Orders of last 'n' days", default=True)
@yelizariev Why? We need to load all orders for a specified number of days, not for a specified number of orders

2018-11-15 12:57 UTC, GabbasovDinar commented on pos_orders_history/models/pos_orders_history_models.py
> +    load_orders_of_last_n_days = fields.Boolean("Orders of last 'n' days", default=True)
@yelizariev I think first of all that **load_limit_orders** means to load a specified number of orders

2018-11-16 13:36 UTC, yelizariev approved these changes

2018-11-16 13:37 UTC, merged