11.0 42288143e4765d33a21e8e4c12fe55c3bdf41d78
itpp-labs/pos-addons pull request #817
Opened 2018-11-01 13:29 UTC by Rusllan

Merging 10.0 in 11.0

2018-11-09 10:32 UTC, yelizariev requested changes

2018-11-09 10:32 UTC, yelizariev commented on pos_product_available_negative/__openerp__.py
> +}
Wrong

2018-11-09 10:32 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +- **FIX:** Don't make automatic scrolling of the current order on changing other orders
Someone has to check that it works in odoo 11

2018-11-09 10:32 UTC, yelizariev commented on pos_mobile_restaurant/doc/changelog.rst
> +- **FIX:** The menu is not opened after changing a floor
Someone has to check that it works in odoo 11

2018-11-09 10:32 UTC, yelizariev commented on pos_mobile/doc/changelog.rst
> +- **FIX:** Scrollbar of Products after opening bottom menu
Someone has to check that it works in odoo 11

2018-11-09 10:32 UTC, yelizariev commented on pos_debt_notebook_sync/doc/changelog.rst
> +- **FIX:** Endless update requests on the customer screen after renamings in pos_longpolling
Someone has to check that it works in odoo 11

2018-11-09 10:32 UTC, yelizariev commented on pos_debt_notebook/doc/changelog.rst
> +
Someone has to check that it works in odoo 11

2018-11-16 14:11 UTC, Ramil-Mukhametzyanov reviewed
:+1:  **FIX:** Don't make automatic scrolling of the current order on changing other orders

2018-11-16 14:26 UTC, Ramil-Mukhametzyanov reviewed
:+1: **FIX:** The menu is not opened after changing a floor

2018-11-16 14:40 UTC, Ramil-Mukhametzyanov reviewed
pos_mobile
:+1:  **FIX:** Order list scrolling
:+1:  **FIX:** Scrollbar of Products after opening bottom menu

2018-11-16 14:42 UTC, Ramil-Mukhametzyanov reviewed
pos_mobile
:-1:  **FIX:** Font size of buttons

2018-11-16 14:49 UTC, Ramil-Mukhametzyanov reviewed
:+1:  **FIX:** Endless update requests on the customer screen after renamings in pos_longpolling

2018-11-19 13:15 UTC, ilmir-k requested changes
Validation error when trying to add a partner to _Write-off Credits_ wizard

2018-12-07 10:49 UTC, Ramil-Mukhametzyanov commented on hw_twitter_printing/__manifest__.py
> +    "version": "10.0.1.0.0",
should be 11.0.1.0.0

2018-12-10 08:53 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/doc/changelog.rst
> +- **FIX:** Don't make automatic scrolling of the current order on changing other orders
> Someone has to check that it works in odoo 11

:+1:

2018-12-10 09:10 UTC, Ramil-Mukhametzyanov commented on pos_mobile/doc/changelog.rst
> +- **FIX:** Scrollbar of Products after opening bottom menu
:+1:

2018-12-10 09:17 UTC, Ramil-Mukhametzyanov commented on pos_debt_notebook_sync/doc/changelog.rst
> +- **FIX:** Endless update requests on the customer screen after renamings in pos_longpolling
:+1:

2018-12-10 10:40 UTC, Ramil-Mukhametzyanov commented on pos_debt_notebook/doc/changelog.rst
> +
:+1:  **NEW:** Wizard allow to create invoices for sets of partners: `Balance update`, `New Balance`
:+1:  **FIX:** Error related to paying with not discount credit journals in POS
:+1:  **FIX:** Invoices paid with credit journals now counts in partner debts

2018-12-10 11:01 UTC, Ramil-Mukhametzyanov approved these changes

2018-12-10 11:06 UTC, GabbasovDinar approved these changes

2018-12-10 11:16 UTC, merged