:ambulance: Orders history is not updated instantly
itpp-labs/pos-addons pull request #843
Opened 2018-11-22 12:14 UTC by GabbasovDinar

2018-11-22 13:54 UTC, ilmir-k approved these changes

2018-11-23 13:34 UTC, yelizariev requested changes

2018-11-23 13:34 UTC, yelizariev commented on pos_orders_history/static/src/js/screens.js
> +            return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds())).toLocaleString();
What the hell? Can simply use ``d.toLocaleString();``

2018-11-25 10:33 UTC, GabbasovDinar commented on pos_orders_history/static/src/js/screens.js
> +            return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds())).toLocaleString();
![image](https://user-images.githubusercontent.com/15119940/48978037-76609780-f0c7-11e8-8ed3-38d827c625b0.png)

2018-11-26 07:15 UTC, yelizariev commented on pos_orders_history/static/src/js/screens.js
> +            return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds())).toLocaleString();
Do you agree or not?

2018-11-26 08:04 UTC, GabbasovDinar commented on pos_orders_history/static/src/js/screens.js
> +            return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds())).toLocaleString();
@yelizariev No

2018-11-26 08:13 UTC, yelizariev commented on pos_orders_history/static/src/js/screens.js
> +            return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds())).toLocaleString();
`utc =  new Date(d.getTime() + d.getTimezoneOffset() * 60000)`

2018-11-26 08:39 UTC, GabbasovDinar commented
@yelizariev DONE

2018-11-30 08:49 UTC, ilmir-k commented
@yelizariev can we proceed?

2018-11-30 09:21 UTC, yelizariev approved these changes

2018-11-30 09:22 UTC, merged