:arrow_up::one::two: pos_orderline_absolute_discount
itpp-labs/pos-addons pull request #847
Opened 2018-11-27 09:48 UTC by GabbasovDinar

2018-11-27 14:50 UTC, Ramil-Mukhametzyanov approved these changes

2018-11-28 11:23 UTC, yelizariev requested changes

2018-11-28 11:23 UTC, yelizariev commented on pos_orderline_absolute_discount/static/description/index.html
> +                <!--</div>-->
Don't update each line

2018-11-28 12:14 UTC, yelizariev commented on pos_debt_notebook/static/description/index.html
> +                </div>-->
No need to change it

2018-11-28 12:18 UTC, GabbasovDinar commented on pos_orderline_absolute_discount/static/description/index.html
> +                <!--</div>-->
DONE

2018-11-29 11:53 UTC, yelizariev requested changes

2018-11-29 11:53 UTC, yelizariev commented on pos_orderline_absolute_discount/static/description/index.html
> +                             -ms-transform: rotate(-7deg);">
Thanks, but spaces are not needed

2018-11-29 12:16 UTC, GabbasovDinar commented on pos_orderline_absolute_discount/static/description/index.html
> +                             -ms-transform: rotate(-7deg);">
@yelizariev DONE

2018-12-18 13:11 UTC, yelizariev approved these changes
Code LGTM

2018-12-19 08:54 UTC, merged