:ambulance: Incorrect popup open to indicate number of guests
itpp-labs/pos-addons pull request #849
Opened 2018-11-28 09:20 UTC by GabbasovDinar

2018-11-28 11:07 UTC, Ramil-Mukhametzyanov approved these changes

2018-11-28 11:29 UTC, yelizariev requested changes

2018-11-28 11:29 UTC, yelizariev commented on pos_product_category_discount/doc/changelog.rst
> +- **FIX:** Incorrect popup open to indicate number of guests
When?

2018-11-28 12:41 UTC, GabbasovDinar commented on pos_product_category_discount/doc/changelog.rst
> +- **FIX:** Incorrect popup open to indicate number of guests
DONE

2018-11-29 11:48 UTC, yelizariev approved these changes

2018-11-29 11:49 UTC, yelizariev commented
There are errors in tests

2018-11-30 10:53 UTC, yelizariev commented
Still doesn't work

2018-12-18 13:13 UTC, yelizariev approved these changes

2018-12-18 13:14 UTC, merged