Revert ":zap: orders_history update list button"
itpp-labs/pos-addons pull request #856
Opened 2018-12-04 12:02 UTC by GabbasovDinar

This reverts commit 033664556c12999f78a334dee5745629a0450d1c.

I think we don't need to use the changes. These changes are not needed because all updates should come instantly. Also, this module in pos-addons v 10.0 has changes https://github.com/it-projects-llc/pos-addons/commit/8d386d0c6002d52524ee04a9e657c841f0d63b9d#diff-6200f6049d7dfe741e4966628ac47a31 which fix some problems of instant updates. In any case, you must test with changes from 10.0 before you can accept the PR.

2018-12-04 12:08 UTC, GabbasovDinar commented
CC: @yelizariev @ilmir-k @KolushovAlexandr

2019-01-14 14:28 UTC, Ramil-Mukhametzyanov approved these changes

2019-01-14 14:45 UTC, yelizariev requested changes
You still need to add changelog

2019-01-15 09:13 UTC, GabbasovDinar commented
> You still need to add changelog

@yelizariev About what?

2019-03-25 16:52 UTC, yelizariev requested changes

2019-03-25 16:52 UTC, yelizariev commented on pos_orders_history/doc/changelog.rst
> +**Fix:** Orders history has not been updated instantly
Wrong tense I think. Also, you said in PR it's not needed, but here you state that it didn't work. Please clarify

2019-03-28 14:10 UTC, yelizariev approved these changes

2019-03-28 14:27 UTC, ilmir-k approved these changes

2019-03-29 09:21 UTC, merged