12.0 461c741345fbdeaf2d736c2f2913297080204555
itpp-labs/pos-addons pull request #861
Opened 2018-12-10 12:55 UTC by Rusllan

2018-12-11 10:31 UTC, GabbasovDinar commented on pos_debranding/doc/changelog.rst
> +- **Init version**
:+1:

2018-12-11 10:38 UTC, GabbasovDinar commented on pos_debt_notebook/doc/changelog.rst
> +
:+1:

2018-12-11 10:39 UTC, GabbasovDinar commented on pos_debt_notebook_sync/doc/changelog.rst
> +
:+1:

2018-12-11 10:45 UTC, GabbasovDinar commented on pos_mobile/doc/changelog.rst
> +
:+1:

2018-12-11 10:46 UTC, GabbasovDinar commented on pos_mobile_restaurant/doc/changelog.rst
> +
:+1:

2018-12-11 10:51 UTC, GabbasovDinar commented on pos_multi_session/doc/changelog.rst
> +
:+1:

2018-12-11 11:04 UTC, GabbasovDinar commented on pos_multi_session_restaurant/doc/changelog.rst
> +
:+1:

2018-12-11 11:08 UTC, GabbasovDinar commented on pos_orders_history/doc/changelog.rst
> +
:+1:

2018-12-11 11:09 UTC, GabbasovDinar commented on pos_orders_history_reprint/doc/changelog.rst
> +
:+1:

2018-12-11 11:12 UTC, GabbasovDinar commented on pos_orders_history_return/doc/changelog.rst
> +
> **FIX:** Not correctly a product price when returning an order (the Sale Price of the product is used instead of the price from the Original Order).

:-1:

2018-12-11 11:14 UTC, GabbasovDinar commented on pos_product_available/doc/changelog.rst
> +
:+1:

2018-12-11 11:14 UTC, GabbasovDinar commented on pos_restaurant_base/doc/changelog.rst
> +
:+1:

2018-12-11 11:54 UTC, GabbasovDinar commented on pos_orders_history_return/doc/changelog.rst
> +
DONE

2018-12-12 08:43 UTC, Ramil-Mukhametzyanov commented on hw_twitter_printing/__manifest__.py
> +    "version": "11.0.1.0.0",
Should be 12.0.1.0.0

2018-12-12 08:46 UTC, Ramil-Mukhametzyanov commented on pos_fiscal_current/__manifest__.py
> +    'version': '10.0.1.0.0',
Should be 12.0.1.0.0

2018-12-12 08:49 UTC, Ramil-Mukhametzyanov commented on pos_fiscal_floor/__manifest__.py
>      'author': 'IT-Projects LLC',
Should be 12.0.1.0.1

2018-12-12 08:49 UTC, Ramil-Mukhametzyanov commented on pos_invoice_pay/__manifest__.py
>      "application": False,
Should be 12.0.1.2.0

2018-12-12 09:33 UTC, Ramil-Mukhametzyanov requested changes
After selecting a customer, the discount program disappears in the final receipt (including the case of  using a credit method payments)

2018-12-12 09:39 UTC, GabbasovDinar commented
@Ramil-Mukhametzyanov 
![image](https://user-images.githubusercontent.com/15119940/49860486-afb13b00-fe1b-11e8-9dc5-609713335565.png)

2018-12-12 13:10 UTC, Ramil-Mukhametzyanov approved these changes

2018-12-12 14:19 UTC, Ramil-Mukhametzyanov requested changes
POS order product categories does not work

2018-12-12 14:57 UTC, Ramil-Mukhametzyanov requested changes
Order transfer tickets cannot be printed when an order is moved to another table.

2018-12-13 13:10 UTC, Ramil-Mukhametzyanov approved these changes

2018-12-13 13:31 UTC, yelizariev commented
Error in travis:
```

.button.next.highlight:contains("Set Customer") succeeded
2018-12-13 12:31:19,368 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:19] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.008 0.022
2018-12-13 12:31:19,385 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:19] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:20,310 6552 INFO openerp_test odoo.addons.pos_debt_notebook_sync.tests.test_debt_sync.TestUi: console log: Tour tour_pos_debt_notebook: step .order-button.selected succeeded
2018-12-13 12:31:20,428 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:20] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.009 0.025
2018-12-13 12:31:20,440 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:20] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.005
2018-12-13 12:31:21,322 6552 INFO openerp_test odoo.addons.pos_debt_notebook_sync.tests.test_debt_sync.TestUi: console log: Tour tour_pos_debt_notebook: step .product-screen .actionpad .pay succeeded
2018-12-13 12:31:21,481 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:21] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.007 0.019
2018-12-13 12:31:21,504 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:21] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:22,557 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:22] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.008 0.028
2018-12-13 12:31:22,574 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:22] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:23,636 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:23] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.020 0.022
2018-12-13 12:31:23,650 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:23] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.007
2018-12-13 12:31:24,691 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:24] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.008 0.020
2018-12-13 12:31:24,718 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:24] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.002 0.013
2018-12-13 12:31:25,751 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:25] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.007 0.018
2018-12-13 12:31:25,778 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:25] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.002 0.008
2018-12-13 12:31:26,819 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:26] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.015 0.018
2018-12-13 12:31:26,834 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:26] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:27,875 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:27] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.014 0.018
2018-12-13 12:31:27,895 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:27] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:28,951 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:28] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.013 0.026
2018-12-13 12:31:28,968 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:28] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.009
2018-12-13 12:31:30,018 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:30] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.011 0.026
2018-12-13 12:31:30,030 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:30] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:31,082 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:31] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.015 0.026
2018-12-13 12:31:31,100 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:31] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.009
2018-12-13 12:31:32,133 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:32] "POST /web/dataset/call_kw/res.partner/debt_history HTTP/1.1" 200 - 11 0.008 0.017
2018-12-13 12:31:32,154 6552 INFO openerp_test werkzeug: 127.0.0.1 - - [13/Dec/2018 12:31:32] "POST /pos_longpolling/update HTTP/1.1" 200 - 5 0.001 0.006
2018-12-13 12:31:32,326 6552 INFO openerp_test odoo.addons.pos_debt_notebook_sync.tests.test_debt_sync.TestUi: console log: _check_for_tooltip
2018-12-13 12:31:32,330 6552 INFO openerp_test odoo.addons.pos_debt_notebook_sync.tests.test_debt_sync.TestUi: console log: - modal_displayed: 0
2018-12-13 12:31:32,339 6552 INFO openerp_test odoo.addons.pos_debt_notebook_sync.tests.test_debt_sync.TestUi: console log: - trigger '.modal-dialog.cashier .selection-item:contains("Mitchell Admin")': 0
2018-12-13 12:31:32,347 6552 INFO openerp_test odoo.addons.pos_debt_notebook_sync.tests.test_debt_sync.TestUi: console log: - visible trigger '.modal-dialog.cashier .selection-item:contains("Mitchell Admin")': 0


</div><div class="modal-dialog oe_hidden" role="dialog">
<div class="popup popup-barcode">
<header class="title">Unknown Barcode
<br>
<span class="barcode"></span>
</header>
<main class="body">
The Point of Sale could not find any product, client, employee
or action associated with the scanned barcode.
</main>
<footer class="footer">

```

2018-12-14 08:39 UTC, yelizariev commented on pos_debt_notebook/static/src/js/test_pos_debt.js
> +        if (odoo._modules.indexOf('pos_cashier_select') !== -1) {
This may not work on running tests. Try ``'pos_choosing_cashier' in odoo.__DEBUG__.services``

2018-12-17 09:05 UTC, GabbasovDinar approved these changes

2018-12-17 11:35 UTC, merged