:heart_eyes: compatibility with pos_order_receipt_custom
itpp-labs/pos-addons pull request #876
Opened 2018-12-20 10:55 UTC by GabbasovDinar

2018-12-20 13:23 UTC, Ramil-Mukhametzyanov requested changes
In the case of two active multisessions with configured order printers, two TRANSFER orders are printed.
In one session (Admin) do the following:
1. Add item, print -> printed NEW
2. Add item, print -> printed ADD
3. Remove the last item, print -> printed CANCEL
4. Change table -> 
printed TRANSFER (Printer Waiter: Demo User)
and another TRANSFER (Printer Waiter: Administrator)

2018-12-20 13:34 UTC, Ramil-Mukhametzyanov requested changes
1. Add item in order in the session of Admin. Print order.
2. Move this order to the another table in the session of Demo
    Result: on TRANSFER ticket Printer waiter: Administrator (expected Demo)
If create an order by Demo, and then transfer it by Administrator, the value of Printer waiter on the TRANSFER ticket will be Demo.

2018-12-20 13:43 UTC, Ramil-Mukhametzyanov requested changes
The order button is active for other user after the transfer.

2018-12-20 13:47 UTC, Ramil-Mukhametzyanov requested changes
1. Add item by Demo, print -> printed NEW
2. Add item, by Administrator, print ->
     printed NEW (expected ADD)

2018-12-21 09:46 UTC, GabbasovDinar commented
@Ramil-Mukhametzyanov I fixed the problems

2018-12-21 11:50 UTC, Ramil-Mukhametzyanov requested changes
Lost of synchronization.

Demo:
   1. Select a table.
Admin: 
   2. Open the same table and the same tab
   3. Add an item, print order (click Order)
   4. Move the order to another table
Can see: the table is changed for Demo too.
Demo:
   5. Destroy the order (click '-')
Result: the order is not destroyed in session of Admin

2018-12-21 12:25 UTC, Ramil-Mukhametzyanov reviewed
In the last described case, it is best to print a CANCEL order and delete the order.

2018-12-24 08:13 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_restaurant/__manifest__.py
> +    "version": "12.0.3.2.6",
Here is a mistake: Odoo version is 10.0, not 12.0

2018-12-24 14:26 UTC, Ramil-Mukhametzyanov requested changes
1. Create an order by Demo, print order
    In my example the order 00001-001-0001, Main Floor/T1
2. Find the order by Admin and delete it (destroy by clicking '-')
3. Create new order by Admin, print order
    In my example it was 00002-001-002, Main Floor/T2 (Extra Flandria chicory 1kg)
4. Destroy it by Admin.
5. Click on a table in the Demo's session
    I clicked on the table T3
Result:
    The TRANSFER order is printed
    In my case, it was 00002-001-0002 Main Floor/T2>>>Main Floor/T3 (Extra Flandria chicory 1kg)

It is better to do following oprations after clicking '-' button (if pos_order_receipt_custom module is installed):
1. deletion all the lines (as we click 'delete lines' button)
2. print CANCEL order
3. and the destroy the empty order.

2018-12-26 10:29 UTC, Ramil-Mukhametzyanov requested changes
After the last modification, the new order will not appear to another multi-session user.

2018-12-26 12:14 UTC, Ramil-Mukhametzyanov requested changes
After completing the above steps, any NEW orders will no longer print.

2018-12-26 14:41 UTC, Ramil-Mukhametzyanov approved these changes

2018-12-27 06:57 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                this.order_to_transfer_to_different_table = null;
Why this cannot be done in the module pos_order_receipt_custom?

2018-12-27 07:16 UTC, yelizariev requested changes
Надо из мульти-сессии убрать код, который чисто под pos_order_receipt_custom сделан

2018-12-27 09:07 UTC, yelizariev approved these changes
Looks better

2018-12-27 09:07 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +            // the order has been transferred to another table
Either say "Check that the order has been ..." or move it inside if-block

2018-12-27 09:26 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/static/src/js/pos_multi_session.js
> +                    if (this.get('orders').size() === 0 && this.gui.get_current_screen() !== "floors") {
We need changelog and manifest updates for pos_multi_session

2018-12-27 09:59 UTC, Ramil-Mukhametzyanov requested changes
After the following steps are performed, the an opened order is displayed in the Admin's POS.
Demo:
1    Select a table.
Admin:
2    Open the same table and the same tab
3    Add an item (for example, Boni Oranges 1kg), print order (click Order)
4    Move the order to another table
Can see: the table is changed for Demo too.
Demo:
5   Destroy the order (click '-')
Result: an open order is displayed in the current table of Admin (even if the order is in another table)
The order payment from this table is successful (receipt data is correct).
But if the order has the same products (for example, Boni oranges 1kg), it may be confusing.

It is best to leave the table.

2018-12-27 10:07 UTC, GabbasovDinar commented
@Ramil-Mukhametzyanov This problem does not related to this PR

2018-12-27 11:41 UTC, Ramil-Mukhametzyanov approved these changes
ok

2018-12-28 06:22 UTC, merged