10.0 pos orders history imp
itpp-labs/pos-addons pull request #887
Opened 2018-12-27 14:27 UTC by GabbasovDinar

2018-12-28 10:45 UTC, ilmir-k approved these changes

2018-12-28 13:47 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/static/src/js/screens.js
> +                    new Model('pos.order').call('search_read', [[['pos_reference', '=', 'Order ' + code.code]]]).then(function(o) {
This part can cause incompatible problems in the non-English interface.
Do not use the word 'Order'.

2018-12-28 13:56 UTC, Ramil-Mukhametzyanov requested changes
if using 'Load Specific Orders only'
1. Can't find any orders in the history by searching. I used this example 'Order 00001-001-0001'
2. Scanning '00001-001-0001' will cause the error
    Error: Could not search the Order
    There is no order with this barcode
If this option is not used, the order is successfully found.

2018-12-28 14:06 UTC, Ramil-Mukhametzyanov approved these changes
Understand this feature

2018-12-28 16:02 UTC, KolushovAlexandr approved these changes

2018-12-28 16:02 UTC, KolushovAlexandr commented on pos_orders_history/static/src/js/screens.js
> +                            'title': _t('Error: Could not search the Order'),
```suggestion
                            'title': _t('Error: Could not find the Order'),
```

2018-12-28 16:02 UTC, KolushovAlexandr commented on pos_orders_history/static/src/js/screens.js
> +                                'title': _t('Error: Could not search the Order'),
```suggestion
                                'title': _t('Error: Could not find the Order'),
```

2018-12-29 10:49 UTC, Ramil-Mukhametzyanov requested changes
Remove the word 'Order' from the order in the search string that appears in the history after scanning

2019-01-09 09:26 UTC, ilmir-k commented
What is the progress on this PR?

2019-01-09 14:39 UTC, GabbasovDinar commented
@ilmir-k @Ramil-Mukhametzyanov You can check a new feature https://github.com/it-projects-llc/pos-addons/pull/887/commits/bcd5683816eb80f3b49687baa14ddac5d1302218 and then merge the PR

2019-01-10 13:07 UTC, Ramil-Mukhametzyanov approved these changes

2019-01-10 13:10 UTC, merged