10.0 pos debt issues
itpp-labs/pos-addons pull request #889
Opened 2018-12-28 10:19 UTC by KolushovAlexandr

2018-12-28 11:13 UTC, Ramil-Mukhametzyanov requested changes
Unable to purchase a credit
1. Add 'Credit top-up' for $100
2. Choose a customer
3. Select Cash payment method for $100
Result: a message 'Use an another non-discount payment method'

2019-01-10 08:09 UTC, Ramil-Mukhametzyanov requested changes
Cannot withdraw from Credit (Friuts&Vegatables) using "Pay Debt" product
1. Edit the payment method : disable "Zero transaction", enable "Allow to cash out credits" .
2. Add the product "Pay Debt", select a customer, click "Payment"
3. Select the payment method , set a value
4. Select a payment method where to withdraw. Click "Validate".
Result: error message "You may only buy Fruits and Vegetables..."

2019-01-10 08:37 UTC, Ramil-Mukhametzyanov requested changes
Can withdraw from a credit more than available
1. Edit the payment method : disable "Zero transaction", disable "Allow to cash out credits" .
2. Add the product "Pay Debt", select a customer, click "Payment"
3. Select the payment method , set a value more than available
4. Select a payment method where to withdraw. Click "Validate".
    Result: Success. Should not to be.
I transfered from "Credit" to "Credit (Fruits & Vegetables)".

2019-01-10 12:29 UTC, Ramil-Mukhametzyanov requested changes
1. Open POS
2. Select a product that is not from the category "Fruits & Vegatable" (Acsone.eu 1 Unit)
3. Select a customer
4. Click Payment
5. Click on Credit (Friuts & Vegetables only)
6. Payment
Result: succeess. POS should cause an error.

2019-01-11 08:07 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            return download_debts_ready;
This update is not covered in changelog

2019-01-11 08:19 UTC, yelizariev commented on pos_debt_notebook/static/src/js/pos.js
> +            if (allowed_products.length === order.get_orderlines().length || this.cash_out_check()) {
It's actually allowed_lines rather than allowed products

2019-01-11 09:57 UTC, yelizariev approved these changes

2019-01-11 12:29 UTC, Ramil-Mukhametzyanov approved these changes

2019-01-11 12:29 UTC, merged