11.0 cde969b8ac74599a25bc172bbbe756ff6212ff8b
itpp-labs/pos-addons pull request #895
Opened 2018-12-29 08:36 UTC by GabbasovDinar

2018-12-29 11:33 UTC, yelizariev requested changes

2018-12-29 11:33 UTC, yelizariev commented on README.md
> +[![Build Status](https://travis-ci.com/it-projects-llc/pos-addons.svg?branch=10.0)](https://travis-ci.com/it-projects-llc/pos-addons)
```suggestion
[![Build Status](https://travis-ci.com/it-projects-llc/pos-addons.svg?branch=11.0)](https://travis-ci.com/it-projects-llc/pos-addons)
```

2018-12-29 11:33 UTC, yelizariev commented on pos_invoice_pay/doc/changelog.rst
> +**Fix:** Incorrect receipt printing in the PosBox
It must be new version 1.2.1

2018-12-29 11:33 UTC, yelizariev commented on pos_mobile_restaurant/__manifest__.py
> +    "version": "10.0.1.3.8",
:-1:

2018-12-29 12:40 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_restaurant/doc/changelog.rst
> +
> Someone has to test it

:+1:

2018-12-29 12:40 UTC, Ramil-Mukhametzyanov commented on pos_order_receipt_custom/doc/changelog.rst
> +
> Someone has to test it

:+1:

2018-12-29 12:43 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +
> Someone has to test it

:+1:

2018-12-29 12:43 UTC, Ramil-Mukhametzyanov commented on pos_receipt_custom_template/doc/changelog.rst
> +
> Someone has to test it

:+1:

2018-12-29 12:49 UTC, yelizariev approved these changes

2018-12-29 12:49 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +**Fix:** Do not create a new order after removing the last order from another POS if you are on the Floor
It must be new version here

2018-12-29 12:49 UTC, yelizariev commented on pos_multi_session_restaurant/doc/changelog.rst
> +
@Ramil-Mukhametzyanov Do you want to say that you have tested it?

2018-12-29 12:57 UTC, Ramil-Mukhametzyanov requested changes
Steps:
1. Fetch Orders
2. Select an Order (SO008 China Export)
3. Create Invoice
! There is no the customer
4. Click payment method (Cash)
5. Enter value, click Validate
Error: Excessive payment amount - You can not validate the order with a change because difference account is not set. ... exact amount
! Cannot make payment
! There is no difference account in the Payments section of the POS settings
6. Enter exact value, click Validate
Error: "empty order"
! Cannot make payment
! List of the orders is empty after these steps

2019-01-09 14:43 UTC, GabbasovDinar commented
@Ramil-Mukhametzyanov Can you check again? I could not reproduce the error with the latest updates.

2019-01-10 14:31 UTC, Ramil-Mukhametzyanov requested changes
Fetch Invoices->Select an invoice->Register Payment
Tendered is not 0 (value from a prevoious payment)

2019-01-10 14:32 UTC, Ramil-Mukhametzyanov approved these changes
Skip it for now

2019-01-10 14:33 UTC, merged