[10.0] compatibility with pos_category_multi
itpp-labs/pos-addons pull request #898
Opened 2019-01-10 15:15 UTC by GabbasovDinar

2019-01-14 07:40 UTC, Ramil-Mukhametzyanov requested changes
Installed pos_categ_multi & pos_order_cancel_restaurant 
1. Create a category: Fruits (parent category = Fruits&Vegetables)
2. Assign the category to a product: Orange (<-Fruits)
3. Enter POS, create an order : Oranges
4. Click Order
Result: error "line.product.pos_categ_id is undefined".

2019-01-14 12:52 UTC, Ramil-Mukhametzyanov approved these changes

2019-01-15 10:25 UTC, Ramil-Mukhametzyanov requested changes
manifest and Changelog for  pos_order_printer_product

2019-01-15 10:26 UTC, yelizariev approved these changes
I'd make shared code about categories and put it to some pos_base module. But ok for now

2019-01-15 13:30 UTC, Ramil-Mukhametzyanov approved these changes

2019-01-15 14:35 UTC, merged