:zap: New button to add all partners with debts, availability to upda…
itpp-labs/pos-addons pull request #912
Opened 2019-01-28 11:53 UTC by KolushovAlexandr

…te credits via Manual Credit Updates

2019-01-29 06:21 UTC, yelizariev requested changes

2019-01-29 06:21 UTC, yelizariev commented on pos_debt_notebook/wizard/pos_credit_invoices.py
> +                                  help='Otherwise it will be executed via "Manual Credit Updates"')
Consider to use Selection instead.

2019-01-29 06:21 UTC, yelizariev commented on pos_debt_notebook/wizard/pos_credit_invoices_views.xml
> +                        attrs="{'invisible':[('update_type', '=', 'balance_update')]}"/>
Why just don't make a checkbox? Handling a thousand partners via ui could slow the workflow down

2019-03-08 21:58 UTC, KolushovAlexandr commented on pos_debt_notebook/wizard/pos_credit_invoices_views.xml
> +                        attrs="{'invisible':[('update_type', '=', 'balance_update')]}"/>
As it appeared, the implemented method is more convenient, when you need to specify all partners except, for example, two ones.

2019-03-14 22:09 UTC, merged