:ambulance: fix compatibility POS modules
itpp-labs/pos-addons pull request #916
Opened 2019-01-29 09:29 UTC by GabbasovDinar

2019-01-29 11:37 UTC, Ramil-Mukhametzyanov requested changes
If I enter a numeric value for the discount percentage, the discount product will appear in the product list.

![misc](https://user-images.githubusercontent.com/33877236/51905553-57da8d80-23e3-11e9-9d03-16d2ed7a732d.jpeg)

2019-01-29 12:00 UTC, GabbasovDinar commented
> If I enter a numeric value for the discount percentage, the discount product will appear in the product list.

it's a pos_discount module (module by Odoo)

2019-01-29 12:54 UTC, Ramil-Mukhametzyanov approved these changes
@yelizariev please check

2019-01-29 14:53 UTC, yelizariev requested changes
Try to hide discount product via qweb instead

2019-01-29 14:53 UTC, yelizariev commented on pos_product_category_discount/static/src/js/widgets.js
> +            this.product_list.push(discount_product);
:-1:

2019-01-30 09:38 UTC, Ramil-Mukhametzyanov approved these changes

2019-01-30 09:38 UTC, Ramil-Mukhametzyanov commented on pos_order_receipt_custom/doc/changelog.rst
> +**Fix:** The error of adding products if the pos_restaurant module is installed (when there are no floors in the restaurant)
:+1: approved

2019-01-30 09:41 UTC, Ramil-Mukhametzyanov requested changes
broken discount program interface in my mozilla browser
![df](https://user-images.githubusercontent.com/33877236/51972208-ba439480-249c-11e9-9291-d4a09d88c0cd.jpeg)
If it's the same in Chrome, please fix it

2019-01-30 10:01 UTC, Ramil-Mukhametzyanov requested changes
Another error in POS multisession after deleting floors
![self floor is undefined](https://user-images.githubusercontent.com/33877236/51973353-3e971700-249f-11e9-8bba-81345b031bf5.jpeg)
The error occurs after entering the POS, but I did not see it in my first entrance.

2019-01-31 10:40 UTC, Ramil-Mukhametzyanov approved these changes
I can't reproduce the error "self.floors[0] is undefined".
Skip it for now.
All other changes are good.
@yelizariev please check again

2019-01-31 10:55 UTC, yelizariev requested changes

2019-01-31 10:55 UTC, yelizariev commented on pos_product_category_discount/static/src/js/widgets.js
> +                $(res).addClass('oe_hidden');
:-1:

2019-02-04 13:09 UTC, Ramil-Mukhametzyanov approved these changes
@yelizariev

2019-02-04 15:11 UTC, yelizariev approved these changes

2019-02-05 06:54 UTC, merged