11.0 6f3ec0a690fe100ed417fe0da020eca1527dd8fe
itpp-labs/pos-addons pull request #918
Opened 2019-02-04 11:49 UTC by GabbasovDinar

2019-02-04 14:00 UTC, Ramil-Mukhametzyanov commented on pos_mobile_restaurant/__manifest__.py
>      "application": False,
Incorrect change

2019-02-04 14:25 UTC, Ramil-Mukhametzyanov requested changes
I paid for Ekomurz.nl (Pos Category: Partner Services) using Credit (Fruits & Vegetables only)
![fruit credit](https://user-images.githubusercontent.com/33877236/52213996-70024f00-28b2-11e9-8bb6-5961f7b442b1.jpeg)

2019-02-06 14:54 UTC, Ramil-Mukhametzyanov reviewed
The last error has been fixed.

2019-02-11 13:11 UTC, Ramil-Mukhametzyanov requested changes
multi_session does not work

2019-02-11 13:44 UTC, Ramil-Mukhametzyanov requested changes
pos_multi_session and pos_printer_network become uncompatible.
Set printer to Admin's POS and enter. Then after enter to Demo's POS, an error occurs.

![urlindexof](https://user-images.githubusercontent.com/33877236/52566875-aef15100-2e2c-11e9-8122-ee09e3eb7178.jpg)

2019-02-12 12:18 UTC, Ramil-Mukhametzyanov approved these changes

2019-02-12 12:19 UTC, Ramil-Mukhametzyanov reviewed
@yelizariev @ilmir-k 
please check it

2019-02-13 13:04 UTC, ilmir-k approved these changes

2019-02-13 13:42 UTC, merged