11.0 scan ref porting
itpp-labs/pos-addons pull request #920
Opened 2019-02-08 08:53 UTC by Ommo73

2019-02-08 13:06 UTC, KolushovAlexandr requested changes

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/README.rst
> +This module fix this behaviour. It can be usefull if you use "Internal Reference" field for barcodes, because you have products with a different type of barcodes (e.g. EAN8, JPC, UPC, GTIN, etc.) and
11 - 13 lines would be better to write smth like this:
The module provides a feature to search a product in POS by its "Internal Reference"

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/__manifest__.py
> +# License LGPL-3.0 (https://www.gnu.org/licenses/lgpl.html).
I'm sure that someone is missing here. In the older version the manifest file was called 'openerp', so look for original file and developer

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/__init__.py
> +# License LGPL-3.0 (https://www.gnu.org/licenses/lgpl.html).
empty line at the end of the file is required

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/doc/changelog.rst
according to template a comment about initial version is needed

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/pos.js
> +        options = options || {};
Do not totally redefine any methods. It makes the module incompatible with another. Use super method, if its impossible then explain why

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/pos.js
> +    scan: function(code){
Do not totally redefine any methods. It makes the module incompatible with another. Use super method, if its impossible then explain why

2019-02-08 13:06 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/pos.js
> +    add_products: function(products){
Do not totally redefine any methods. It makes the module incompatible with another. Use super method, if its impossible then explain why

2019-02-11 09:20 UTC, Ommo73 commented on pos_scan_ref/static/src/js/pos.js
> +    scan: function(code){
In this case, it is impossible to use "super", because I am changing the logical expression that already exists in the method.

2019-02-11 09:20 UTC, Ommo73 commented on pos_scan_ref/static/src/js/pos.js
> +    add_products: function(products){
In this case, it is impossible to use "super", because I am changing the logical expression that already exists in the method.

2019-02-11 09:21 UTC, Ommo73 commented on pos_scan_ref/static/src/js/pos.js
> +        options = options || {};
I corrected it

2019-02-11 09:21 UTC, Ommo73 commented on pos_scan_ref/doc/changelog.rst
I corrected it

2019-02-11 09:21 UTC, Ommo73 commented on pos_scan_ref/__init__.py
> +# License LGPL-3.0 (https://www.gnu.org/licenses/lgpl.html).
I corrected it

2019-02-11 09:21 UTC, Ommo73 commented on pos_scan_ref/__manifest__.py
> +# License LGPL-3.0 (https://www.gnu.org/licenses/lgpl.html).
I corrected it

2019-02-11 09:21 UTC, Ommo73 commented on pos_scan_ref/README.rst
> +This module fix this behaviour. It can be usefull if you use "Internal Reference" field for barcodes, because you have products with a different type of barcodes (e.g. EAN8, JPC, UPC, GTIN, etc.) and
I corrected it

2019-02-14 15:31 UTC, KolushovAlexandr approved these changes

2019-02-14 15:31 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/pos.js
> +            return false;
correct the alignment

2019-02-14 15:31 UTC, KolushovAlexandr commented on pos_scan_ref/doc/index.rst
>   FIX searching product by ref in POS
I would suggest discussing the module name with Ilmir

2019-02-15 09:58 UTC, Ramil-Mukhametzyanov reviewed
Should give  different names to commits

2019-02-15 09:59 UTC, Ramil-Mukhametzyanov approved these changes
It works :+1:

2019-02-15 10:02 UTC, Ramil-Mukhametzyanov requested changes
This part has not been transfered
https://github.com/it-projects-llc/pos-addons/blob/10.0/pos_scan_ref/static/src/js/pos.js#L16-L19

2019-02-18 11:38 UTC, Ramil-Mukhametzyanov approved these changes

2019-02-18 14:00 UTC, Ramil-Mukhametzyanov reviewed
@Ommo73 
pos_scan_ref/__manifest__.py: Please use single quotes (')

2019-02-19 08:52 UTC, ilmir-k commented
> @Ommo73
> pos_scan_ref/**manifest**.py: Please use single quotes (')

@Ramil-Mukhametzyanov why? actually, it is not required

2019-02-25 20:18 UTC, yelizariev commented
it's double quotes that should use for manifest

2019-03-27 18:31 UTC, yelizariev approved these changes

2019-03-28 05:33 UTC, GabbasovDinar requested changes

2019-03-28 05:33 UTC, GabbasovDinar commented on pos_scan_ref/tests/test_pos_scan_ref.py
> +
@Ommo73 should work without code lines above (the module does not use Qweb) Check it please

2019-03-28 10:02 UTC, Ommo73 commented on pos_scan_ref/tests/test_pos_scan_ref.py
> +
@GabbasovDinar  Yes, that is right. Works without this part of the code.

2019-03-28 11:17 UTC, GabbasovDinar commented
@Ommo73 

`2019-03-28` 10:57:42,260 6412 [1;31m[1;49mERROR[0m openerp_test odoo.addons.pos_scan_ref.tests.test_pos_scan_ref: ` AssertionError: ('TypeError: undefined is not a function (evaluating '
2019-03-28 10:57:42,260 6412 [1;31m[1;49mERROR[0m openerp_test odoo.addons.pos_scan_ref.tests.test_pos_scan_ref: `  "'this.pos.db.get_sorted_orders_history(1000).find')\n"`

You need to replace `find` to `_.find`

2019-03-29 08:33 UTC, Ramil-Mukhametzyanov requested changes

2019-03-29 08:33 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/static/src/js/screens.js
> +            var order = _.find(this.pos.db.get_sorted_orders_history(1000), function(o) {
If this change to pos_orders_history is really required, please make records to its changelog and modify the manifest.
Otherwise, remove this change.

2019-03-29 09:01 UTC, GabbasovDinar commented on pos_orders_history/static/src/js/screens.js
> +            var order = _.find(this.pos.db.get_sorted_orders_history(1000), function(o) {
@Ramil-Mukhametzyanov not necessary to make changes to the changelog

2019-03-29 09:03 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-29 09:03 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/static/src/js/screens.js
> +            var order = _.find(this.pos.db.get_sorted_orders_history(1000), function(o) {
好吧

2019-04-01 10:09 UTC, Ommo73 commented
@yelizariev can you merge it?

2019-04-01 10:20 UTC, GabbasovDinar approved these changes

2019-04-05 10:19 UTC, yelizariev commented on pos_orders_history/static/src/js/screens.js
> +            var order = _.find(this.pos.db.get_sorted_orders_history(1000), function(o) {
It's not a :ambulance: then. You fix tests. So, :shield:

2019-04-05 10:20 UTC, yelizariev commented on pos_mobile/controllers/main.py
> -# -*- coding: utf-8 -*-
It's not a :ambulance:. You don't fix anything from user point of view

2019-04-05 13:45 UTC, KolushovAlexandr approved these changes

2019-04-08 12:56 UTC, KolushovAlexandr approved these changes

2019-04-09 14:27 UTC, KolushovAlexandr approved these changes

2019-04-09 14:28 UTC, merged