:arrow_up::one::zero: pos_scan_ref *Port*
itpp-labs/pos-addons pull request #921
Opened 2019-02-08 12:32 UTC by Ommo73

2019-02-25 20:15 UTC, yelizariev commented
You must squash commit into one via ``git rebase -i``. Don't make new PR please

2019-04-05 13:51 UTC, KolushovAlexandr approved these changes

2019-04-05 13:53 UTC, KolushovAlexandr requested changes

2019-04-05 13:53 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/pos.js
> +            var search_string = this._product_search_string(product);
Hound bot pick the wrong line. Look at the line below. This error about that

2019-04-10 08:11 UTC, KolushovAlexandr requested changes
1) :green_heart: commits say they add 'utf-8' line but i see they only delete the empty line beneath 'utf-8' comment. You can remove those commits
2) Don't forget to rebase
3) travis error

2019-04-10 08:11 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/pos.js
> +        var stored_categories = this.product_by_category_id;
Check the necessity of this stuff

2019-04-10 08:11 UTC, KolushovAlexandr commented on pos_scan_ref/doc/index.rst
> +============
Add Usage

2019-04-10 08:11 UTC, KolushovAlexandr commented on pos_scan_ref/README.rst
> +Scan & search a product by ref in POS
No need to duplicate the module name

2019-04-10 11:13 UTC, Ommo73 commented on pos_scan_ref/doc/index.rst
> +============
Usage added

2019-04-11 08:25 UTC, KolushovAlexandr approved these changes

2019-04-11 10:34 UTC, Ramil-Mukhametzyanov approved these changes

2019-04-11 11:32 UTC, merged