:arrow_up::one::two: pos_category_multi
itpp-labs/pos-addons pull request #928
Opened 2019-02-25 08:34 UTC by GabbasovDinar

2019-02-25 09:11 UTC, Ramil-Mukhametzyanov approved these changes

2019-02-25 19:14 UTC, yelizariev reviewed
Fix ALL reference to odoo version, e.g.

Tested on Odoo 11.0 ee2b9fae3519c2494f34dacf15d0a3b5bd8fbd06

2019-03-21 18:09 UTC, yelizariev requested changes

2019-03-21 18:09 UTC, yelizariev commented on pos_debt_notebook/models.py
> +                'discount': disc == 100 and disc or
It's not :shield:. You don't change anything in coverage. Check the handbook. It has clear explanation on tag usage.

2019-03-25 16:36 UTC, yelizariev approved these changes

2019-03-26 07:51 UTC, merged