:heart_eyes: disable mobile mode in POS
itpp-labs/pos-addons pull request #930
Opened 2019-02-26 10:34 UTC by GabbasovDinar

2019-02-26 11:58 UTC, Ramil-Mukhametzyanov approved these changes

2019-02-26 14:17 UTC, ilmir-k commented on pos_mobile/models/pos_config_model.py
> +    mobile_version_is_active = fields.Boolean(string="Mobile version is Active", default=True)
@GabbasovDinar 
I think it's better to name it ``Mobile version`` instead

2019-02-26 15:13 UTC, yelizariev commented on pos_mobile/models/pos_config_model.py
> +    mobile_version_is_active = fields.Boolean(string="Mobile version is Active", default=True)
``allow_mobile`` + Update description so it's easier to understand Meaning (It's allow mode, not a force mode)

2019-02-26 15:14 UTC, yelizariev requested changes
Use proper variable name and clarify docs

2019-02-26 15:25 UTC, yelizariev requested changes

2019-02-26 15:25 UTC, yelizariev commented on pos_mobile/controllers/main.py
> +            return request.render('point_of_sale.index', qcontext=context)
It's better call super and update context in response
See https://github.com/odoo/odoo/blob/10.0/addons/website_portal_sale/controllers/main.py#L14

2019-02-26 15:25 UTC, yelizariev commented on pos_mobile/controllers/main.py
> +            session_info['is_mobile'] = True
If ``mobile_version_is_active``, then it doesn't mean that system *is mobile*, it's only *allow mobile*

2019-02-26 15:25 UTC, yelizariev commented on pos_mobile/views/pos_mobile_template.xml
>  // exclude pos_mobile from module list if the url doesn't have parameter "m" in agrs (e.g. /pos/web?m=1 )
This comment is obsolete and need to be updated

2019-02-26 15:25 UTC, yelizariev commented on pos_mobile/views/pos_mobile_view.xml
> +                                Disable or Enable Mobile Version
You cannot *Enable* Mobile via this option. You can only *Allow*

2019-02-26 17:21 UTC, yelizariev commented
More flexible solution might be this:

     auto_mobile = fields.Boolean ("Auto Mobile View", help="Switch to Mobile  view automatically depending on device")

2019-02-28 12:49 UTC, yelizariev requested changes

2019-02-28 12:49 UTC, yelizariev commented on pos_mobile/controllers/main.py
> +    @http.route('/pos/web', type='http', auth='user')
``@http.route()`` is enough

2019-02-28 12:49 UTC, yelizariev commented on pos_mobile/static/src/js/mobile.js
> +            this.is_mobile = odoo.is_mobile && odoo.session_info.allow_mobile;
It evaluate to False when auto_mobile is False, but ``m=1``

2019-03-27 18:18 UTC, yelizariev approved these changes

2019-03-27 18:19 UTC, yelizariev commented
Change tag to :zap: (new feature) please

2019-03-28 08:38 UTC, merged