:heart_eyes: load order after scan barcode
itpp-labs/pos-addons pull request #931
Opened 2019-02-26 11:40 UTC by GabbasovDinar

2019-03-19 08:39 UTC, ilmir-k requested changes
@GabbasovDinar update the version please

2019-03-21 20:46 UTC, yelizariev commented
Are you sure that both updates are just :heart_eyes:  and not  :ambulance: or :zap: (depending on whether is it supposed feature or not)

:heart_eyes: = 
before the commit it worked in expected way, but now it works better (quicker, nicer)

2019-04-03 10:32 UTC, KolushovAlexandr approved these changes

2019-04-03 12:28 UTC, ilmir-k approved these changes

2019-04-03 12:32 UTC, merged