:heart_eyes: No need to specify a Receipt Printer in config for using…
itpp-labs/pos-addons pull request #936
Opened 2019-03-05 14:33 UTC by GabbasovDinar

… Kitchen Printers

2019-03-06 08:04 UTC, Ramil-Mukhametzyanov requested changes
Even if the USB printer is switched on, its status is shown as 'offline'
![usb printer](https://user-images.githubusercontent.com/33877236/53865193-499a1580-4010-11e9-910f-eb93322da228.jpg)

2019-03-06 08:22 UTC, Ramil-Mukhametzyanov requested changes
The error 'self.devices_status is undefined' appears after turning off the USB printer.
Steps to reproduce:
1. usb printer is on
2. enter pos
3. switch off  usb printer
4. reload pos, click on network printer icon
5. reload pos, click on network printer icon again

2019-03-07 12:30 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-07 16:28 UTC, yelizariev approved these changes
Consider splitting commit into two as there are two updates and not just one

2019-03-12 14:20 UTC, merged