10.0 pos partner sync
itpp-labs/pos-addons pull request #939
Opened 2019-03-11 00:01 UTC by KolushovAlexandr

2019-03-11 01:33 UTC, yelizariev requested changes
Check all docs

2019-03-11 01:33 UTC, yelizariev commented on pos_partner_sync/README.rst
>  The module allows to instantly update partner data in opened POSes via longpolling connection if partner barcode has been changed in the backend.
Not only barcode

2019-03-11 16:28 UTC, KolushovAlexandr commented
With updates tests are passed, the only problem travis sees is the lack of tours for the module.

2019-03-18 13:28 UTC, Ramil-Mukhametzyanov requested changes

2019-03-18 13:28 UTC, Ramil-Mukhametzyanov commented on pos_partner_sync/README.rst
> +By default, Odoo updates partner data when open the client list. This module doesn't require an extra action for that and updates partner data in POSes instantly after the predefined partner field ha
I entered the client list before I scanned the new customer barcode from other POS. Otherwise, POS can not find the barcode.

2019-03-19 18:30 UTC, KolushovAlexandr commented on pos_partner_sync/README.rst
> +By default, Odoo updates partner data when open the client list. This module doesn't require an extra action for that and updates partner data in POSes instantly after the predefined partner field ha
Had you specified the barcode field to be synchronized? You can find how to do it in the documentation.

2019-03-20 00:04 UTC, KolushovAlexandr commented on pos_partner_sync/README.rst
> +By default, Odoo updates partner data when open the client list. This module doesn't require an extra action for that and updates partner data in POSes instantly after the predefined partner field ha
Confirm. That's the issue

2019-03-22 08:23 UTC, Ramil-Mukhametzyanov commented on pos_partner_sync/README.rst
> +By default, Odoo updates partner data when open the client list. This module doesn't require an extra action for that and updates partner data in POSes instantly after the predefined partner field ha
Ok, resolved

2019-03-22 08:23 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-22 16:33 UTC, yelizariev approved these changes

2019-03-22 16:33 UTC, yelizariev commented on pos_partner_sync/README.rst
> +The module allows to instantly update partner data in opened POSes via longpolling connection if a predefined partner field has been changed in the backend.
```suggestion
The module allows to instantly update partner data in opened POSes via longpolling connection if any of predefined partner fields have been changed in the backend.
```

2019-03-22 16:33 UTC, yelizariev commented on pos_partner_sync/doc/changelog.rst
> +**New:** Availability to sync all partner fields with POSes
```suggestion
**New:** Availability to sync any partner fields with POSes
```

2019-03-22 16:34 UTC, yelizariev requested changes
Improve docs and rebase

2019-03-25 22:07 UTC, yelizariev approved these changes

2019-03-25 22:08 UTC, yelizariev commented
Why it has UTF lints?

2019-03-26 16:16 UTC, KolushovAlexandr commented
@yelizariev  they are not related to the module

2019-03-28 15:17 UTC, merged