:tada::one::zero: pos_disable_payment_restaurant module
itpp-labs/pos-addons pull request #941
Opened 2019-03-13 15:48 UTC by ilmir-k

:tada::one::zero: pos_disable_payment_restaurant module

2019-03-29 11:49 UTC, Ramil-Mukhametzyanov reviewed
pos_disable_payment has changed: the changelog and manifest files need to be modified.

2019-03-29 11:51 UTC, Ramil-Mukhametzyanov approved these changes

2019-04-03 10:15 UTC, KolushovAlexandr requested changes

2019-04-03 10:15 UTC, KolushovAlexandr commented on pos_disable_payment/doc/changelog.rst
> +**Improvement:** New option "Disable customer selection"
this improvement requires the second number to be changed
https://odoo-development.readthedocs.io/en/latest/dev/docs/__manifest__.py.html?highlight=version

2019-04-03 10:15 UTC, KolushovAlexandr commented on pos_multi_session/doc/changelog.rst
> +`4.0.5`
Why is it here?

2019-04-05 14:15 UTC, KolushovAlexandr approved these changes

2019-04-08 10:07 UTC, merged