:ambulance: error of using different companies within one multi-session
itpp-labs/pos-addons pull request #945
Opened 2019-03-14 07:14 UTC by GabbasovDinar

2019-03-14 13:27 UTC, yelizariev requested changes

2019-03-14 13:27 UTC, yelizariev commented on pos_multi_session/doc/changelog.rst
> +**Fix:** The error associated with the use of different companies within the same multi-session
Don't use "associated". You can say "error on using different companies..."

2019-03-20 14:02 UTC, Ramil-Mukhametzyanov requested changes
If log in as Demo and change the company, I will see the corresponding multisession POSes.
But if I enter as Admin, I will see every POS no matter which company I choose.

2019-03-21 08:24 UTC, Ramil-Mukhametzyanov approved these changes
In the last comment is the Odoo 11.0 feature.

2019-03-21 17:15 UTC, yelizariev approved these changes

2019-03-21 17:17 UTC, merged