10.0 pos order cancel integaration with pos pin
itpp-labs/pos-addons pull request #951
Opened 2019-03-20 20:23 UTC by KolushovAlexandr

2019-03-21 20:40 UTC, yelizariev requested changes

2019-03-21 20:40 UTC, yelizariev commented on pos_pin/doc/changelog.rst
> +- **NEW:** Availability not to change cashier after entering pin
Ability?

2019-03-21 20:40 UTC, yelizariev commented on pos_pin/static/src/js/pos.js
> +            return def_pass.done(function(res){
It seems that you don't need ``def_pass``. 


    Try def_list.done(...the same here, but without def_pass..).done(....check_then_set_and_render_cashier....)

2019-03-21 20:40 UTC, yelizariev commented on pos_pin/static/src/js/pos.js
> +            }
I don't see a reason to have this in separate method

2019-03-26 17:16 UTC, gustavovalverde requested changes
Just as advanced order notes works. This one should have an option to Ask for the manager just when the order was sent to the kitchen.

I think you'll have to make an extra module for that functionality, as it will depend on pos_restaurant; making this module for restaurants and not as a generic one <-- Your call.

2019-03-26 20:38 UTC, gustavovalverde approved these changes

2019-03-28 14:06 UTC, Ramil-Mukhametzyanov requested changes

2019-03-28 14:06 UTC, Ramil-Mukhametzyanov commented on pos_order_cancel_restaurant/models/models.py
> +    ask_managers_pin_kitchen_orders_only = fields.Boolean(string="Ask Manager For Kitchen orders only", default=False, help="Only Managers are allowed to cancel kitchen order lines")
This option does not work properly.
The 'Select User' popup is displayed, if only an order is created, all lines are deleted and then the order deleting button [-] is clicked.

2019-03-28 14:16 UTC, KolushovAlexandr commented on pos_order_cancel_restaurant/models/models.py
> +    ask_managers_pin_kitchen_orders_only = fields.Boolean(string="Ask Manager For Kitchen orders only", default=False, help="Only Managers are allowed to cancel kitchen order lines")
Did you send the order to the kitchen? It should work only that way

2019-03-28 14:26 UTC, Ramil-Mukhametzyanov commented on pos_order_cancel_restaurant/models/models.py
> +    ask_managers_pin_kitchen_orders_only = fields.Boolean(string="Ask Manager For Kitchen orders only", default=False, help="Only Managers are allowed to cancel kitchen order lines")
No, I did not.
I have tested trying to delete an order lines that has been sent to the kitchen. It works.

2019-03-28 14:26 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-28 14:31 UTC, yelizariev approved these changes

2019-03-28 14:31 UTC, merged