:zap: Table_blocking feature
itpp-labs/pos-addons pull request #952
Opened 2019-03-21 17:08 UTC by KolushovAlexandr

2019-03-21 19:56 UTC, yelizariev requested changes

2019-03-21 19:56 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                            'body': _t('The Table is served by another waiter'),
Specify in the message by whom is served

2019-03-21 19:56 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                .unique().value();
You don't need to compute it when ``user_is_manager`` is true

2019-03-21 19:56 UTC, yelizariev commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                    if (this.pos.check_table_admittance(table)) {
You can simplify nesting
```
if (!table or this.pos.check_table_admittance(table)){
return  super;
}
```

2019-03-26 17:14 UTC, gustavovalverde approved these changes
Just add the translation file.

2019-03-28 13:33 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js
> +                    confirm: function(){
It does not make sense: cancel or confirm
Why not just 'ok'?

2019-03-28 13:33 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-28 18:52 UTC, yelizariev approved these changes

2019-03-29 10:32 UTC, merged