10.0 pos longpolling issue
itpp-labs/pos-addons pull request #959
Opened 2019-03-24 01:49 UTC by KolushovAlexandr

2019-03-25 22:12 UTC, yelizariev requested changes
Commits can be joined I suppose.
Update changelog

2019-03-26 20:04 UTC, yelizariev approved these changes

2019-03-26 20:04 UTC, yelizariev commented on pos_longpolling/doc/changelog.rst
> + - **FIX:** Incorrect behaviour of longpolling icons
:+1:

2019-03-27 09:50 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-27 09:50 UTC, merged