11.0 719922f491313952462a767428a701567295d61f
itpp-labs/pos-addons pull request #964
Opened 2019-03-31 00:18 UTC by KolushovAlexandr

2019-04-01 09:49 UTC, Ramil-Mukhametzyanov requested changes
Using the multi_session option "One Waiter per Table" clicking on a table will result in the error "cashier is undefined"

2019-04-01 10:02 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/__manifest__.py
> +    'version': '10.0.1.1.0',
The module could bot be tested on runbot due to a wrong version number.

2019-04-01 10:02 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/__manifest__.py
> +    'version': '10.0.1.1.0',
odoo 11.0

2019-04-01 10:30 UTC, Ramil-Mukhametzyanov requested changes
"Ask manager" option: when the demo (POS user) tries to delete the order, there is the same type of error.

2019-04-01 11:22 UTC, Ramil-Mukhametzyanov requested changes
pos_partner_sync:
If the customer list screen is not open, new barcode will not be applied to a partner in another POS.

2019-04-02 00:19 UTC, KolushovAlexandr commented on pos_keyboard/__manifest__.py
> +    'version': '10.0.1.1.0',
@Ramil-Mukhametzyanov, it's not ported yet, so it's not installable. 
https://github.com/it-projects-llc/pos-addons/pull/964/files/9ca66a6b2dbfbc3ababdda04af9760f2008a1092#diff-036e3bb5eeff71c6285f911b70b19b8dR17
And I have the question, should i do it in this pr or in the another?

2019-04-02 09:31 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/__manifest__.py
> +    'version': '10.0.1.1.0',
OK, you should not port it in this pr.

2019-04-04 10:39 UTC, Ramil-Mukhametzyanov requested changes
Error after click 'cancel' in the lock screen.
Steps to reproduce:
1. Set PIN for Admin. Turn on 'Ask Manager' option in the Demo's POS.
2. Enter POS as Demo, create an order, add an item and click to remove the item.
3. Select Admin, then click Cancel
Result: 'cancel_function is undefined' and, in addition, the item has been is deleted.

2019-04-08 09:47 UTC, Ramil-Mukhametzyanov approved these changes

2019-04-08 10:00 UTC, merged