:ambulance: client lines updating on the clientlistscreen
itpp-labs/pos-addons pull request #966
Opened 2019-04-04 10:46 UTC by KolushovAlexandr

2019-04-04 12:03 UTC, Ramil-Mukhametzyanov requested changes
When I try to edit a company's name from the POS customer list screen, an 'partner is not defined' error occurs.

2019-04-05 06:51 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/static/src/js/pos_multi_session.js
> +            this.ms_syncing_in_pzogress = false;
Is it intentional change?

2019-04-05 11:21 UTC, Ramil-Mukhametzyanov approved these changes
perfect :+1:

2019-04-05 11:55 UTC, yelizariev requested changes
load_new_partners no need to be redefined. Just use new method, e.g. load_new_partners_force_update.

2019-04-05 11:55 UTC, yelizariev commented on pos_partner_sync/static/src/js/pos_partner_sync.js
> +                self.db.get_partner_write_date();
Senseless

2019-04-05 11:56 UTC, yelizariev commented
load_new_partners_force_update must have comment about what is difference with load_new_partner

2019-04-06 11:36 UTC, yelizariev commented on pos_partner_sync/static/src/js/pos_partner_sync.js
> +            ids = ids || this.db.partner_sorted;
Does that mean, that  it updates ALL partners (even without any updates), when you call method without parameters? Is it really necessary?

2019-04-08 11:38 UTC, KolushovAlexandr commented on pos_partner_sync/static/src/js/pos_partner_sync.js
> +            ids = ids || this.db.partner_sorted;
@yelizariev  I made it work by analogy with `load_new_partners` method. So as it's written in the name of the function it is the same as `load_new_partners` but do it forcibly. It is not necessary, i can change it to a check for `ids.length` and return rejected defered object if `ids.length === 0`

2019-04-08 12:07 UTC, yelizariev commented on pos_partner_sync/static/src/js/pos_partner_sync.js
> +            ids = ids || this.db.partner_sorted;
Yes, make it impossible to use without ids

2019-04-09 09:50 UTC, yelizariev approved these changes

2019-04-09 09:50 UTC, merged