:zap: For different POS categories available are different Product Notes
itpp-labs/pos-addons pull request #973
Opened 2019-04-10 11:44 UTC by GabbasovDinar

2019-04-10 13:06 UTC, Ramil-Mukhametzyanov requested changes
When a product with non-specified category is selected, the "category_ids is undefined" error occurs after clicking Note button.

2019-04-10 14:33 UTC, Ramil-Mukhametzyanov approved these changes

2019-04-10 15:37 UTC, yelizariev requested changes

2019-04-10 15:37 UTC, yelizariev commented on pos_order_note/static/src/js/order_note.js
> +            return self.config.module_pos_restaurant;
Add a comment to code about what does that mean

2019-04-10 15:37 UTC, yelizariev commented on pos_order_note/doc/changelog.rst
> +- **NEW:** For different POS categories available are different Product Notes
![image](https://user-images.githubusercontent.com/186131/55892801-707bd680-5bd0-11e9-8770-f895c714474a.png)

2019-04-16 13:52 UTC, yelizariev commented on pos_order_note/doc/changelog.rst
> +- **NEW:** Each POS category has its own set of notes for POS products.
Sorry, but it's actually opposite -- each note can be applied for specific set of categories only

2019-04-29 10:53 UTC, yelizariev commented on pos_order_note/models/models.py
> +                                        help='The note will be available for this group of POS categories.'
I think space at the end is needed. Otherwise it's ``The note will be available for this group of POS categories.Leave the field empty so that the note is available for all POS categories.``

2019-04-30 09:03 UTC, bealdav commented on pos_order_note/models/models.py
> +                                        help='The note will be available for this group of POS categories.'
```suggestion
                                        help='The note will be available for this group of POS categories. '
```

2019-05-01 11:01 UTC, merged