10.0 pos small fixes
itpp-labs/pos-addons pull request #975
Opened 2019-04-11 13:40 UTC by KolushovAlexandr

2019-04-12 12:01 UTC, Ramil-Mukhametzyanov approved these changes

2019-04-12 12:09 UTC, yelizariev requested changes
README was used as description for apps store. If we update README, we need new html description. Try to make something from our templates or make a request for a description

2019-04-22 09:26 UTC, yelizariev commented
This branch has conflicts that must be resolved

2019-04-22 13:38 UTC, yelizariev commented on pos_keyboard/README.rst
> -Usage instructions: `<doc/index.rst>`_
This commit fix updates of another commit of the same PR. So, you need to merge such commits

2019-04-22 13:39 UTC, yelizariev commented on pos_pin/README.rst
>  * `Kolushov Alexandr <https://it-projects.info/team/KolushovAlexandr>`__
Different url style (with www and without www)

2019-04-29 14:43 UTC, yelizariev requested changes

2019-04-29 14:43 UTC, yelizariev commented on pos_pin/static/src/js/pos.js
> +                return cashier;
Changelog is needed I think

2019-04-30 08:27 UTC, yelizariev approved these changes

2019-04-30 08:27 UTC, merged