:shield: pos_scan_ref updated tests. cover the basic functionality
itpp-labs/pos-addons pull request #976
Opened 2019-04-11 15:57 UTC by Ommo73

2019-05-16 09:39 UTC, KolushovAlexandr requested changes
check and fix incompatibility with pos_cashier_select in the same pr with tests

2019-05-18 17:41 UTC, KolushovAlexandr requested changes

2019-05-18 17:41 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/test_pos_scan_ref.js
> +            trigger: '.product-name:contains("Boni Oranges")',
It doesn't guarantee that the orderline was added

2019-05-18 17:41 UTC, KolushovAlexandr commented on pos_scan_ref/static/src/js/test_pos_scan_ref.js
> +            position: "bottom"
these changes are not related to the commit message

2019-05-18 17:41 UTC, KolushovAlexandr commented on pos_product_lot/static/src/js/pos.js
> +            if(parsed_code.type === 'price'){
Please get rid of dispensable changes

2019-05-18 17:41 UTC, KolushovAlexandr commented on pos_product_lot/static/src/js/pos.js
> +                selectedOrder.add_product(product, {price:parsed_code.value});
add it to the changelog as a fix

2019-05-20 08:59 UTC, Ommo73 commented on pos_product_lot/static/src/js/pos.js
> +                selectedOrder.add_product(product, {price:parsed_code.value});
DONE

2019-05-20 13:28 UTC, KolushovAlexandr commented on pos_product_lot/static/src/js/pos.js
> +            if(parsed_code.type === 'price'){
I meant not only this one, please look at the ``Files Changed`` and fix all of them

2019-05-22 13:41 UTC, KolushovAlexandr approved these changes

2019-05-30 13:12 UTC, KolushovAlexandr commented
@Ommo73 Who's next to check it?

2019-06-18 09:28 UTC, yelizariev commented
Чей ход?

2019-07-15 12:25 UTC, em230418 commented
Maybe :cherries: for https://github.com/it-projects-llc/pos-addons/pull/976/commits/bb8db5f7796cb07462d3a3b5ae9e0e85ab04f319 ? And  :ambulance: for https://github.com/it-projects-llc/pos-addons/pull/976/commits/141e753d1d50523a66717ba5ed74b8184b8b6989 ?

2019-07-15 12:27 UTC, em230418 commented
```
Changelog: `<doc/changelog.rst>`_
Use template: "Tested on Odoo {VERSION} {ODOO_COMMIT_SHA_TO_BE_UPDATED}"
************* Module pos_product_lot
pos_product_lot/__init__.py:1: [E7989(readme-versions), ] Wrong version in module's README.rst
pos_product_lot/__init__.py:1: [W7993(js-empty-coverage), ] JS files are not covered (phantom_js is not used). Please add js tests: https://odoo-development.readthedocs.io/en/latest/qa/js/index.html
```

2019-07-15 13:33 UTC, KolushovAlexandr commented
@em230418 about this 'And  ambulance for 141e753 ?' It worked as it should, the only reason it was changed - failed tests

2019-07-15 13:34 UTC, KolushovAlexandr commented
@em230418 also, I don't think that this is necessary 'pos_product_lot/__init__.py:1: [W7993(js-empty-coverage), ] JS files are not covered (phantom_js is not used). Please add js tests: https://odoo-development.readthedocs.io/en/latest/qa/js/index.html'

2019-07-18 05:45 UTC, em230418 commented
> @em230418 about this 'And ambulance for 141e753 ?' It worked as it should, the only reason it was changed - failed tests

Ok. Accepted.

> @em230418 also, I don't think that this is necessary
If travis passes without it - that is fine for me.

2019-07-31 06:03 UTC, em230418 approved these changes

2019-07-31 06:04 UTC, em230418 commented
I approve to merge it now

2019-07-31 06:04 UTC, merged