10.0 pos partner deselection publication
itpp-labs/pos-addons pull request #982
Opened 2019-04-24 08:47 UTC by KolushovAlexandr

2019-04-25 06:30 UTC, yelizariev commented
@KolushovAlexandr second commit has wrong link to PR. Either fix it (``it-projects-llc/addons-dev#647``, it-projects-llc/addons-dev#647) or remove, please

2019-04-26 07:56 UTC, yelizariev requested changes

2019-04-26 07:56 UTC, yelizariev commented on pos_partner_deselection/models/models.py
> +    customer_deselection_interval = fields.Integer(string='Customer Deselection Interval', default=0)
It's clear from UI is it seconds or minutes

2019-04-26 07:56 UTC, yelizariev commented on pos_partner_deselection/static/src/js/test_pos_deselection.js
> +        }];
Why don't you add customer selection and checking deselection?

2019-04-26 08:28 UTC, KolushovAlexandr commented on pos_partner_deselection/static/src/js/test_pos_deselection.js
> +        }];
Because it might break other tours due to deselected partner before a payment

2019-04-29 14:54 UTC, yelizariev commented on pos_partner_deselection/static/src/js/test_pos_deselection.js
> +        }];
No, it cannot

2019-04-29 14:54 UTC, yelizariev approved these changes

2019-04-29 14:54 UTC, merged