:ambulance: pos_order_note compatibility with pos_mobile
itpp-labs/pos-addons pull request #992
Opened 2019-05-13 17:35 UTC by KolushovAlexandr

2019-05-14 05:57 UTC, Ramil-Mukhametzyanov approved these changes
:+1:

2019-05-14 07:08 UTC, yelizariev requested changes

2019-05-14 07:08 UTC, yelizariev commented on pos_order_note/static/src/js/order_note.js
> +    var pos_mobile_gui = require('pos_mobile.gui');
pos_mobile might not be installed and this will raise error. You have to make a solution, that will work in both cases

2019-05-14 07:08 UTC, yelizariev commented on pos_order_note/static/src/js/order_note.js
> +    pos_mobile_gui.Gui.include({
Can you use just ``gui.Gui`` here? If not, probably, some refactoring in ``pos_mobile`` is needed

2019-05-15 12:47 UTC, GabbasovDinar approved these changes

2019-05-20 10:43 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-20 11:02 UTC, yelizariev commented on pos_mobile/static/src/js/gui.js
> -            this.change_screen_type(current_screen_name);
@GabbasovDinar check this update please

2019-05-20 12:08 UTC, GabbasovDinar commented on pos_mobile/static/src/js/gui.js
> -            this.change_screen_type(current_screen_name);
I think, @KolushovAlexandr you don't need to change this code

2019-05-22 13:50 UTC, GabbasovDinar commented on pos_mobile/static/src/js/gui.js
> -            this.change_screen_type(current_screen_name);
it seems OK

2019-05-22 13:51 UTC, GabbasovDinar approved these changes

2019-05-23 09:27 UTC, yelizariev approved these changes

2019-05-23 11:28 UTC, merged