11.0 c1d920cbebf0de45e14b024e21aa44fc125256c0
itpp-labs/pos-addons pull request #994
Opened 2019-05-15 09:14 UTC by KolushovAlexandr

2019-05-16 08:51 UTC, Ramil-Mukhametzyanov commented on pos_disable_payment_restaurant/static/description/index.html
> +                    Tested on Odoo<br/>10.0 community
11.0 community

2019-05-16 08:55 UTC, Ramil-Mukhametzyanov commented on pos_disable_payment_restaurant/static/description/index.html
> +                    Tested on Odoo<br/>10.0 community
It's OK, pos_disable_payment_restaurant is not ported yet.

2019-05-16 10:36 UTC, Ramil-Mukhametzyanov commented on pos_debt_notebook/doc/changelog.rst
> +- **Improvement:** New Balance is amount for selected journal,  not for total Credits.
checked :+1:

2019-05-16 10:36 UTC, Ramil-Mukhametzyanov commented on pos_disable_payment/doc/changelog.rst
> +**Improvement:** New option "Disable customer selection"
checked :+1:

2019-05-16 10:36 UTC, Ramil-Mukhametzyanov commented on pos_disable_payment/doc/changelog.rst
> +**Improvement:** Move the "Allow change Qty for kitchen orders" option to pos_disable_payment_restaurant module
checked :+1:

2019-05-16 11:13 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Incorrect input data on password pop-up if the first clicked button was `backspace`
checked :+1:

2019-05-16 14:53 UTC, Ramil-Mukhametzyanov commented on pos_partner_sync/doc/changelog.rst
> +**Fix:** Client line data updating
checked :+1:

2019-05-16 14:53 UTC, Ramil-Mukhametzyanov commented on pos_partner_sync/doc/changelog.rst
> +**Fix:** Several updates within the one second were denied by built-in behavior
checked :+1:

2019-05-17 10:05 UTC, Ramil-Mukhametzyanov requested changes

2019-05-17 10:05 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Error on clicking numbers and enter in selection popups
checked :-1:
Enter doesn't work. #985 
@KolushovAlexandr Remove the pos_keyboard change from the PR.

2019-05-17 10:15 UTC, KolushovAlexandr commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Error on clicking numbers and enter in selection popups
We realized that it is another error needed to be fixed in 10.0 at first

2019-05-17 10:23 UTC, KolushovAlexandr commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Error on clicking numbers and enter in selection popups
I'll remove this commit to update it and later merge in 11 again

2019-05-17 10:48 UTC, Ramil-Mukhametzyanov requested changes

2019-05-17 10:48 UTC, Ramil-Mukhametzyanov commented on pos_pin/doc/changelog.rst
> +- **Fix:** Cannot set property of undefined on some actions with password popup
checked :-1:
The js files or py files associated with the pos_pin module in PR has not changed.

2019-05-17 10:58 UTC, KolushovAlexandr commented on pos_pin/doc/changelog.rst
> +- **Fix:** Cannot set property of undefined on some actions with password popup
@Ramil-Mukhametzyanov it was fixed earlier as a part of the merge PR.

2019-05-17 11:48 UTC, Ramil-Mukhametzyanov commented on pos_pin/doc/changelog.rst
> +- **Fix:** Cannot set property of undefined on some actions with password popup
OK

2019-05-17 11:48 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/doc/changelog.rst
>  **Improvement:** Remove the "Update order list" button because the orders are updated instantly now
checked :+1:

2019-05-17 11:48 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Error related to return a specific order after barcode scanning
how to check this? #931 
@ilmir-k  @GabbasovDinar

2019-05-17 11:48 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Order duplication in case of poor connection in POS
how to check this? #931 
@ilmir-k  @GabbasovDinar

2019-05-17 11:48 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/doc/changelog.rst
> +**Fix:** Error related to load specific order after barcode scanning
how to check this? #931 
@ilmir-k  @GabbasovDinar

2019-05-17 12:39 UTC, ilmir-k commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Error related to return a specific order after barcode scanning
@Ramil-Mukhametzyanov 
load specific order by its barcode scanning and try to return it then

2019-05-17 12:41 UTC, ilmir-k commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Error related to return a specific order after barcode scanning
@Ramil-Mukhametzyanov 
also try to make partial returns, i.e. 
* load specific order
* make a return of some products
* load the same order again
* return the remaining products

2019-05-17 12:43 UTC, ilmir-k commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Order duplication in case of poor connection in POS
@Ramil-Mukhametzyanov 
emulate a poor connection and see if there are any duplicated orders after return or not

2019-05-17 12:44 UTC, ilmir-k commented on pos_orders_history/doc/changelog.rst
> +**Fix:** Error related to load specific order after barcode scanning
@Ramil-Mukhametzyanov 
Just load any order by barcode scanning and see results. It must be loaded without errors

2019-05-20 14:18 UTC, Ramil-Mukhametzyanov commented on pos_orders_history/doc/changelog.rst
> +**Fix:** Error related to load specific order after barcode scanning
checked :+1:

2019-05-20 14:30 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Error on clicking numbers and enter in selection popups
**fixed here** #999

2019-05-20 14:44 UTC, Ramil-Mukhametzyanov requested changes
pos_order_history_return issues:
1. After entering the POS, if there is no paid order, the history screen cannot be opened.
2. There is no return button for orders in the history.

2019-05-20 14:57 UTC, Ramil-Mukhametzyanov commented on pos_keyboard/doc/changelog.rst
> +**Fix:** Enter did not work for some pop-ups
checked :+1:

2019-05-23 13:13 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Error related to return a specific order after barcode scanning
> @Ramil-Mukhametzyanov
> load specific order by its barcode scanning and try to return it then

checked :+1:

2019-05-23 13:13 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Error related to return a specific order after barcode scanning
> @Ramil-Mukhametzyanov
> also try to make partial returns, i.e.
> 
>     * load specific order
> 
>     * make a return of some products
> 
>     * load the same order again
> 
>     * return the remaining products

checked :+1:

2019-05-24 07:53 UTC, Ramil-Mukhametzyanov commented on pos_orders_history_return/doc/changelog.rst
> +**Fix:** Order duplication in case of poor connection in POS
checked :+1:

2019-05-24 07:58 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/doc/changelog.rst
> +- **Fix:** Paid order could appear again in POS in case of problems with connection within payment process
checked :+1:

2019-05-24 08:28 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-24 09:40 UTC, yelizariev commented
Травис штормит. Вернемся к ПР, когда травис наладится

2019-05-28 14:26 UTC, yelizariev commented
rebase with upstream to fix travis

2019-05-28 14:28 UTC, yelizariev commented
ok, seems that you just did something similar

2019-05-29 10:42 UTC, yelizariev approved these changes
Ok, but fix versions please

2019-05-29 10:42 UTC, yelizariev commented on pos_keyboard/README.rst
> +      To get a guaranteed support you are kindly requested to purchase the module at `odoo apps store <https://apps.odoo.com/apps/modules/10.0/pos_keyboard/>`__.
11.0

2019-05-30 11:02 UTC, Ramil-Mukhametzyanov commented on pos_pin/doc/changelog.rst
> +- **Fix:** Id of undefined error appeared when a pin was entered correctly
checked :+1:

2019-05-30 11:02 UTC, Ramil-Mukhametzyanov commented on pos_multi_session_restaurant/doc/changelog.rst
> +**Fix:** Property of undefined error might happen when restaurant multisession loses floors with opened orders in it
checked :+1:

2019-05-31 06:11 UTC, Ramil-Mukhametzyanov commented on pos_multi_session/doc/changelog.rst
> +- **Fix:** After restoring the connection, numbers of created and paid offline POS orders were not counted, that could lead to order loss in some cases
checked :+1:

2019-05-31 06:12 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-31 07:14 UTC, GabbasovDinar approved these changes

2019-05-31 08:21 UTC, merged